packages:
  - artifacts/*
  - lib/*
  - scripts

onlyBuiltDependencies:
  - esbuild

catalog:
  '@replit/vite-plugin-cartographer': 0.2.8
  '@replit/vite-plugin-runtime-error-modal': 0.0.3
  '@tailwindcss/vite': 4.3.1
  '@tanstack/react-query': 5.101.2
  '@types/node': 22.20.0
  '@types/react': 19.1.17
  '@types/react-dom': 19.1.11
  '@vitejs/plugin-react': 4.7.0
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  drizzle-orm: 0.41.0
  framer-motion: 12.40.0
  lucide-react: 0.511.0
  react: 19.1.0
  react-dom: 19.1.0
  tailwind-merge: 3.6.0
  tailwindcss: 4.3.1
  tsx: 4.22.4
  vite: 6.4.3
  zod: 3.25.76
