/**
 * LayoverOfflinePlanCard — what a traveller keeps when the read fails, beyond
 * the return time. census §16 L151 and §20 L233.
 *
 * ── THE GAP ──────────────────────────────────────────────────────────────────
 * L150 closed the deadline and the failure screen gained one number. Everything
 * else about the layover still died with the network: WHERE the traveller was
 * going, WHICH airport they have to be back at, and HOW FAR OUT the certified
 * envelope reached. L233 asks for exactly the first of those — "offline after
 * leaving → cached return plan remains visible with a stale indicator" — and
 * L151 for the second and third.
 *
 * ── EVERY LINE HERE IS THE SERVER'S, AND IS CAPTIONED AS OLD ─────────────────
 * The record comes from `lib/layoverPlanCache`, which stores the server's own
 * `certifiedAt` / `staleAfter` verbatim, and freshness is decided by the ONE
 * rule this client has — `bundleFreshness` — the same one a live bundle goes
 * through. Nothing is recomputed here and no second, gentler offline rule
 * exists: that is precisely how a cache ends up presenting an old answer as a
 * current one.
 *
 * ── THE ENVELOPE MAY NOT BE RENDERED AS A PROMISE ────────────────────────────
 * `LayoverSafeEnvelope.certifiedInward` is permanently `false`: a point inside
 * the disc is NOT certified to fit, because there is no routed provider to
 * certify it with. So the area is stated only in the direction it is proved —
 * OUTSIDE it, nothing fits at any speed — and the contracted planning edge is
 * named as what was planned against, never as a safe zone. A surface that drew
 * this disc as "safe" would be the L293 fabrication in a new shape, offline.
 *
 * ── AND WHAT CAN STILL BE WORKED OUT (L156) ──────────────────────────────────
 * The offline replan rule's answer is rendered when the caller asks it: either
 * a conservative usable-minutes figure — the certified window MINUS the age of
 * the answer, so it can only get more cautious — or the server's own refusal,
 * said plainly. Neither is computed here.
 *
 * ── WHAT IS NOT HERE ─────────────────────────────────────────────────────────
 * No route (there is no routing provider), no flight or gate status (no flight
 * feed), no crew meeting point (the bundle still answers `no_crew_storage`), no
 * phrases (`no_phrase_catalogue`). Those are L152–L155 and each is a server-side
 * absence; none of them is papered over with something this card invented.
 */
import React from 'react';
import { View, Text, StyleSheet } from 'react-native';
import { MapPin, Plane } from 'lucide-react-native';
import { color, space, radius, type as t } from '../../theme/tokens.ts';
import { fmtDur } from './layoverFormat.ts';
import { bundleFreshness } from './layoverReturnFacts.ts';
import type { CachedLayoverPlan } from '../../lib/layoverPlanCache.ts';
import type { LocalReplanDecision, LocalReplanRefusal } from './layoverLocalReplan.ts';

interface Props {
  /** The record as stored. `null` renders nothing — never a placeholder plan. */
  plan: CachedLayoverPlan | null;
  /**
   * §16 L156 — the offline replan rule's answer, DECIDED BY THE CALLER.
   *
   * `layoverLocalReplan.localReplan` is the client mirror of the server's own
   * rule, pinned against a fixture generated by executing it. It is asked in
   * the screen rather than here so this card stays a consumer, exactly as
   * `LayoverMapCard` consumes bands it does not compute. `null` means the rule
   * could not be asked — no cached schedule — and renders as nothing rather
   * than as a refusal the rule never issued.
   */
  replan?: LocalReplanDecision | null;
  /** Injected so the stale indicator is testable without a fake clock. */
  nowMs: number;
}

/**
 * The server's three refusals, in a traveller's words. The vocabulary is the
 * server's and is never widened here: an unrecognised refusal is rendered as
 * its own token rather than dropped, on the same principle as Appendix A codes.
 */
const REFUSAL_COPY: Record<LocalReplanRefusal, string> = {
  bundle_stale:
    'This answer is older than it is meant to be relied on, so nothing new can be worked out from it offline.',
  schedule_changed_since_certification:
    'Your flight times changed after this was certified, so it is about a different flight.',
  already_past_hard_return:
    'The certified return time has passed. Head back to the airport now.',
};

function km(metres: number): string {
  return metres >= 10_000
    ? `${Math.round(metres / 1000)} km`
    : `${Math.round(metres / 100) / 10} km`;
}

export function LayoverOfflinePlanCard({ plan, replan, nowMs }: Props) {
  if (!plan) return null;

  const freshness = bundleFreshness(plan, nowMs);
  // The same three standings `describeDeadline` uses, and the same words: an
  // unparseable instant is UNKNOWN age, which is not the same as fresh.
  const staleness = !freshness.known
    ? 'Last certified — age unknown. Re-check before you rely on it.'
    : freshness.stale
      ? `Last certified ${freshness.ageMinutes} min ago — this plan may be out of date.`
      : null;

  return (
    <View style={styles.card} testID="layover-cached-plan">
      <Text style={styles.label}>Your last certified plan</Text>

      {/* L151 — the airport half. The one place the traveller has to be back at,
          kept through the network dying. */}
      <View style={styles.airportRow} testID="layover-cached-plan-airport">
        <Plane size={14} color={color.mute} />
        <Text style={styles.airportText}>
          {plan.airport.iataCode}
          {plan.airport.name ? ` — ${plan.airport.name}` : ''}
          {plan.airport.city ? `, ${plan.airport.city}` : ''}
        </Text>
      </View>

      {/* L233 — the plan itself. An empty plan is a real answer and says so
          rather than rendering as a section that failed to load. */}
      {plan.stops.length > 0 ? (
        plan.stops.map((s, i) => (
          <View key={`${s.title}-${i}`} style={styles.stopRow} testID="layover-cached-plan-stop">
            <MapPin size={13} color={color.faint} />
            <Text style={styles.stopText}>
              {s.title} · {fmtDur(s.durationMin)}
              {s.travelMin > 0 ? ` · ${fmtDur(s.travelMin)} to get there` : ''}
              {s.insideAirport ? ' · inside the airport' : ''}
            </Text>
          </View>
        ))
      ) : (
        <Text style={styles.stopText} testID="layover-cached-plan-empty">
          No stops were on this plan when it was last certified.
        </Text>
      )}

      {/* L151 — the area half, stated only in the direction it is proved. */}
      {plan.envelope && (
        <View style={styles.envelopeBox} testID="layover-cached-plan-envelope">
          <Text style={styles.envelopeText}>
            Beyond about {km(plan.envelope.radiusMetres)} from this airport, nothing fitted the{' '}
            {fmtDur(plan.envelope.usableMinutes)} window at any speed.
          </Text>
          <Text style={styles.envelopeText}>
            Planning ran to about {km(plan.envelope.plannedRadiusMetres)}. Being inside that is not
            a promise anything fits — no route was ever measured.
          </Text>
        </View>
      )}

      {/* §16 L156 — "local conservative fallback only if deterministic inputs
          suffice; otherwise show unavailable/stale". Both halves, and the
          allowed half can only ever be MORE cautious than the certified figure:
          it is that window minus the age of the answer. */}
      {replan && (
        replan.allowed && replan.conservativeUsableMinutes != null ? (
          <Text style={styles.replan} testID="layover-cached-plan-replan">
            Working offline, assume no more than {fmtDur(replan.conservativeUsableMinutes)} of
            usable time — the certified window less how old this answer is.
          </Text>
        ) : (
          <View testID="layover-cached-plan-replan-refused">
            {replan.refusals.map((r) => (
              <Text key={r} style={styles.replanRefused}>
                {REFUSAL_COPY[r] ?? r}
              </Text>
            ))}
          </View>
        )
      )}

      {staleness && (
        <Text style={styles.staleness} testID="layover-cached-plan-staleness">
          {staleness}
        </Text>
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  card:        { marginTop: space.sm, alignSelf: 'stretch', backgroundColor: color.paperRaised, borderRadius: radius.md, borderWidth: 1, borderColor: color.haze, padding: space.md, gap: 4 },
  label:       { ...t.stamp, color: color.mute, textTransform: 'uppercase' },
  airportRow:  { flexDirection: 'row', alignItems: 'center', gap: 6 },
  airportText: { ...t.small, color: color.ink, fontWeight: '700' },
  stopRow:     { flexDirection: 'row', alignItems: 'center', gap: 6 },
  stopText:    { ...t.small, color: color.mute, flexShrink: 1 },
  envelopeBox: { borderTopWidth: 1, borderTopColor: color.haze, marginTop: 4, paddingTop: 4, gap: 2 },
  envelopeText:{ ...t.small, color: color.faint },
  staleness:   { ...t.small, color: color.warn, fontWeight: '700', marginTop: 4 },
  replan:      { ...t.small, color: color.ink, marginTop: 4 },
  replanRefused:{ ...t.small, color: color.mute, marginTop: 4 },
});
