#!/usr/bin/env node
/**
 * check:trip-write-path-inventory — Trips spec §24 Phase 0, census-trips TR434:
 * "inventory the existing Trip tables / routes / services against the new
 * kernel and freeze semantic drift by documenting current write paths; do not
 * big-bang rewrite."
 *
 * The inventory is GENERATED from the tree, not typed by hand, so it cannot
 * be out of date without this check saying so:
 *
 *   tables          every `CREATE TABLE trips | trip_*` in src/migrations, with
 *                   the migration that created it and the kernel migrations
 *                   (2420 and the trip_kernel_* chain) whose SQL writes it;
 *   kernel commands the command unions in lib/tripKernel.ts;
 *   kernel issuers  every server site that issues a command (executeTripCommand
 *                   or the rpc by name);
 *   direct writes   every server site that writes a trip table around the
 *                   kernel (`.from("trip_*").insert|update|upsert|delete`);
 *   routes          every /trips route, each write classified as kernel,
 *                   direct, both or neither by what its handler body does;
 *   services        the trip service and library modules.
 *
 *   pnpm -s check:trip-write-path-inventory            regenerates the block
 *   pnpm -s check:trip-write-path-inventory -- --check  fails when the tree's
 *                                                        inventory differs from
 *                                                        the document's block
 *
 * The FREEZE: a new table, route, direct write path, kernel command or
 * service module changes the generated block, and CI refuses the change until
 * the document is regenerated in the same commit — the drift is documented or
 * it is red. Nothing here rewrites anything; the ratchets that shrink the
 * direct-write set live in check:trip-kernel-writers, check:trip-write-validation
 * and check:trip-policy-callsites, and this document is where they start from.
 *
 * LIMITS, stated: a write through `.from(variable)` is invisible to the same
 * regex that check:write-path-columns uses, and says so in the block's
 * footer; a kernel migration is recognised by its file name (2420 or
 * `trip_kernel`), and its writes by the literal `INSERT INTO | UPDATE |
 * DELETE FROM public.<table>`.
 */
import { existsSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
export const API_ROOT = path.resolve(HERE, "../..");
export const DOC_PATH = path.resolve(API_ROOT, "../../docs/architecture/trips-phase0-inventory.md");
export const BEGIN = "<!-- trip-write-path-inventory:begin — generated by src/scripts/tripWritePathInventory.ts; do not edit by hand -->";
export const END = "<!-- trip-write-path-inventory:end -->";

export interface TableEntry { table: string; createdBy: string; kernelWriters: string[] }
export interface SiteEntry { file: string; kind: "executeTripCommand" | "rpc"; commandTypes: string[] }
export interface DirectWriteEntry { file: string; table: string; verb: "insert" | "update" | "upsert" | "delete" }
export interface RouteEntry { method: string; path: string; file: string; writes: "read" | "kernel" | "direct" | "both" | "none" }
export interface TripInventory {
  tables: TableEntry[];
  kernelCommands: string[];
  kernelIssuers: SiteEntry[];
  directWrites: DirectWriteEntry[];
  routes: RouteEntry[];
  services: string[];
}

const TABLE_RE = /CREATE TABLE(?: IF NOT EXISTS)?\s+(?:public\.)?"?(trips|trip_[a-z_]+)"?/g;
const WRITE_RE = /\.from\(\s*"(trips|trip_[a-z_]+)"\s*\)\s*\.\s*(insert|update|upsert|delete)\b/gs;
const ROUTE_RE = /router\.(get|post|patch|put|delete)\(\s*"(\/trips[^"]*)"/g;

function walk(dir: string, out: string[] = []): string[] {
  for (const name of readdirSync(dir)) {
    const p = path.join(dir, name);
    if (statSync(p).isDirectory()) { if (name !== "node_modules") walk(p, out); }
    else if (p.endsWith(".ts") && !p.endsWith(".d.ts")) out.push(p);
  }
  return out;
}
const rel = (p: string): string => path.relative(API_ROOT, p).split(path.sep).join("/");
const isServer = (r: string): boolean => r.startsWith("src/") && !r.startsWith("src/test/") && !r.startsWith("src/scripts/") && !r.startsWith("src/scenarios/");

export function buildTripInventory(root: string = API_ROOT): TripInventory {
  const migrationsDir = path.join(root, "src/migrations");
  const migrations = readdirSync(migrationsDir).filter((f) => f.endsWith(".sql")).sort();
  const kernelMigrations = migrations.filter((f) => f.startsWith("2420_") || f.includes("trip_kernel"));
  const kernelSql = kernelMigrations.map((f) => ({ f, text: readFileSync(path.join(migrationsDir, f), "utf8") }));

  // tables: first migration that creates each
  const created = new Map<string, string>();
  for (const f of migrations) {
    const text = readFileSync(path.join(migrationsDir, f), "utf8");
    for (const m of text.matchAll(TABLE_RE)) if (!created.has(m[1]!)) created.set(m[1]!, f);
  }
  // A table the server writes (directly or through the kernel) that no migration
  // in src/migrations creates predates the chain: the spine's `trips`, for one.
  const kernelWritten = (table: string): string[] => kernelSql.filter(({ text }) => new RegExp(`(INSERT INTO|UPDATE|DELETE FROM)\\s+public\\.${table}\\b`).test(text)).map(({ f }) => f.slice(0, 4));
  const baselineTables = new Set<string>();
  for (const { text } of kernelSql) for (const m of text.matchAll(/(?:INSERT INTO|UPDATE|DELETE FROM)\s+public\.(trips|trip_[a-z_]+)\b/g)) if (!created.has(m[1]!)) baselineTables.add(m[1]!);
  const tables: TableEntry[] = [...created.entries()].map(([table, createdBy]) => ({ table, createdBy, kernelWriters: kernelWritten(table) }));

  // kernel commands: every quoted name in the command-type unions
  // Line by line, not "up to the first semicolon": the unions carry comments,
  // and a comment with a `;` in it would end the scan early and lose commands.
  const kernelLines = readFileSync(path.join(root, "src/lib/tripKernel.ts"), "utf8").split("\n");
  const commands = new Set<string>();
  for (let i = 0; i < kernelLines.length; i++) {
    if (!/^export type Trip\w*CommandType =/.test(kernelLines[i]!)) continue;
    for (let j = i; j < kernelLines.length; j++) {
      const line = kernelLines[j]!.trim();
      const member = j === i || line === "" || line.startsWith("//") || line.startsWith("/*") || line.startsWith("*") || line.startsWith("|");
      if (!member) break;
      if (line.startsWith("//") || line.startsWith("/*") || line.startsWith("*")) continue;   // a comment ending in `;` is not the end of the union
      for (const c of line.matchAll(/"([A-Z_]+)"/g)) commands.add(c[1]!);
      if (/;\s*(\/\/.*)?$/.test(line)) break;
    }
  }
  const kernelCommands = [...commands].sort();

  // sites
  const files = walk(path.join(root, "src")).map(rel).filter(isServer).sort();
  const kernelIssuers: SiteEntry[] = [];
  const directWrites: DirectWriteEntry[] = [];
  const bodies = new Map<string, string>();
  for (const r of files) {
    const text = readFileSync(path.join(root, r), "utf8");
    bodies.set(r, text);
    if (r !== "src/lib/tripKernel.ts") {
      for (const kind of ["executeTripCommand", "rpc"] as const) {
        const re = kind === "executeTripCommand" ? /executeTripCommand\(/g : /rpc\(\s*"trip_kernel_execute"/g;
        const types = new Set<string>();
        let hits = 0;
        for (const m of text.matchAll(re)) {
          hits += 1;
          const t = /type:\s*"([A-Z_]+)"/.exec(text.slice(m.index!, m.index! + 600));
          if (t) types.add(t[1]!);
        }
        if (hits > 0) kernelIssuers.push({ file: r, kind, commandTypes: [...types].sort() });
      }
    }
    const seen = new Set<string>();
    for (const m of text.matchAll(WRITE_RE)) {
      const key = `${m[1]}:${m[2]}`;
      if (seen.has(key)) continue;
      seen.add(key);
      directWrites.push({ file: r, table: m[1]!, verb: m[2] as DirectWriteEntry["verb"] });
    }
  }

  for (const d of directWrites) if (!created.has(d.table)) baselineTables.add(d.table);
  for (const table of baselineTables) tables.push({ table, createdBy: "baseline (predates src/migrations)", kernelWriters: kernelWritten(table) });
  tables.sort((a, b) => a.table.localeCompare(b.table));

  // routes, classified by what their handler body does
  const routes: RouteEntry[] = [];
  for (const r of files.filter((f) => f.startsWith("src/routes/"))) {
    const text = bodies.get(r)!;
    const starts = [...text.matchAll(/^router\.(get|post|patch|put|delete)\(/gm)].map((m) => m.index!);
    for (const m of text.matchAll(ROUTE_RE)) {
      const at = m.index!;
      const next = starts.find((s) => s > at) ?? text.length;
      const body = text.slice(at, next);
      const kernel = /executeTripCommand\(|rpc\(\s*"trip_kernel_execute"/.test(body);
      const direct = new RegExp(WRITE_RE.source, "s").test(body);
      const method = m[1]!.toUpperCase();
      routes.push({ method, path: m[2]!, file: r, writes: method === "GET" ? "read" : kernel && direct ? "both" : kernel ? "kernel" : direct ? "direct" : "none" });
    }
  }
  routes.sort((a, b) => a.path.localeCompare(b.path) || a.method.localeCompare(b.method));

  const services = files.filter((f) => f.startsWith("src/services/trips/") || f.startsWith("src/services/tripCrew/") || /^src\/lib\/trip[A-Z]/.test(f));
  return { tables, kernelCommands, kernelIssuers, directWrites, routes, services };
}

export function renderInventory(inv: TripInventory): string {
  const out: string[] = [BEGIN, ""];
  out.push(`### Tables — ${inv.tables.length}`, "", "| table | created by | kernel migrations that write it |", "| --- | --- | --- |");
  for (const t of inv.tables) out.push(`| \`${t.table}\` | \`${t.createdBy}\` | ${t.kernelWriters.length === 0 ? "—" : t.kernelWriters.join(", ")} |`);
  out.push("", `### Kernel commands — ${inv.kernelCommands.length}`, "", inv.kernelCommands.map((c) => `\`${c}\``).join(" · "));
  out.push("", `### Kernel issuers — ${inv.kernelIssuers.length} site file(s)`, "", "| file | via | command types issued in that file |", "| --- | --- | --- |");
  for (const s of inv.kernelIssuers) out.push(`| \`${s.file}\` | ${s.kind} | ${s.commandTypes.length === 0 ? "(dynamic)" : s.commandTypes.map((c) => `\`${c}\``).join(", ")} |`);
  out.push("", `### Direct write paths around the kernel — ${inv.directWrites.length}`, "", "| file | table | verb |", "| --- | --- | --- |");
  for (const d of inv.directWrites) out.push(`| \`${d.file}\` | \`${d.table}\` | ${d.verb} |`);
  const counts = { read: 0, kernel: 0, direct: 0, both: 0, none: 0 } as Record<RouteEntry["writes"], number>;
  for (const r of inv.routes) counts[r.writes] += 1;
  out.push("", `### Routes under /trips — ${inv.routes.length} (${counts.read} reads; writes: ${counts.kernel} kernel, ${counts.direct} direct, ${counts.both} both, ${counts.none} neither)`, "", "| method | path | file | writes through |", "| --- | --- | --- | --- |");
  for (const r of inv.routes) out.push(`| ${r.method} | \`${r.path}\` | \`${r.file}\` | ${r.writes} |`);
  out.push("", `### Trip service and library modules — ${inv.services.length}`, "", inv.services.map((s) => `\`${s}\``).join(" · "));
  out.push("", "_Limits: a write through `.from(variable)` is invisible to this scan (as to check:write-path-columns); a kernel migration is one named 2420 or `trip_kernel`, and its writes are the literal `INSERT INTO | UPDATE | DELETE FROM public.<table>`._", "", END);
  return out.join("\n");
}

/** The block currently in the document, or null when the document or a marker is missing. */
export function documentBlock(doc: string): string | null {
  const b = doc.indexOf(BEGIN); const e = doc.indexOf(END);
  if (b < 0 || e < 0 || e < b) return null;
  return doc.slice(b, e + END.length);
}

export function withBlock(doc: string, block: string): string {
  const b = doc.indexOf(BEGIN); const e = doc.indexOf(END);
  if (b < 0 || e < 0 || e < b) throw new Error(`${DOC_PATH} has no ${BEGIN.slice(0, 40)}… / …end markers`);
  return doc.slice(0, b) + block + doc.slice(e + END.length);
}

/** Lines in one block and not the other — what a reviewer needs to see. */
export function blockDrift(current: string | null, fresh: string): { added: string[]; removed: string[] } {
  const a = new Set((current ?? "").split("\n")); const b = new Set(fresh.split("\n"));
  return { added: [...b].filter((l) => !a.has(l)), removed: [...a].filter((l) => !b.has(l)) };
}

const invokedDirectly = process.argv[1] ? path.resolve(process.argv[1]) === fileURLToPath(import.meta.url) : false;
if (invokedDirectly) {
  const check = process.argv.includes("--check");
  const fresh = renderInventory(buildTripInventory());
  if (!existsSync(DOC_PATH)) { console.error(`::error::${DOC_PATH} does not exist`); process.exit(2); }
  const doc = readFileSync(DOC_PATH, "utf8");
  const current = documentBlock(doc);
  if (check) {
    if (current === fresh) { console.log(`check:trip-write-path-inventory PASSED — the document's inventory is the tree's.`); process.exit(0); }
    const d = blockDrift(current, fresh);
    console.error(`::error::${path.relative(process.cwd(), DOC_PATH)} is out of date: ${d.added.length} line(s) the tree has that the document lacks, ${d.removed.length} the document has that the tree lacks. Regenerate it in this commit: pnpm -s check:trip-write-path-inventory`);
    for (const l of d.added.slice(0, 40)) console.error(`  + ${l}`);
    for (const l of d.removed.slice(0, 40)) console.error(`  - ${l}`);
    process.exit(1);
  }
  writeFileSync(DOC_PATH, withBlock(doc, fresh), "utf8");
  console.log(`inventory regenerated into ${path.relative(process.cwd(), DOC_PATH)}${current === fresh ? " (unchanged)" : ""}`);
}
