/**
 * Writes the committed, machine-readable graph snapshot.
 *
 *   node --import tsx/esm src/lib/deletion/writeSnapshot.ts
 *
 * WHY A SNAPSHOT AT ALL, when `deletionGraph()` recomputes the same thing from
 * the baseline on every call: a decision this size needs an artefact a person
 * (or a lawyer, or an owner answering D6) can read and diff, without running
 * anything. deletionGraph.test.ts recomputes the graph and compares, so the
 * snapshot cannot drift away from the code that produced it.
 *
 * WHAT IS DELIBERATELY EXCLUDED: the per-table code-scan counts and route
 * reader lists. They change whenever an unrelated route is edited, and a
 * snapshot that fails CI for a reason that has nothing to do with deletion
 * teaches people to regenerate it without reading it. They are recomputed live
 * by `deletionGraph()` instead.
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { deletionGraph, candidateCounts, baselineUserLinkCounts, REPO_ROOT } from "./index.js";
import type { DeletionGraphNode } from "./types.js";

export const SNAPSHOT_PATH = resolve(REPO_ROOT, "src/lib/deletion/deletionGraph.snapshot.json");

/** The stable projection of a node that the snapshot stores. */
export function snapshotNode(n: DeletionGraphNode): Record<string, unknown> {
  return {
    table: n.table,
    inBaseline: n.inBaseline,
    userLink: n.userLink,
    statedFate: n.statedFate,
    manifestCoverageGap: n.manifestCoverageGap,
    userColumns: n.userColumns,
    signals: n.signals,
    visibility: {
      rlsEnabled: n.visibility.rlsEnabled,
      policyCount: n.visibility.policyCount,
      exposure: n.visibility.exposure,
      nonOwnerReadable: n.visibility.nonOwnerReadable,
      selectPolicies: n.visibility.selectPolicies,
    },
    derivative: {
      nameSuggestsDerived: n.derivative.nameSuggestsDerived,
      derivedFrom: n.derivative.derivedFrom,
      parents: n.derivative.parents,
    },
    retention: {
      governedElsewhere: n.retention.governedElsewhere,
      sweepers: n.retention.sweepers,
      rpcs: n.retention.rpcs.map((r) => r.fn),
      expiryColumns: n.retention.expiryColumns,
    },
    guardTriggers: n.guardTriggers,
    propagation: {
      DELETE: { mechanism: n.propagation.DELETE.mechanism, obstacles: n.propagation.DELETE.obstacles, blockingChildren: n.propagation.DELETE.blockingChildren, cascadeChildren: n.propagation.DELETE.cascadeChildren },
      ANONYMIZE: { mechanism: n.propagation.ANONYMIZE.mechanism, obstacles: n.propagation.ANONYMIZE.obstacles },
      RETAIN: { mechanism: n.propagation.RETAIN.mechanism, obstacles: n.propagation.RETAIN.obstacles },
    },
    candidate: n.candidate,
    candidateEvidence: n.candidateEvidence,
    ...(n.handNote ? { handNote: n.handNote } : {}),
  };
}

export function snapshotBody(): Record<string, unknown> {
  const nodes = deletionGraph();
  return {
    _readme:
      "Generated by src/lib/deletion/writeSnapshot.ts. A CANDIDATE class is an engineering observation, " +
      "not a deletion policy: OWNER_REQUIRED means the evidence does not decide and owner decision D6 must. " +
      "Field provenance is declared in src/lib/deletion/provenance.ts.",
    tableCount: nodes.length,
    userLinkCounts: baselineUserLinkCounts(),
    candidateCounts: candidateCounts(nodes),
    nodes: nodes.map(snapshotNode),
  };
}

/**
 * Serialised ONE NODE PER LINE. Still valid JSON, but a change to one table is
 * a one-line diff instead of a forty-line one — which is the difference between
 * a reviewable artefact and a blob people approve without reading.
 */
export function serializeSnapshot(body: Record<string, unknown>): string {
  const { nodes, ...head } = body as { nodes: unknown[] } & Record<string, unknown>;
  const headText = Object.entries(head)
    .map(([k, v]) => ` ${JSON.stringify(k)}: ${JSON.stringify(v)}`)
    .join(",\n");
  const nodeText = nodes.map((n) => `  ${JSON.stringify(n)}`).join(",\n");
  return `{\n${headText},\n "nodes": [\n${nodeText}\n ]\n}\n`;
}

function main(): void {
  const body = snapshotBody();
  writeFileSync(SNAPSHOT_PATH, serializeSnapshot(body), "utf8");
  console.log(`wrote ${SNAPSHOT_PATH} (${(body as any).tableCount} tables)`);
}

if (import.meta.url === `file://${process.argv[1]}`) main();
