"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var health_1 = require("./health");
var auth_1 = require("./auth");
var trips_1 = require("./trips");
var posts_1 = require("./posts");
var follows_1 = require("./follows");
var friends_1 = require("./friends");
var profile_1 = require("./profile");
var passport_1 = require("./passport");
var telegraph_1 = require("./telegraph");
var telegraphChat_1 = require("./telegraphChat");
var telegraphStream_1 = require("./telegraphStream");
var messaging_1 = require("./messaging");
var requests_1 = require("./requests");
var plan_1 = require("./plan");
var groupChat_1 = require("./groupChat");
var availability_1 = require("./availability");
var meetups_1 = require("./meetups");
var preferences_1 = require("./preferences");
var dailyBrief_1 = require("./dailyBrief");
var telegraphCommands_1 = require("./telegraphCommands");
var telegraphFeedback_1 = require("./telegraphFeedback");
var discovery_1 = require("./discovery");
var blocks_1 = require("./blocks");
var location_1 = require("./location");
var locationPreferences_1 = require("./locationPreferences");
var geofence_1 = require("./geofence");
var safeReturn_1 = require("./safeReturn");
var highlights_1 = require("./highlights");
var places_1 = require("./places");
var pulse_1 = require("./pulse");
var admin_1 = require("./admin");
var notifications_1 = require("./notifications");
var router = (0, express_1.Router)();
router.use(health_1.default);
router.use(auth_1.default);
router.use(trips_1.default);
router.use(posts_1.default);
router.use(follows_1.default);
router.use(friends_1.default);
router.use(profile_1.default);
router.use(passport_1.default);
router.use(telegraph_1.default);
router.use(telegraphChat_1.default);
router.use(telegraphStream_1.default);
router.use(telegraphFeedback_1.default);
router.use(telegraphCommands_1.default);
router.use(messaging_1.default);
router.use(requests_1.default);
router.use(plan_1.default);
router.use(groupChat_1.default);
router.use(availability_1.default);
router.use(meetups_1.default);
router.use(preferences_1.default);
router.use(dailyBrief_1.default);
router.use(discovery_1.default);
router.use(blocks_1.default);
router.use(location_1.default);
router.use(locationPreferences_1.default);
router.use(geofence_1.default);
router.use(safeReturn_1.default);
router.use(highlights_1.default);
router.use(places_1.default);
router.use(pulse_1.default);
router.use(admin_1.default);
router.use(notifications_1.default);
exports.default = router;
