import { Router, type IRouter } from "express";
import verificationRouter from "./verification.js";
import devicesRouter from "./devices";
import keyPackagesRouter from "./keyPackages";
import healthRouter from "./health";
import authRouter from "./auth";
import tripsRouter from "./trips";
import postsRouter from "./posts";
import followsRouter from "./follows";
import friendsRouter from "./friends";
import profileRouter from "./profile";
import passportRouter from "./passport";
import telegraphRouter from "./telegraph";
import telegraphChatRouter from "./telegraphChat";
import telegraphStreamRouter from "./telegraphStream";
import messagingRouter from "./messaging";
import requestsRouter from "./requests";
import planRouter from "./plan";
import groupChatRouter from "./groupChat";
import availabilityRouter from "./availability";
import meetupsRouter from "./meetups";
import preferencesRouter from "./preferences";
import dailyBriefRouter from "./dailyBrief";
import telegraphCommandsRouter from "./telegraphCommands";
import telegraphFeedbackRouter from "./telegraphFeedback";
import discoveryRouter from "./discovery";
import blocksRouter from "./blocks";
import locationRouter from "./location";
import locationPreferencesRouter from "./locationPreferences";
import mapTravelersRouter from "./mapTravelers";
import geofenceRouter from "./geofence";
import intelRouter from "./intel.js";
import intelCoverageRouter from "./intelCoverage.js";
import intelApiRouter from "./intelApi.js";
import safeReturnRouter from "./safeReturn";
import tripCrewLocationRouter from "./tripCrewLocation";
import highlightsRouter from "./highlights";
import placesRouter from "./places";
import locationsRouter from "./locations";
import pulseRouter from "./pulse";
import adminRouter from "./admin";
import trustAdminRouter from "./trust-admin";
import phoneVerificationRouter from "./phoneVerification";
import passportStampsRouter from "./passportStamps";
import hiddenGemsRouter from "./hiddenGems";
import notificationsRouter from "./notifications";
import airportRouter from "./airport";
import featureFlagsRouter from "./featureFlags";
import tagsRouter from "./tags";
import hashtagsRouter from "./hashtags";
import circleAgeSettingsRouter from "./circleAgeSettings";
import rentABuddyRouter from "./rentABuddy";
import rentABuddyMarketplaceRouter from "./rentABuddyMarketplace";
import rentABuddyRolloutRouter from "./rentABuddyRollout";
import rentABuddySpecRouter from "./rentABuddySpec";
import compassRouter from "./compass";
import compassHomeRouter from "./compassHome";
import compassSenseRouter from "./compassSense";
import compassLiveRouter from "./compassLive";
import compassAutopilotRouter from "./compassAutopilot";
import compassOutcomesRouter from "./compassOutcomes";
import compassGraphRouter from "./compassGraph";
import adminCompassRouter from "./adminCompass";
import routePlanRouter from "./routePlan";
import interactionContextRouter from "./interactionContext";
import mutesRouter from "./mutes";
import savesRouter from "./saves";
import reportsRouter from "./reports";
import restrictRouter from "./restrict";
import eventsRouter from "./events";
import memoriesRouter from "./memories";
import storiesRouter from "./stories";
import closeFriendsRouter from "./closeFriends";
import reviewsRouter from "./reviews";
import appealsRouter from "./appeals";
import collectionsRouter from "./collections";
import wishlistRouter from "./wishlist";
import profileTabsRouter from "./profileTabs";
import tripsExpansionRouter from "./trips-expansion";
import stampsRouter from "./stamps";
import adminStampsRouter from "./adminStamps";
import adminGeocodeRouter from "./adminGeocode";
import adminRankingMetricsRouter from "./adminRankingMetrics";
import adminRankingConfigRouter from "./adminRankingConfig";
import stampCatalogRouter from "./stampCatalog";
import emergencyContactsRouter from "./emergencyContacts";
import crashReportRouter from "./crashReport";
import discoverySearchRouter from "./discoverySearch";
import inputAssistanceRouter from "./inputAssistance";
import searchHistoryRouter from "./searchHistory";
import postcardsRouter from "./postcards";
import engagementRouter from "./engagement";
import circleRouter from "./circle";
import rankEventsRouter from "./rankEvents";
import callsRouter from "./calls";
import moderationRouter from "./moderation";
import entryRequirementsRouter from "./entryRequirements";
import tripReadinessRouter from "./tripReadiness";
import tripBudgetIntelRouter from "./tripBudgetIntel";
import tripReservationsRouter from "./tripReservations";
import tripDraftRouter from "./tripDraft";
import visualsRouter from "./visuals";
import adminVisualsRouter from "./adminVisuals";
import adminPlaceImagesRouter from "./adminPlaceImages.js";
import neighborhoodsRouter from "./neighborhoods";
import stampShowcaseRouter from "./stampShowcase";
import stampAdmireRouter from "./stampAdmire";
import contentStampsRouter from "./contentStamps";
import countryEssentialsRouter from "./countryEssentials";
import mapSearchRouter from "./mapSearch";
import mapProjectionRouter from "./mapProjection";
import mapTelemetryRouter from "./mapTelemetry";
import mapObservationsRouter from "./mapObservations";
import locateFriendsRouter from "./locateFriends";
import mediaFileRouter from "./mediaFile";
import mediaWorldRouter from "./mediaWorld";
import mediaFeedRouter from "./mediaFeed";
import adminMediaRouter from "./adminMedia.js";
import mediaAnalyticsBatchRouter from "./mediaAnalyticsBatch.js";
import placesCanonicalRouter from "./placesCanonical";
import fsqPlacesRouter from "./fsqPlaces";
import ogRouter from "./og";
import adminPortavaPostsRouter from "./adminPortavaPosts.js";
import adminFeaturedRouter from "./adminFeatured";
import adminPlaceMismatchRouter from "./adminPlaceMismatch.js";
import featuredRouter from "./featured.js";
import placeLivingRouter from "./placeLiving.js";
import placeDaysRouter from "./placeDays.js";
import contentTranslationRouter from "./contentTranslation.js";
import sharedMomentsRouter from "./sharedMoments.js";
import placeRecapsRouter from "./placeRecaps.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(tripsRouter);
router.use(postsRouter);
router.use(profileRouter);
router.use(followsRouter);
router.use(friendsRouter);
router.use(passportRouter);
router.use(passportStampsRouter);
router.use(telegraphRouter);
router.use(telegraphChatRouter);
router.use(telegraphStreamRouter);
router.use(telegraphFeedbackRouter);
router.use(telegraphCommandsRouter);
router.use(messagingRouter);
router.use(requestsRouter);
router.use(planRouter);
router.use(groupChatRouter);
router.use(availabilityRouter);
router.use(meetupsRouter);
router.use(preferencesRouter);
router.use(dailyBriefRouter);
router.use(discoveryRouter);
router.use(blocksRouter);
router.use(locationRouter);
router.use(locationPreferencesRouter);
router.use(mapTravelersRouter);
router.use(geofenceRouter);
router.use(safeReturnRouter);
router.use(tripCrewLocationRouter);
router.use(highlightsRouter);
router.use(placesRouter);
router.use(locationsRouter);
router.use(pulseRouter);
router.use(adminRouter);
router.use(trustAdminRouter);
// Phone verification. Every rent_buddy_launch_controls row requires phone
// verification, but the product had no way to perform one — the only phone
// signal was rent_buddy_profiles.phone_verified, on the BUDDY table, written
// by nothing. These routes are the missing capability.
router.use(phoneVerificationRouter);
router.use(hiddenGemsRouter);
router.use(notificationsRouter);
router.use(airportRouter);
router.use(featureFlagsRouter);
router.use(tagsRouter);
router.use(hashtagsRouter);
router.use(circleAgeSettingsRouter);
router.use(rentABuddyRouter);
router.use(rentABuddySpecRouter);
router.use(rentABuddyMarketplaceRouter);
router.use(rentABuddyRolloutRouter);
router.use(compassRouter);
router.use(compassHomeRouter);
router.use(compassSenseRouter);
router.use(compassLiveRouter);
router.use(compassAutopilotRouter);
router.use(compassOutcomesRouter);
router.use(compassGraphRouter);
router.use(adminCompassRouter);
router.use(routePlanRouter);
router.use(interactionContextRouter);
router.use(mutesRouter);
router.use(savesRouter);
router.use(reportsRouter);
router.use(restrictRouter);
router.use(eventsRouter);
router.use(memoriesRouter);
router.use(storiesRouter);
router.use(closeFriendsRouter);
router.use(reviewsRouter);
router.use(appealsRouter);
router.use(collectionsRouter);
router.use(wishlistRouter);
router.use(profileTabsRouter);
router.use(tripsExpansionRouter);
router.use(postcardsRouter);
// Stamp Wave 2 routers (stampShowcase, stampAdmire) must be registered BEFORE
// stampsRouter. stamps.ts registers `GET /stamps/:stampId` which returns 400
// for non-UUID paths (e.g. "showcase") without calling next(), so any static
// /stamps/* path in a later router would be unreachable. Feature-flag gating
// is enforced inside each handler (isFlagEnabled), not by router ordering.
router.use(stampShowcaseRouter);
router.use(stampAdmireRouter);
// contentStampsRouter must be after stampAdmireRouter so /stamps/:id/admire
// routes win before the polymorphic /stamps/:entityType/:entityId DELETE.
router.use(contentStampsRouter);
router.use(stampsRouter);
router.use(adminStampsRouter);
router.use(adminGeocodeRouter);
router.use(adminRankingMetricsRouter);
router.use(adminRankingConfigRouter);
router.use(stampCatalogRouter);
router.use(emergencyContactsRouter);
router.use(crashReportRouter);
router.use(discoverySearchRouter);
router.use(inputAssistanceRouter);
router.use(searchHistoryRouter);
router.use(engagementRouter);
router.use(circleRouter);
router.use(rankEventsRouter);
router.use(callsRouter);
router.use(moderationRouter);
router.use(devicesRouter);
router.use(keyPackagesRouter);
router.use(verificationRouter);
router.use(entryRequirementsRouter);
router.use(tripReadinessRouter);
router.use(tripBudgetIntelRouter);
router.use(tripReservationsRouter);
router.use(tripDraftRouter);
router.use(visualsRouter);
router.use(adminVisualsRouter);
router.use(adminPlaceImagesRouter);
router.use(neighborhoodsRouter);
router.use(countryEssentialsRouter);
router.use(fsqPlacesRouter);
router.use(mapSearchRouter);
router.use(mapProjectionRouter);
router.use(mapTelemetryRouter);
router.use(mapObservationsRouter);
router.use(locateFriendsRouter);
router.use(mediaFileRouter);
// Media v2 World-first projection endpoints (§43). Registered BEFORE
// mediaFeedRouter so specific paths (/media/world, /media/people, /media/me,
// /media/timeline, /media/map) are not swallowed by mediaFeed's `/media/:id`.
router.use(mediaWorldRouter);
router.use(mediaFeedRouter);
router.use(adminMediaRouter);
router.use(mediaAnalyticsBatchRouter);
router.use(placesCanonicalRouter);
router.use(adminPlaceMismatchRouter);
router.use(ogRouter);
router.use(adminPortavaPostsRouter);
router.use(adminFeaturedRouter);
router.use(featuredRouter);
router.use(placeLivingRouter);
router.use(placeDaysRouter);
router.use(contentTranslationRouter);
router.use(sharedMomentsRouter);
router.use(placeRecapsRouter);
router.use(intelRouter);
router.use(intelCoverageRouter);
router.use(intelApiRouter);

export default router;
