import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import tripsRouter from "./trips";
import postsRouter from "./posts";
import followsRouter from "./follows";
import friendsRouter from "./friends";
import profileRouter from "./profile";
import passportRouter from "./passport";
import telegraphRouter from "./telegraph";
import telegraphChatRouter from "./telegraphChat";
import telegraphStreamRouter from "./telegraphStream";
import messagingRouter from "./messaging";
import requestsRouter from "./requests";
import planRouter from "./plan";
import groupChatRouter from "./groupChat";
import availabilityRouter from "./availability";
import meetupsRouter from "./meetups";
import preferencesRouter from "./preferences";
import dailyBriefRouter from "./dailyBrief";
import telegraphCommandsRouter from "./telegraphCommands";
import telegraphFeedbackRouter from "./telegraphFeedback";
import discoveryRouter from "./discovery";
import blocksRouter from "./blocks";
import locationRouter from "./location";
import locationPreferencesRouter from "./locationPreferences";
import mapTravelersRouter from "./mapTravelers";
import geofenceRouter from "./geofence";
import safeReturnRouter from "./safeReturn";
import tripCrewLocationRouter from "./tripCrewLocation";
import highlightsRouter from "./highlights";
import placesRouter from "./places";
import locationsRouter from "./locations";
import pulseRouter from "./pulse";
import adminRouter from "./admin";
import trustAdminRouter from "./trust-admin";
import passportStampsRouter from "./passportStamps";
import hiddenGemsRouter from "./hiddenGems";
import notificationsRouter from "./notifications";
import airportRouter from "./airport";
import featureFlagsRouter from "./featureFlags";
import tagsRouter from "./tags";
import hashtagsRouter from "./hashtags";
import circleAgeSettingsRouter from "./circleAgeSettings";
import rentABuddyRouter from "./rentABuddy";
import rentABuddyMarketplaceRouter from "./rentABuddyMarketplace";
import rentABuddyRolloutRouter from "./rentABuddyRollout";
import rentABuddySpecRouter from "./rentABuddySpec";
import compassRouter from "./compass";
import adminCompassRouter from "./adminCompass";
import routePlanRouter from "./routePlan";
import interactionContextRouter from "./interactionContext";
import mutesRouter from "./mutes";
import savesRouter from "./saves";
import reportsRouter from "./reports";
import restrictRouter from "./restrict";
import eventsRouter from "./events";
import memoriesRouter from "./memories";
import storiesRouter from "./stories";
import closeFriendsRouter from "./closeFriends";
import reviewsRouter from "./reviews";
import appealsRouter from "./appeals";
import collectionsRouter from "./collections";
import wishlistRouter from "./wishlist";
import profileTabsRouter from "./profileTabs";
import tripsExpansionRouter from "./trips-expansion";
import stampsRouter from "./stamps";
import adminStampsRouter from "./adminStamps";
import adminGeocodeRouter from "./adminGeocode";
import stampCatalogRouter from "./stampCatalog";
import emergencyContactsRouter from "./emergencyContacts";
import crashReportRouter from "./crashReport";
import discoverySearchRouter from "./discoverySearch";
import searchHistoryRouter from "./searchHistory";
import postcardsRouter from "./postcards";
import engagementRouter from "./engagement";
import circleRouter from "./circle";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(tripsRouter);
router.use(postsRouter);
router.use(profileRouter);
router.use(followsRouter);
router.use(friendsRouter);
router.use(passportRouter);
router.use(passportStampsRouter);
router.use(telegraphRouter);
router.use(telegraphChatRouter);
router.use(telegraphStreamRouter);
router.use(telegraphFeedbackRouter);
router.use(telegraphCommandsRouter);
router.use(messagingRouter);
router.use(requestsRouter);
router.use(planRouter);
router.use(groupChatRouter);
router.use(availabilityRouter);
router.use(meetupsRouter);
router.use(preferencesRouter);
router.use(dailyBriefRouter);
router.use(discoveryRouter);
router.use(blocksRouter);
router.use(locationRouter);
router.use(locationPreferencesRouter);
router.use(mapTravelersRouter);
router.use(geofenceRouter);
router.use(safeReturnRouter);
router.use(tripCrewLocationRouter);
router.use(highlightsRouter);
router.use(placesRouter);
router.use(locationsRouter);
router.use(pulseRouter);
router.use(adminRouter);
router.use(trustAdminRouter);
router.use(hiddenGemsRouter);
router.use(notificationsRouter);
router.use(airportRouter);
router.use(featureFlagsRouter);
router.use(tagsRouter);
router.use(hashtagsRouter);
router.use(circleAgeSettingsRouter);
router.use(rentABuddyRouter);
router.use(rentABuddySpecRouter);
router.use(rentABuddyMarketplaceRouter);
router.use(rentABuddyRolloutRouter);
router.use(compassRouter);
router.use(adminCompassRouter);
router.use(routePlanRouter);
router.use(interactionContextRouter);
router.use(mutesRouter);
router.use(savesRouter);
router.use(reportsRouter);
router.use(restrictRouter);
router.use(eventsRouter);
router.use(memoriesRouter);
router.use(storiesRouter);
router.use(closeFriendsRouter);
router.use(reviewsRouter);
router.use(appealsRouter);
router.use(collectionsRouter);
router.use(wishlistRouter);
router.use(profileTabsRouter);
router.use(tripsExpansionRouter);
router.use(postcardsRouter);
router.use(stampsRouter);
router.use(adminStampsRouter);
router.use(adminGeocodeRouter);
router.use(stampCatalogRouter);
router.use(emergencyContactsRouter);
router.use(crashReportRouter);
router.use(discoverySearchRouter);
router.use(searchHistoryRouter);
router.use(engagementRouter);
router.use(circleRouter);

export default router;
