import { Router, type IRouter } from "express";
import healthRouter from "./health";
import tripsRouter from "./trips";
import postsRouter from "./posts";
import followsRouter from "./follows";
import friendsRouter from "./friends";
import profileRouter from "./profile";
import passportRouter from "./passport";
import telegraphRouter from "./telegraph";
import telegraphChatRouter from "./telegraphChat";
import messagingRouter from "./messaging";
import requestsRouter from "./requests";
import planRouter from "./plan";
import groupChatRouter from "./groupChat";
import availabilityRouter from "./availability";
import meetupsRouter from "./meetups";
import preferencesRouter from "./preferences";
import dailyBriefRouter from "./dailyBrief";
import telegraphCommandsRouter from "./telegraphCommands";
import telegraphFeedbackRouter from "./telegraphFeedback";

const router: IRouter = Router();

router.use(healthRouter);
router.use(tripsRouter);
router.use(postsRouter);
router.use(followsRouter);
router.use(friendsRouter);
router.use(profileRouter);
router.use(passportRouter);
router.use(telegraphRouter);
router.use(telegraphChatRouter);
router.use(telegraphFeedbackRouter);
router.use(telegraphCommandsRouter);
router.use(messagingRouter);
router.use(requestsRouter);
router.use(planRouter);
router.use(groupChatRouter);
router.use(availabilityRouter);
router.use(meetupsRouter);
router.use(preferencesRouter);
router.use(dailyBriefRouter);

export default router;
