/**
 * Telegraph — AI activity recommendation engine.
 *
 * POST /api/telegraph/recommend
 *   Reads the caller's travel profile context and returns structured
 *   activity recommendations generated by GPT. Each recommendation
 *   carries a reason, location context, time estimate, and price level
 *   so the mobile client can render a rich TelegraphCard.
 *
 * Security: requireUser — anon callers rejected.
 */
import { Router } from "express";
import { z } from "zod";
import { requireUser, sendError } from "../lib/http";
import { getServiceClient } from "../lib/supabase";
import { openai } from "../lib/openai";
import { getWeatherContext } from "../lib/weatherCache.js";
import { buildCompassContext } from "../services/location/CompassLocationContext";
import type { SpanHashtag } from "../lib/enrichSpans";

const router = Router();

const recommendSchema = z.object({
  interests: z.array(z.string()).max(15).optional(),
  travelStyle: z.string().max(50).optional(),
  destination: z.string().max(100).optional(),
  tripDates: z
    .object({ start: z.string(), end: z.string() })
    .optional(),
  conversationContext: z.string().max(600).optional(),
  recipientName: z.string().max(100).optional(),
  defaultLanguage: z.string().max(10).optional(),
  count: z.number().int().min(1).max(5).default(3),
});

const VALID_CATEGORIES = new Set([
  "hotel", "food", "nightlife", "beach", "activity",
  "transport", "safety", "tip", "question",
]);
const VALID_PRICES = new Set(["free", "$", "$$", "$$$", "$$$$"]);

function sanitizeRec(r: any, idx: number) {
  return {
    id: typeof r.id === "string" ? r.id : `rec_${Date.now()}_${idx}`,
    title: typeof r.title === "string" ? r.title.slice(0, 120) : "Activity",
    category: VALID_CATEGORIES.has(r.category) ? r.category : "activity",
    reason: typeof r.reason === "string" ? r.reason.slice(0, 300) : "",
    locationContext: typeof r.locationContext === "string" ? r.locationContext.slice(0, 150) : "",
    estimatedTime: typeof r.estimatedTime === "string" ? r.estimatedTime.slice(0, 60) : "",
    priceLevel: VALID_PRICES.has(r.priceLevel) ? r.priceLevel : "$",
    imageUrl: typeof r.imageUrl === "string" ? r.imageUrl : null,
  };
}

/* ===========================================================================
 * POST /telegraph/recommend
 * ===========================================================================
 */
router.post("/telegraph/recommend", async (req, res) => {
  const auth = await requireUser(req, res);
  if (!auth) return;

  const parsed = recommendSchema.safeParse(req.body);
  if (!parsed.success) {
    sendError(res, "invalid_payload", parsed.error.issues[0]?.message ?? "Invalid payload");
    return;
  }

  const {
    interests, travelStyle, destination, tripDates,
    conversationContext, recipientName, defaultLanguage, count,
  } = parsed.data;

  const systemPrompt = `You are Telegraph, the smart activity recommendation layer inside Travel Buddy — a social travel companion app.
Your job: generate specific, practical, engaging activity recommendations tailored to the traveler.
Rules:
- Be specific: name real types of places, real area names, real categories
- Be concise: reason in 1-2 sentences, location in a few words
- ALWAYS return valid JSON only — no markdown fences, no prose
- Return exactly an array of ${count} recommendation objects`;

  // Fetch weather context for the destination if available — fire-and-forget with graceful fallback
  let weatherBrief: string | null = null;
  if (destination) {
    try {
      const wx = await getWeatherContext(destination, tripDates?.start, tripDates?.end);
      weatherBrief = wx?.briefSummary ?? null;
    } catch { /* degrade gracefully */ }
  }

  // CompassLocationContext — enrich prompt with city-level location context.
  // Feature-flagged: only build context when `compass_location_context_enabled` is on.
  // Falls back gracefully when flag is absent, disabled, or DB is unavailable.
  let compassCtx: Awaited<ReturnType<typeof buildCompassContext>> | null = null;
  try {
    const sc = getServiceClient();
    if (sc) {
      const { data: flag } = await sc
        .from("feature_flags")
        .select("enabled")
        .eq("key", "compass_location_context_enabled")
        .maybeSingle();
      if ((flag as any)?.enabled) {
        compassCtx = await buildCompassContext(auth.client, auth.user.id);
      }
    }
  } catch { /* non-fatal — degrade to no location context */ }

  const locationLines: string[] = [];
  if (compassCtx?.currentCity) {
    locationLines.push(`- Current city: ${compassCtx.currentCity}${compassCtx.currentCountry ? `, ${compassCtx.currentCountry}` : ""}`);
  }
  if (compassCtx?.upcomingTripCity) {
    locationLines.push(`- Upcoming trip: ${compassCtx.upcomingTripCity}${compassCtx.upcomingTripCountry ? `, ${compassCtx.upcomingTripCountry}` : ""}`);
  }
  if (compassCtx?.nearbyVerifiedPlaces?.length) {
    const names = compassCtx.nearbyVerifiedPlaces.slice(0, 3).map((p) => p.name).join(", ");
    locationLines.push(`- Nearby verified places: ${names}`);
  }

  // Followed hashtags context — enrich recommendations with the user's interest tags.
  // Non-fatal: a failure falls back to no hashtag context.
  let followedHashtagSlugs: string[] = [];
  try {
    const sc = getServiceClient();
    if (sc) {
      const { data: followRows } = await sc
        .from("user_hashtag_follows")
        .select("hashtags(slug)")
        .eq("user_id", auth.user.id)
        .limit(15);
      followedHashtagSlugs = ((followRows ?? []) as any[])
        .map((r: any) => r.hashtags?.slug)
        .filter(Boolean) as string[];
    }
  } catch { /* non-fatal */ }

  const userPrompt = `Generate ${count} activity recommendations.

Traveler context:
- Destination: ${destination ?? compassCtx?.currentCity ?? "current location"}
- Interests: ${interests?.join(", ") ?? "general travel"}
- Travel style: ${travelStyle ?? "explorer"}
- Preferred language: ${defaultLanguage ?? "en"}
${tripDates ? `- Trip: ${tripDates.start} → ${tripDates.end}` : ""}
${followedHashtagSlugs.length > 0 ? `- Followed hashtags: ${followedHashtagSlugs.map((s) => `#${s}`).join(", ")}` : ""}
${locationLines.length > 0 ? `\nLocation context (city-level only, no exact coords):\n${locationLines.join("\n")}` : ""}
${weatherBrief ? `- Weather forecast: ${weatherBrief}` : ""}
${conversationContext ? `- Chat context: "${conversationContext}"` : ""}
${recipientName ? `- Chatting with: ${recipientName}` : ""}

${weatherBrief ? "Important: factor in the weather forecast when writing 'reason' fields — mention indoor alternatives if rain is expected, or highlight outdoor activities if the weather is clear.\n\n" : ""}Return a JSON array of exactly ${count} objects, each with this exact shape (no extra keys):
{
  "id": "rec_<short_unique_id>",
  "title": "Activity name (max 60 chars)",
  "category": "food" | "nightlife" | "beach" | "activity" | "hotel" | "transport" | "tip",
  "reason": "Why this fits this traveler (max 100 chars)",
  "locationContext": "e.g. '1.2 km from Ayala Mall' (max 60 chars)",
  "estimatedTime": "e.g. '2–3 hours' or 'Full evening'",
  "priceLevel": "free" | "$" | "$$" | "$$$" | "$$$$",
  "imageUrl": null
}`;

  try {
    const completion = await openai.chat.completions.create({
      model: "gpt-5-mini",
      max_completion_tokens: 1024,
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: userPrompt },
      ],
    });

    const raw = (completion.choices[0]?.message?.content ?? "[]").trim();

    let parsed: unknown;
    try {
      parsed = JSON.parse(raw);
    } catch {
      req.log.error({ raw }, "Telegraph: AI response not valid JSON");
      sendError(res, "db_error", "Recommendation engine returned invalid response");
      return;
    }

    const arr = Array.isArray(parsed) ? parsed : [];
    const recommendations = arr.slice(0, count).map(sanitizeRec);

    // ── Compass hashtag span enrichment ──────────────────────────────────────
    // Scan each recommendation's reason/title text for #slug patterns produced
    // by the AI (e.g. when the user follows #foodie and the AI echoes it back).
    // Resolve slugs → hashtag IDs and blocked status so the mobile client can
    // render them as tappable links via RichText.hashtagUsages.
    let enrichedRecommendations: typeof recommendations = recommendations;
    try {
      const sc = getServiceClient();
      if (sc && recommendations.length > 0) {
        // Collect all unique slugs across all reason + title fields
        const allSlugs = new Set<string>();
        for (const r of recommendations) {
          const text = `${r.reason ?? ""} ${r.title ?? ""}`;
          for (const m of text.matchAll(/#([a-z0-9_]+)/gi)) {
            allSlugs.add(m[1].toLowerCase());
          }
        }

        const slugMetaMap: Record<string, { id: string; isBlocked: boolean }> = {};
        if (allSlugs.size > 0) {
          const { data: htRows } = await sc
            .from("hashtags")
            .select("id, slug, is_blocked")
            .in("slug", [...allSlugs]);
          for (const h of (htRows ?? []) as any[]) {
            if (h.slug) slugMetaMap[h.slug.toLowerCase()] = { id: h.id, isBlocked: !!h.is_blocked };
          }
        }

        // Compute positioned spans for each recommendation's reason text,
        // skipping permission check for AI-generated content (no real tagger).
        enrichedRecommendations = recommendations.map((r) => {
          const reasonText = r.reason ?? "";
          const reasonSpans: SpanHashtag[] = [];
          for (const m of reasonText.matchAll(/#([a-z0-9_]+)/gi)) {
            const slug = m[1].toLowerCase();
            const meta = slugMetaMap[slug];
            if (meta) {
              reasonSpans.push({
                slug,
                hashtagId: meta.id,
                startChar: m.index!,
                endChar: m.index! + m[0].length,
                ...(meta.isBlocked ? { isBlocked: true as const } : {}),
              });
            }
          }
          return reasonSpans.length > 0 ? { ...r, hashtagSpans: reasonSpans } : r;
        });
      }
    } catch { /* non-fatal — degrade to undecorated recommendations */ }

    res.status(200).json({ recommendations: enrichedRecommendations });
  } catch (err) {
    req.log.error({ err }, "Telegraph recommend: OpenAI call failed");
    sendError(res, "db_error", "Telegraph recommendation service unavailable");
  }
});

export default router;
