/**
 * Telegraph — AI activity recommendation engine.
 *
 * POST /api/telegraph/recommend
 *   Reads the caller's travel profile context and returns structured
 *   activity recommendations generated by GPT. Each recommendation
 *   carries a reason, location context, time estimate, and price level
 *   so the mobile client can render a rich TelegraphCard.
 *
 * Security: requireUser — anon callers rejected.
 */
import { Router } from "express";
import { z } from "zod";
import { requireUser, sendError } from "../lib/http";
import { openai } from "../lib/openai";
import { getWeatherContext } from "../lib/weatherCache.js";
import { buildCompassContext } from "../services/location/CompassLocationContext";

const router = Router();

const recommendSchema = z.object({
  interests: z.array(z.string()).max(15).optional(),
  travelStyle: z.string().max(50).optional(),
  destination: z.string().max(100).optional(),
  tripDates: z
    .object({ start: z.string(), end: z.string() })
    .optional(),
  conversationContext: z.string().max(600).optional(),
  recipientName: z.string().max(100).optional(),
  defaultLanguage: z.string().max(10).optional(),
  count: z.number().int().min(1).max(5).default(3),
});

const VALID_CATEGORIES = new Set([
  "hotel", "food", "nightlife", "beach", "activity",
  "transport", "safety", "tip", "question",
]);
const VALID_PRICES = new Set(["free", "$", "$$", "$$$", "$$$$"]);

function sanitizeRec(r: any, idx: number) {
  return {
    id: typeof r.id === "string" ? r.id : `rec_${Date.now()}_${idx}`,
    title: typeof r.title === "string" ? r.title.slice(0, 120) : "Activity",
    category: VALID_CATEGORIES.has(r.category) ? r.category : "activity",
    reason: typeof r.reason === "string" ? r.reason.slice(0, 300) : "",
    locationContext: typeof r.locationContext === "string" ? r.locationContext.slice(0, 150) : "",
    estimatedTime: typeof r.estimatedTime === "string" ? r.estimatedTime.slice(0, 60) : "",
    priceLevel: VALID_PRICES.has(r.priceLevel) ? r.priceLevel : "$",
    imageUrl: typeof r.imageUrl === "string" ? r.imageUrl : null,
  };
}

/* ===========================================================================
 * POST /telegraph/recommend
 * ===========================================================================
 */
router.post("/telegraph/recommend", async (req, res) => {
  const auth = await requireUser(req, res);
  if (!auth) return;

  const parsed = recommendSchema.safeParse(req.body);
  if (!parsed.success) {
    sendError(res, "invalid_payload", parsed.error.issues[0]?.message ?? "Invalid payload");
    return;
  }

  const {
    interests, travelStyle, destination, tripDates,
    conversationContext, recipientName, defaultLanguage, count,
  } = parsed.data;

  const systemPrompt = `You are Telegraph, the smart activity recommendation layer inside Travel Buddy — a social travel companion app.
Your job: generate specific, practical, engaging activity recommendations tailored to the traveler.
Rules:
- Be specific: name real types of places, real area names, real categories
- Be concise: reason in 1-2 sentences, location in a few words
- ALWAYS return valid JSON only — no markdown fences, no prose
- Return exactly an array of ${count} recommendation objects`;

  // Fetch weather context for the destination if available — fire-and-forget with graceful fallback
  let weatherBrief: string | null = null;
  if (destination) {
    try {
      const wx = await getWeatherContext(destination, tripDates?.start, tripDates?.end);
      weatherBrief = wx?.briefSummary ?? null;
    } catch { /* degrade gracefully */ }
  }

  // CompassLocationContext — enrich prompt with city-level location context.
  // Gated: only inject when user has location data; falls back gracefully.
  let compassCtx: Awaited<ReturnType<typeof buildCompassContext>> | null = null;
  try {
    compassCtx = await buildCompassContext(auth.client, auth.user.id);
  } catch { /* non-fatal */ }

  const locationLines: string[] = [];
  if (compassCtx?.currentCity) {
    locationLines.push(`- Current city: ${compassCtx.currentCity}${compassCtx.currentCountry ? `, ${compassCtx.currentCountry}` : ""}`);
  }
  if (compassCtx?.upcomingTripCity) {
    locationLines.push(`- Upcoming trip: ${compassCtx.upcomingTripCity}${compassCtx.upcomingTripCountry ? `, ${compassCtx.upcomingTripCountry}` : ""}`);
  }
  if (compassCtx?.nearbyVerifiedPlaces?.length) {
    const names = compassCtx.nearbyVerifiedPlaces.slice(0, 3).map((p) => p.name).join(", ");
    locationLines.push(`- Nearby verified places: ${names}`);
  }

  const userPrompt = `Generate ${count} activity recommendations.

Traveler context:
- Destination: ${destination ?? compassCtx?.currentCity ?? "current location"}
- Interests: ${interests?.join(", ") ?? "general travel"}
- Travel style: ${travelStyle ?? "explorer"}
- Preferred language: ${defaultLanguage ?? "en"}
${tripDates ? `- Trip: ${tripDates.start} → ${tripDates.end}` : ""}
${locationLines.length > 0 ? `\nLocation context (city-level only, no exact coords):\n${locationLines.join("\n")}` : ""}
${weatherBrief ? `- Weather forecast: ${weatherBrief}` : ""}
${conversationContext ? `- Chat context: "${conversationContext}"` : ""}
${recipientName ? `- Chatting with: ${recipientName}` : ""}

${weatherBrief ? "Important: factor in the weather forecast when writing 'reason' fields — mention indoor alternatives if rain is expected, or highlight outdoor activities if the weather is clear.\n\n" : ""}Return a JSON array of exactly ${count} objects, each with this exact shape (no extra keys):
{
  "id": "rec_<short_unique_id>",
  "title": "Activity name (max 60 chars)",
  "category": "food" | "nightlife" | "beach" | "activity" | "hotel" | "transport" | "tip",
  "reason": "Why this fits this traveler (max 100 chars)",
  "locationContext": "e.g. '1.2 km from Ayala Mall' (max 60 chars)",
  "estimatedTime": "e.g. '2–3 hours' or 'Full evening'",
  "priceLevel": "free" | "$" | "$$" | "$$$" | "$$$$",
  "imageUrl": null
}`;

  try {
    const completion = await openai.chat.completions.create({
      model: "gpt-5-mini",
      max_completion_tokens: 1024,
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: userPrompt },
      ],
    });

    const raw = (completion.choices[0]?.message?.content ?? "[]").trim();

    let parsed: unknown;
    try {
      parsed = JSON.parse(raw);
    } catch {
      req.log.error({ raw }, "Telegraph: AI response not valid JSON");
      sendError(res, "db_error", "Recommendation engine returned invalid response");
      return;
    }

    const arr = Array.isArray(parsed) ? parsed : [];
    const recommendations = arr.slice(0, count).map(sanitizeRec);

    res.status(200).json({ recommendations });
  } catch (err) {
    req.log.error({ err }, "Telegraph recommend: OpenAI call failed");
    sendError(res, "db_error", "Telegraph recommendation service unavailable");
  }
});

export default router;
