/**
 * Telegraph — AI activity recommendation engine.
 *
 * POST /api/telegraph/recommend
 *   Reads the caller's travel profile context and returns structured
 *   activity recommendations generated by GPT. Each recommendation
 *   carries a reason, location context, time estimate, and price level
 *   so the mobile client can render a rich TelegraphCard.
 *
 * Security: requireUser — anon callers rejected.
 */
import { Router } from "express";
import { z } from "zod";
import { requireUser, sendError } from "../lib/http";
import { getServiceClient } from "../lib/supabase";
import { openai } from "../lib/openai";
import { getWeatherContext } from "../lib/weatherCache.js";
import { buildCompassContext } from "../services/location/CompassLocationContext";
import type { SpanHashtag, SpanTag } from "../lib/enrichSpans";
import { makeConfidence } from "../lib/liveIntelligence.js";

const router = Router();

const recommendSchema = z.object({
  interests: z.array(z.string()).max(15).optional(),
  travelStyle: z.string().max(50).optional(),
  destination: z.string().max(100).optional(),
  tripDates: z
    .object({ start: z.string(), end: z.string() })
    .optional(),
  conversationContext: z.string().max(600).optional(),
  recipientName: z.string().max(100).optional(),
  defaultLanguage: z.string().max(10).optional(),
  count: z.number().int().min(1).max(5).default(3),
});

const VALID_CATEGORIES = new Set([
  "hotel", "food", "nightlife", "beach", "activity",
  "transport", "safety", "tip", "question",
]);
const VALID_PRICES = new Set(["free", "$", "$$", "$$$", "$$$$"]);

function sanitizeRec(r: any, idx: number) {
  return {
    id: typeof r.id === "string" ? r.id : `rec_${Date.now()}_${idx}`,
    title: typeof r.title === "string" ? r.title.slice(0, 120) : "Activity",
    category: VALID_CATEGORIES.has(r.category) ? r.category : "activity",
    reason: typeof r.reason === "string" ? r.reason.slice(0, 300) : "",
    locationContext: typeof r.locationContext === "string" ? r.locationContext.slice(0, 150) : "",
    estimatedTime: typeof r.estimatedTime === "string" ? r.estimatedTime.slice(0, 60) : "",
    priceLevel: VALID_PRICES.has(r.priceLevel) ? r.priceLevel : "$",
    imageUrl: typeof r.imageUrl === "string" ? r.imageUrl : null,
    // Phase 8 — Telegraph recommendations are model-generated, not verified
    // against a live source: label them honestly as AI inference.
    confidence: makeConfidence("ai_inference"),
  };
}

/* ===========================================================================
 * POST /telegraph/recommend
 * ===========================================================================
 */
router.post("/telegraph/recommend", async (req, res) => {
  const auth = await requireUser(req, res);
  if (!auth) return;

  const parsed = recommendSchema.safeParse(req.body);
  if (!parsed.success) {
    sendError(res, "invalid_payload", parsed.error.issues[0]?.message ?? "Invalid payload");
    return;
  }

  const {
    interests, travelStyle, destination, tripDates,
    conversationContext, recipientName, defaultLanguage, count,
  } = parsed.data;

  const systemPrompt = `You are Telegraph, the smart activity recommendation layer inside Portava — a social travel companion app.
Your job: generate specific, practical, engaging activity recommendations tailored to the traveler.
Rules:
- Be specific: name real types of places, real area names, real categories
- Be concise: reason in 1-2 sentences, location in a few words
- ALWAYS return valid JSON only — no markdown fences, no prose
- Return exactly an array of ${count} recommendation objects`;

  // Fetch weather context for the destination if available — fire-and-forget with graceful fallback
  let weatherBrief: string | null = null;
  if (destination) {
    try {
      const wx = await getWeatherContext(destination, tripDates?.start, tripDates?.end);
      weatherBrief = wx?.briefSummary ?? null;
    } catch { /* degrade gracefully */ }
  }

  // CompassLocationContext — enrich prompt with city-level location context.
  // Feature-flagged: only build context when `compass_location_context_enabled` is on.
  // Falls back gracefully when flag is absent, disabled, or DB is unavailable.
  let compassCtx: Awaited<ReturnType<typeof buildCompassContext>> | null = null;
  try {
    const sc = getServiceClient();
    if (sc) {
      const { data: flag } = await sc
        .from("feature_flags")
        .select("enabled")
        .eq("flag", "compass_location_context_enabled")
        .maybeSingle();
      if ((flag as any)?.enabled) {
        compassCtx = await buildCompassContext(auth.client, auth.user.id);
      }
    }
  } catch { /* non-fatal — degrade to no location context */ }

  const locationLines: string[] = [];
  if (compassCtx?.currentCity) {
    locationLines.push(`- Current city: ${compassCtx.currentCity}${compassCtx.currentCountry ? `, ${compassCtx.currentCountry}` : ""}`);
  }
  if (compassCtx?.upcomingTripCity) {
    locationLines.push(`- Upcoming trip: ${compassCtx.upcomingTripCity}${compassCtx.upcomingTripCountry ? `, ${compassCtx.upcomingTripCountry}` : ""}`);
  }
  if (compassCtx?.nearbyVerifiedPlaces?.length) {
    const names = compassCtx.nearbyVerifiedPlaces.slice(0, 3).map((p) => p.name).join(", ");
    locationLines.push(`- Nearby verified places: ${names}`);
  }

  // Followed hashtags context — enrich recommendations with the user's interest tags.
  // Non-fatal: a failure falls back to no hashtag context.
  let followedHashtagSlugs: string[] = [];
  try {
    const sc = getServiceClient();
    if (sc) {
      const { data: followRows } = await sc
        .from("user_hashtag_follows")
        .select("hashtags(slug)")
        .eq("user_id", auth.user.id)
        .limit(15);
      followedHashtagSlugs = ((followRows ?? []) as any[])
        .map((r: any) => r.hashtags?.slug)
        .filter(Boolean) as string[];
    }
  } catch { /* non-fatal */ }

  const userPrompt = `Generate ${count} activity recommendations.

Traveler context:
- Destination: ${destination ?? compassCtx?.currentCity ?? "current location"}
- Interests: ${interests?.join(", ") ?? "general travel"}
- Travel style: ${travelStyle ?? "explorer"}
- Preferred language: ${defaultLanguage ?? "en"}
${tripDates ? `- Trip: ${tripDates.start} → ${tripDates.end}` : ""}
${followedHashtagSlugs.length > 0 ? `- Followed hashtags: ${followedHashtagSlugs.map((s) => `#${s}`).join(", ")}` : ""}
${locationLines.length > 0 ? `\nLocation context (city-level only, no exact coords):\n${locationLines.join("\n")}` : ""}
${weatherBrief ? `- Weather forecast: ${weatherBrief}` : ""}
${conversationContext ? `- Chat context: "${conversationContext}"` : ""}
${recipientName ? `- Chatting with: ${recipientName}` : ""}

${weatherBrief ? "Important: factor in the weather forecast when writing 'reason' fields — mention indoor alternatives if rain is expected, or highlight outdoor activities if the weather is clear.\n\n" : ""}Return a JSON array of exactly ${count} objects, each with this exact shape (no extra keys):
{
  "id": "rec_<short_unique_id>",
  "title": "Activity name (max 60 chars)",
  "category": "food" | "nightlife" | "beach" | "activity" | "hotel" | "transport" | "tip",
  "reason": "Why this fits this traveler (max 100 chars)",
  "locationContext": "e.g. '1.2 km from Ayala Mall' (max 60 chars)",
  "estimatedTime": "e.g. '2–3 hours' or 'Full evening'",
  "priceLevel": "free" | "$" | "$$" | "$$$" | "$$$$",
  "imageUrl": null
}`;

  try {
    const completion = await openai.chat.completions.create({
      model: "gpt-5-mini",
      max_completion_tokens: 1024,
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: userPrompt },
      ],
    });

    const raw = (completion.choices[0]?.message?.content ?? "[]").trim();

    let parsed: unknown;
    try {
      parsed = JSON.parse(raw);
    } catch {
      req.log.error({ raw }, "Telegraph: AI response not valid JSON");
      sendError(res, "db_error", "Recommendation engine returned invalid response", { exposeDetail: true });
      return;
    }

    const arr = Array.isArray(parsed) ? parsed : [];
    const recommendations = arr.slice(0, count).map(sanitizeRec);

    // ── Compass span enrichment ───────────────────────────────────────────────
    // Scan each recommendation's reason text for #slug and @handle patterns.
    // #hashtags  → resolved against `hashtags` table; is_blocked suppresses link.
    // @mentions  → resolved against `profiles`; tag_permission + blocks + follows
    //              are enforced using the same rules as the tag-suggestions endpoint.
    //              Handles that fail the permission check are excluded entirely so
    //              a user with tag_permission='nobody' never appears in AI output.
    let enrichedRecommendations: typeof recommendations = recommendations;
    try {
      const sc = getServiceClient();
      if (sc && recommendations.length > 0) {
        // ── 1. Collect unique tokens ─────────────────────────────────────────
        const allSlugs  = new Set<string>();
        const allHandles = new Set<string>();
        for (const r of recommendations) {
          const text = r.reason ?? "";
          for (const m of text.matchAll(/#([a-z0-9_]+)/gi))  allSlugs.add(m[1].toLowerCase());
          for (const m of text.matchAll(/@([a-z0-9_]+)/gi)) allHandles.add(m[1].toLowerCase());
        }

        // ── 2. Resolve hashtags ──────────────────────────────────────────────
        const slugMetaMap: Record<string, { id: string; isBlocked: boolean }> = {};
        if (allSlugs.size > 0) {
          const { data: htRows } = await sc
            .from("hashtags")
            .select("id, slug, is_blocked")
            .in("slug", [...allSlugs]);
          for (const h of (htRows ?? []) as any[]) {
            if (h.slug) slugMetaMap[h.slug.toLowerCase()] = { id: h.id, isBlocked: !!h.is_blocked };
          }
        }

        // ── 3. Resolve @handles with permission enforcement ──────────────────
        // Mirrors the tag_permission checks in GET /api/tags/suggestions.
        const allowedMentionMap: Record<string, { userId: string; handle: string }> = {};
        if (allHandles.size > 0) {
          const { data: profiles } = await sc
            .from("profiles")
            .select("id, handle, tag_permission")
            .in("handle", [...allHandles]);

          const profileIds: string[] = ((profiles ?? []) as any[]).map((p: any) => p.id as string);

          // Block check (both directions)
          const blockedSet = new Set<string>();
          if (profileIds.length > 0) {
            const ids = profileIds.join(",");
            const { data: blockRows, error: blockErr } = await sc
              .from("blocks")
              .select("blocker_id, blocked_id")
              .or(
                `and(blocker_id.eq.${auth.user.id},blocked_id.in.(${ids})),` +
                `and(blocked_id.eq.${auth.user.id},blocker_id.in.(${ids}))`,
              );
            // An empty result means "none of these profiles is blocked"; a
            // rejected one (a malformed or() filter is the usual cause here,
            // since this predicate is string-built) means "we did not check".
            // Both leave blockedSet empty and both let blocked users through.
            if (blockErr) {
              req.log?.warn(
                { userId: auth.user.id, code: (blockErr as any)?.code, err: blockErr },
                "telegraph: block-state read failed — blocked users are NOT being filtered from suggestions",
              );
            }
            for (const row of (blockRows ?? []) as any[]) {
              blockedSet.add(
                row.blocker_id === auth.user.id ? row.blocked_id : row.blocker_id,
              );
            }

            // Follow sets for friends_only / interacted checks
            const { data: followRows } = await sc
              .from("user_follows")
              .select("follower_id, following_id")
              .or(
                `and(follower_id.eq.${auth.user.id},following_id.in.(${ids})),` +
                `and(following_id.eq.${auth.user.id},follower_id.in.(${ids}))`,
              );
            const iFollow   = new Set<string>();
            const followsMe = new Set<string>();
            for (const row of (followRows ?? []) as any[]) {
              if (row.follower_id === auth.user.id) iFollow.add(row.following_id);
              else followsMe.add(row.follower_id);
            }

            for (const p of (profiles ?? []) as any[]) {
              if (!p.handle) continue;
              const uid  = p.id as string;
              const perm = (p.tag_permission ?? "anyone") as string;
              if (blockedSet.has(uid))   continue; // blocked — exclude
              if (perm === "nobody")     continue; // user opted out entirely
              if (perm === "friends_only" && !(iFollow.has(uid) && followsMe.has(uid))) continue;
              if (perm === "interacted"   && !(iFollow.has(uid) || followsMe.has(uid))) continue;
              allowedMentionMap[(p.handle as string).toLowerCase()] = { userId: uid, handle: p.handle as string };
            }
          }
        }

        // ── 4. Compute positioned spans per recommendation ───────────────────
        enrichedRecommendations = recommendations.map((r) => {
          const reasonText = r.reason ?? "";
          const hashtagSpans: SpanHashtag[] = [];
          const tagSpans: SpanTag[] = [];

          for (const m of reasonText.matchAll(/#([a-z0-9_]+)/gi)) {
            const slug = m[1].toLowerCase();
            const meta = slugMetaMap[slug];
            if (meta) {
              hashtagSpans.push({
                slug,
                hashtagId: meta.id,
                startChar: m.index!,
                endChar: m.index! + m[0].length,
                ...(meta.isBlocked ? { isBlocked: true as const } : {}),
              });
            }
          }

          for (const m of reasonText.matchAll(/@([a-z0-9_]+)/gi)) {
            const handle = m[1].toLowerCase();
            const meta = allowedMentionMap[handle];
            if (meta) {
              tagSpans.push({
                type: "user",
                id: meta.userId,
                matchToken: meta.handle,
                startChar: m.index!,
                endChar: m.index! + m[0].length,
              });
            }
          }

          const extras: Record<string, unknown> = {};
          if (hashtagSpans.length > 0) extras.hashtagSpans = hashtagSpans;
          if (tagSpans.length > 0)     extras.tagSpans     = tagSpans;
          return Object.keys(extras).length > 0 ? { ...r, ...extras } : r;
        });
      }
    } catch { /* non-fatal — degrade to undecorated recommendations */ }

    res.status(200).json({ recommendations: enrichedRecommendations });
  } catch (err) {
    req.log.error({ err }, "Telegraph recommend: OpenAI call failed");
    sendError(res, "db_error", "Telegraph recommendation service unavailable", { exposeDetail: true });
  }
});

export default router;
