"use strict";
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
var __generator = (this && this.__generator) || function (thisArg, body) {
    var _ = { label: 0, sent: function() { if (t[0] & 1) throw t[1]; return t[1]; }, trys: [], ops: [] }, f, y, t, g = Object.create((typeof Iterator === "function" ? Iterator : Object).prototype);
    return g.next = verb(0), g["throw"] = verb(1), g["return"] = verb(2), typeof Symbol === "function" && (g[Symbol.iterator] = function() { return this; }), g;
    function verb(n) { return function (v) { return step([n, v]); }; }
    function step(op) {
        if (f) throw new TypeError("Generator is already executing.");
        while (g && (g = 0, op[0] && (_ = 0)), _) try {
            if (f = 1, y && (t = op[0] & 2 ? y["return"] : op[0] ? y["throw"] || ((t = y["return"]) && t.call(y), 0) : y.next) && !(t = t.call(y, op[1])).done) return t;
            if (y = 0, t) op = [op[0] & 2, t.value];
            switch (op[0]) {
                case 0: case 1: t = op; break;
                case 4: _.label++; return { value: op[1], done: false };
                case 5: _.label++; y = op[1]; op = [0]; continue;
                case 7: op = _.ops.pop(); _.trys.pop(); continue;
                default:
                    if (!(t = _.trys, t = t.length > 0 && t[t.length - 1]) && (op[0] === 6 || op[0] === 2)) { _ = 0; continue; }
                    if (op[0] === 3 && (!t || (op[1] > t[0] && op[1] < t[3]))) { _.label = op[1]; break; }
                    if (op[0] === 6 && _.label < t[1]) { _.label = t[1]; t = op; break; }
                    if (t && _.label < t[2]) { _.label = t[2]; _.ops.push(op); break; }
                    if (t[2]) _.ops.pop();
                    _.trys.pop(); continue;
            }
            op = body.call(thisArg, _);
        } catch (e) { op = [6, e]; y = 0; } finally { f = t = 0; }
        if (op[0] & 5) throw op[1]; return { value: op[0] ? op[1] : void 0, done: true };
    }
};
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * Telegraph — AI activity recommendation engine.
 *
 * POST /api/telegraph/recommend
 *   Reads the caller's travel profile context and returns structured
 *   activity recommendations generated by GPT. Each recommendation
 *   carries a reason, location context, time estimate, and price level
 *   so the mobile client can render a rich TelegraphCard.
 *
 * Security: requireUser — anon callers rejected.
 */
var express_1 = require("express");
var zod_1 = require("zod");
var http_1 = require("../lib/http");
var supabase_1 = require("../lib/supabase");
var openai_1 = require("../lib/openai");
var weatherCache_js_1 = require("../lib/weatherCache.js");
var CompassLocationContext_1 = require("../services/location/CompassLocationContext");
var router = (0, express_1.Router)();
var recommendSchema = zod_1.z.object({
    interests: zod_1.z.array(zod_1.z.string()).max(15).optional(),
    travelStyle: zod_1.z.string().max(50).optional(),
    destination: zod_1.z.string().max(100).optional(),
    tripDates: zod_1.z
        .object({ start: zod_1.z.string(), end: zod_1.z.string() })
        .optional(),
    conversationContext: zod_1.z.string().max(600).optional(),
    recipientName: zod_1.z.string().max(100).optional(),
    defaultLanguage: zod_1.z.string().max(10).optional(),
    count: zod_1.z.number().int().min(1).max(5).default(3),
});
var VALID_CATEGORIES = new Set([
    "hotel", "food", "nightlife", "beach", "activity",
    "transport", "safety", "tip", "question",
]);
var VALID_PRICES = new Set(["free", "$", "$$", "$$$", "$$$$"]);
function sanitizeRec(r, idx) {
    return {
        id: typeof r.id === "string" ? r.id : "rec_".concat(Date.now(), "_").concat(idx),
        title: typeof r.title === "string" ? r.title.slice(0, 120) : "Activity",
        category: VALID_CATEGORIES.has(r.category) ? r.category : "activity",
        reason: typeof r.reason === "string" ? r.reason.slice(0, 300) : "",
        locationContext: typeof r.locationContext === "string" ? r.locationContext.slice(0, 150) : "",
        estimatedTime: typeof r.estimatedTime === "string" ? r.estimatedTime.slice(0, 60) : "",
        priceLevel: VALID_PRICES.has(r.priceLevel) ? r.priceLevel : "$",
        imageUrl: typeof r.imageUrl === "string" ? r.imageUrl : null,
    };
}
/* ===========================================================================
 * POST /telegraph/recommend
 * ===========================================================================
 */
router.post("/telegraph/recommend", function (req, res) { return __awaiter(void 0, void 0, void 0, function () {
    var auth, parsed, _a, interests, travelStyle, destination, tripDates, conversationContext, recipientName, defaultLanguage, count, systemPrompt, weatherBrief, wx, _b, compassCtx, sc, flag, _c, locationLines, names, userPrompt, completion, raw, parsed_1, arr, recommendations, err_1;
    var _d, _e, _f, _g, _h, _j, _k, _l, _m;
    return __generator(this, function (_o) {
        switch (_o.label) {
            case 0: return [4 /*yield*/, (0, http_1.requireUser)(req, res)];
            case 1:
                auth = _o.sent();
                if (!auth)
                    return [2 /*return*/];
                parsed = recommendSchema.safeParse(req.body);
                if (!parsed.success) {
                    (0, http_1.sendError)(res, "invalid_payload", (_e = (_d = parsed.error.issues[0]) === null || _d === void 0 ? void 0 : _d.message) !== null && _e !== void 0 ? _e : "Invalid payload");
                    return [2 /*return*/];
                }
                _a = parsed.data, interests = _a.interests, travelStyle = _a.travelStyle, destination = _a.destination, tripDates = _a.tripDates, conversationContext = _a.conversationContext, recipientName = _a.recipientName, defaultLanguage = _a.defaultLanguage, count = _a.count;
                systemPrompt = "You are Telegraph, the smart activity recommendation layer inside Travel Buddy \u2014 a social travel companion app.\nYour job: generate specific, practical, engaging activity recommendations tailored to the traveler.\nRules:\n- Be specific: name real types of places, real area names, real categories\n- Be concise: reason in 1-2 sentences, location in a few words\n- ALWAYS return valid JSON only \u2014 no markdown fences, no prose\n- Return exactly an array of ".concat(count, " recommendation objects");
                weatherBrief = null;
                if (!destination) return [3 /*break*/, 5];
                _o.label = 2;
            case 2:
                _o.trys.push([2, 4, , 5]);
                return [4 /*yield*/, (0, weatherCache_js_1.getWeatherContext)(destination, tripDates === null || tripDates === void 0 ? void 0 : tripDates.start, tripDates === null || tripDates === void 0 ? void 0 : tripDates.end)];
            case 3:
                wx = _o.sent();
                weatherBrief = (_f = wx === null || wx === void 0 ? void 0 : wx.briefSummary) !== null && _f !== void 0 ? _f : null;
                return [3 /*break*/, 5];
            case 4:
                _b = _o.sent();
                return [3 /*break*/, 5];
            case 5:
                compassCtx = null;
                _o.label = 6;
            case 6:
                _o.trys.push([6, 10, , 11]);
                sc = (0, supabase_1.getServiceClient)();
                if (!sc) return [3 /*break*/, 9];
                return [4 /*yield*/, sc
                        .from("feature_flags")
                        .select("enabled")
                        .eq("key", "compass_location_context_enabled")
                        .maybeSingle()];
            case 7:
                flag = (_o.sent()).data;
                if (!(flag === null || flag === void 0 ? void 0 : flag.enabled)) return [3 /*break*/, 9];
                return [4 /*yield*/, (0, CompassLocationContext_1.buildCompassContext)(auth.client, auth.user.id)];
            case 8:
                compassCtx = _o.sent();
                _o.label = 9;
            case 9: return [3 /*break*/, 11];
            case 10:
                _c = _o.sent();
                return [3 /*break*/, 11];
            case 11:
                locationLines = [];
                if (compassCtx === null || compassCtx === void 0 ? void 0 : compassCtx.currentCity) {
                    locationLines.push("- Current city: ".concat(compassCtx.currentCity).concat(compassCtx.currentCountry ? ", ".concat(compassCtx.currentCountry) : ""));
                }
                if (compassCtx === null || compassCtx === void 0 ? void 0 : compassCtx.upcomingTripCity) {
                    locationLines.push("- Upcoming trip: ".concat(compassCtx.upcomingTripCity).concat(compassCtx.upcomingTripCountry ? ", ".concat(compassCtx.upcomingTripCountry) : ""));
                }
                if ((_g = compassCtx === null || compassCtx === void 0 ? void 0 : compassCtx.nearbyVerifiedPlaces) === null || _g === void 0 ? void 0 : _g.length) {
                    names = compassCtx.nearbyVerifiedPlaces.slice(0, 3).map(function (p) { return p.name; }).join(", ");
                    locationLines.push("- Nearby verified places: ".concat(names));
                }
                userPrompt = "Generate ".concat(count, " activity recommendations.\n\nTraveler context:\n- Destination: ").concat((_h = destination !== null && destination !== void 0 ? destination : compassCtx === null || compassCtx === void 0 ? void 0 : compassCtx.currentCity) !== null && _h !== void 0 ? _h : "current location", "\n- Interests: ").concat((_j = interests === null || interests === void 0 ? void 0 : interests.join(", ")) !== null && _j !== void 0 ? _j : "general travel", "\n- Travel style: ").concat(travelStyle !== null && travelStyle !== void 0 ? travelStyle : "explorer", "\n- Preferred language: ").concat(defaultLanguage !== null && defaultLanguage !== void 0 ? defaultLanguage : "en", "\n").concat(tripDates ? "- Trip: ".concat(tripDates.start, " \u2192 ").concat(tripDates.end) : "", "\n").concat(locationLines.length > 0 ? "\nLocation context (city-level only, no exact coords):\n".concat(locationLines.join("\n")) : "", "\n").concat(weatherBrief ? "- Weather forecast: ".concat(weatherBrief) : "", "\n").concat(conversationContext ? "- Chat context: \"".concat(conversationContext, "\"") : "", "\n").concat(recipientName ? "- Chatting with: ".concat(recipientName) : "", "\n\n").concat(weatherBrief ? "Important: factor in the weather forecast when writing 'reason' fields — mention indoor alternatives if rain is expected, or highlight outdoor activities if the weather is clear.\n\n" : "", "Return a JSON array of exactly ").concat(count, " objects, each with this exact shape (no extra keys):\n{\n  \"id\": \"rec_<short_unique_id>\",\n  \"title\": \"Activity name (max 60 chars)\",\n  \"category\": \"food\" | \"nightlife\" | \"beach\" | \"activity\" | \"hotel\" | \"transport\" | \"tip\",\n  \"reason\": \"Why this fits this traveler (max 100 chars)\",\n  \"locationContext\": \"e.g. '1.2 km from Ayala Mall' (max 60 chars)\",\n  \"estimatedTime\": \"e.g. '2\u20133 hours' or 'Full evening'\",\n  \"priceLevel\": \"free\" | \"$\" | \"$$\" | \"$$$\" | \"$$$$\",\n  \"imageUrl\": null\n}");
                _o.label = 12;
            case 12:
                _o.trys.push([12, 14, , 15]);
                return [4 /*yield*/, openai_1.openai.chat.completions.create({
                        model: "gpt-5-mini",
                        max_completion_tokens: 1024,
                        messages: [
                            { role: "system", content: systemPrompt },
                            { role: "user", content: userPrompt },
                        ],
                    })];
            case 13:
                completion = _o.sent();
                raw = ((_m = (_l = (_k = completion.choices[0]) === null || _k === void 0 ? void 0 : _k.message) === null || _l === void 0 ? void 0 : _l.content) !== null && _m !== void 0 ? _m : "[]").trim();
                try {
                    parsed_1 = JSON.parse(raw);
                }
                catch (_p) {
                    req.log.error({ raw: raw }, "Telegraph: AI response not valid JSON");
                    (0, http_1.sendError)(res, "db_error", "Recommendation engine returned invalid response");
                    return [2 /*return*/];
                }
                arr = Array.isArray(parsed_1) ? parsed_1 : [];
                recommendations = arr.slice(0, count).map(sanitizeRec);
                res.status(200).json({ recommendations: recommendations });
                return [3 /*break*/, 15];
            case 14:
                err_1 = _o.sent();
                req.log.error({ err: err_1 }, "Telegraph recommend: OpenAI call failed");
                (0, http_1.sendError)(res, "db_error", "Telegraph recommendation service unavailable");
                return [3 /*break*/, 15];
            case 15: return [2 /*return*/];
        }
    });
}); });
exports.default = router;
