/**
 * Global Input Intelligence — the InputContext registry (spec §5).
 *
 * The single source of truth for "what assistance is allowed" per context.
 * Each context carries the default behavioral shape (mode, entity types,
 * privacy, offline, capability flags, zero-state affordance). `inputPolicies.ts`
 * builds concrete per-field `InputFieldPolicy` objects from these descriptors;
 * a field may override any default when it registers.
 *
 * These defaults are derived directly from the spec's field/mode tables
 * (§ "Field | Mode | Primary assistance", §12–§14, §26, §54–§56) and the audit's
 * desired-mode column. Nothing here is wired to a screen yet (additive spine).
 */
import type {
  AssistanceType,
  EntityType,
  InputContext,
  OfflineInputPolicy,
  PrivacyClass,
} from '../types/inputContext.ts';
import type { InputAssistanceMode } from '../types/fieldPolicy.ts';

/** Canonical policy schema version returned on every projection (§41, §48). */
export const INPUT_POLICY_VERSION = 'input-2026-08';

export interface InputContextDescriptor {
  context: InputContext;
  /** Default assistance mode for fields of this context. */
  defaultMode: InputAssistanceMode;
  /** Entity classes this context resolves into (empty for pure text fields). */
  entityTypes: EntityType[];
  /** Assistance types this context may surface by default. */
  allowedSuggestionTypes: AssistanceType[];
  privacyClass: PrivacyClass;
  offlinePolicy: OfflineInputPolicy;
  allowPersonalization: boolean;
  allowLiveContext: boolean;
  allowMemoryContext: boolean;
  allowAI: boolean;
  /** §14 — does this field offer useful zero-character suggestions? */
  zeroStateAssistance: boolean;
  /** Default minimum characters before server-assisted suggestions (§33). */
  minChars: number;
}

/** Reusable default trigger sets to keep the table below readable. */
const ENTITY_PICKER_TYPES: AssistanceType[] = ['entity', 'recent', 'personalized', 'disambiguation', 'correction'];
const SEARCH_TYPES: AssistanceType[] = ['entity', 'completion', 'recent', 'personalized', 'action'];
const TEXT_ASSIST_TYPES: AssistanceType[] = ['entity', 'completion', 'ai_suggestion'];
const NONE_TYPES: AssistanceType[] = [];

/**
 * The registry. Every InputContext MUST have exactly one descriptor — the test
 * `fieldRegistry.test.ts` asserts INPUT_CONTEXTS ⊆ keys(INPUT_CONTEXT_REGISTRY).
 */
export const INPUT_CONTEXT_REGISTRY: Record<InputContext, InputContextDescriptor> = {
  global_search: {
    context: 'global_search',
    defaultMode: 'search',
    entityTypes: ['city', 'country', 'place', 'hidden_gem', 'user', 'trip', 'event', 'hashtag'],
    allowedSuggestionTypes: SEARCH_TYPES,
    privacyClass: 'public',
    offlinePolicy: 'recent_only',
    allowPersonalization: true,
    allowLiveContext: true,
    allowMemoryContext: true,
    allowAI: false,
    zeroStateAssistance: true,
    minChars: 2,
  },
  city_picker: {
    context: 'city_picker',
    defaultMode: 'canonical_picker',
    entityTypes: ['city', 'country'],
    allowedSuggestionTypes: ENTITY_PICKER_TYPES,
    privacyClass: 'public',
    offlinePolicy: 'cached_entities',
    allowPersonalization: true,
    allowLiveContext: false,
    allowMemoryContext: true,
    allowAI: false,
    zeroStateAssistance: true,
    minChars: 1,
  },
  country_picker: {
    context: 'country_picker',
    defaultMode: 'canonical_picker',
    entityTypes: ['country'],
    allowedSuggestionTypes: ENTITY_PICKER_TYPES,
    privacyClass: 'public',
    offlinePolicy: 'static_dictionary',
    allowPersonalization: false,
    allowLiveContext: false,
    allowMemoryContext: true,
    allowAI: false,
    zeroStateAssistance: true,
    minChars: 1,
  },
  neighborhood_picker: {
    context: 'neighborhood_picker',
    defaultMode: 'canonical_picker',
    entityTypes: ['neighborhood', 'city'],
    allowedSuggestionTypes: ENTITY_PICKER_TYPES,
    privacyClass: 'public',
    offlinePolicy: 'cached_entities',
    allowPersonalization: false,
    allowLiveContext: false,
    allowMemoryContext: true,
    allowAI: false,
    zeroStateAssistance: true,
    minChars: 1,
  },
  place_picker: {
    context: 'place_picker',
    defaultMode: 'canonical_picker',
    entityTypes: ['place', 'hidden_gem', 'city'],
    allowedSuggestionTypes: ENTITY_PICKER_TYPES,
    privacyClass: 'public',
    offlinePolicy: 'cached_entities',
    allowPersonalization: true,
    allowLiveContext: true,
    allowMemoryContext: true,
    allowAI: false,
    zeroStateAssistance: true,
    minChars: 1,
  },
  trip_destination: {
    context: 'trip_destination',
    defaultMode: 'canonical_picker',
    entityTypes: ['city', 'country'],
    allowedSuggestionTypes: ENTITY_PICKER_TYPES,
    privacyClass: 'public',
    offlinePolicy: 'cached_entities',
    allowPersonalization: true,
    allowLiveContext: false,
    allowMemoryContext: true,
    allowAI: false,
    zeroStateAssistance: true,
    minChars: 1,
  },
  trip_title: {
    context: 'trip_title',
    defaultMode: 'free_text_assisted',
    entityTypes: [],
    allowedSuggestionTypes: TEXT_ASSIST_TYPES,
    privacyClass: 'personal',
    offlinePolicy: 'none',
    allowPersonalization: false,
    allowLiveContext: false,
    allowMemoryContext: false,
    allowAI: true,
    zeroStateAssistance: false,
    minChars: 2,
  },
  trip_stop_place: {
    context: 'trip_stop_place',
    defaultMode: 'canonical_picker',
    entityTypes: ['place', 'city', 'neighborhood'],
    allowedSuggestionTypes: ENTITY_PICKER_TYPES,
    privacyClass: 'public',
    offlinePolicy: 'cached_entities',
    allowPersonalization: true,
    allowLiveContext: true,
    allowMemoryContext: true,
    allowAI: false,
    zeroStateAssistance: true,
    minChars: 1,
  },
  event_location: {
    context: 'event_location',
    defaultMode: 'canonical_picker',
    entityTypes: ['place', 'city'],
    allowedSuggestionTypes: ENTITY_PICKER_TYPES,
    privacyClass: 'public',
    offlinePolicy: 'cached_entities',
    allowPersonalization: false,
    allowLiveContext: true,
    allowMemoryContext: true,
    allowAI: false,
    zeroStateAssistance: true,
    minChars: 1,
  },
  event_title: {
    context: 'event_title',
    defaultMode: 'free_text_assisted',
    entityTypes: [],
    allowedSuggestionTypes: TEXT_ASSIST_TYPES,
    privacyClass: 'public',
    offlinePolicy: 'none',
    allowPersonalization: false,
    allowLiveContext: false,
    allowMemoryContext: false,
    allowAI: true,
    zeroStateAssistance: false,
    minChars: 2,
  },
  event_description: {
    context: 'event_description',
    defaultMode: 'ai_assisted',
    entityTypes: [],
    allowedSuggestionTypes: ['ai_suggestion', 'completion'],
    privacyClass: 'public',
    offlinePolicy: 'none',
    allowPersonalization: false,
    allowLiveContext: false,
    allowMemoryContext: false,
    allowAI: true,
    zeroStateAssistance: false,
    minChars: 0,
  },
  plan_title: {
    context: 'plan_title',
    defaultMode: 'free_text_assisted',
    entityTypes: [],
    allowedSuggestionTypes: TEXT_ASSIST_TYPES,
    privacyClass: 'personal',
    offlinePolicy: 'none',
    allowPersonalization: false,
    allowLiveContext: false,
    allowMemoryContext: false,
    allowAI: true,
    zeroStateAssistance: false,
    minChars: 2,
  },
  hidden_gem_name: {
    context: 'hidden_gem_name',
    defaultMode: 'free_text_assisted',
    // Duplicate detection resolves existing Gems/Places before creation (§20, §55).
    entityTypes: ['hidden_gem', 'place'],
    allowedSuggestionTypes: ['entity', 'validation', 'completion', 'disambiguation'],
    privacyClass: 'public',
    offlinePolicy: 'none',
    allowPersonalization: false,
    allowLiveContext: false,
    allowMemoryContext: false,
    allowAI: false,
    zeroStateAssistance: false,
    minChars: 2,
  },
  hidden_gem_location: {
    context: 'hidden_gem_location',
    defaultMode: 'canonical_picker',
    entityTypes: ['place', 'neighborhood', 'city', 'hidden_gem'],
    allowedSuggestionTypes: ['entity', 'recent', 'action', 'disambiguation'],
    // Sensitive/protected-location policy applies before projection (§20, §29, §55).
    privacyClass: 'sensitive',
    offlinePolicy: 'cached_entities',
    allowPersonalization: false,
    allowLiveContext: false,
    allowMemoryContext: true,
    allowAI: false,
    zeroStateAssistance: true,
    minChars: 1,
  },
  buddy_service: {
    context: 'buddy_service',
    defaultMode: 'free_text_assisted',
    entityTypes: [],
    allowedSuggestionTypes: ['completion', 'ai_suggestion'],
    privacyClass: 'public',
    offlinePolicy: 'none',
    allowPersonalization: false,
    allowLiveContext: false,
    allowMemoryContext: false,
    allowAI: true,
    zeroStateAssistance: false,
    minChars: 2,
  },
  buddy_service_area: {
    context: 'buddy_service_area',
    defaultMode: 'canonical_picker',
    entityTypes: ['city', 'neighborhood', 'place'],
    allowedSuggestionTypes: ENTITY_PICKER_TYPES,
    privacyClass: 'public',
    offlinePolicy: 'cached_entities',
    allowPersonalization: false,
    allowLiveContext: false,
    allowMemoryContext: true,
    allowAI: false,
    zeroStateAssistance: true,
    minChars: 1,
  },
  username: {
    context: 'username',
    defaultMode: 'free_text_assisted',
    entityTypes: [],
    // Non-blocking availability + reserved-name validation (§23 validation table).
    allowedSuggestionTypes: ['validation', 'correction'],
    privacyClass: 'personal',
    offlinePolicy: 'none',
    allowPersonalization: false,
    allowLiveContext: false,
    allowMemoryContext: false,
    allowAI: false,
    zeroStateAssistance: false,
    minChars: 3,
  },
  display_name: {
    context: 'display_name',
    defaultMode: 'no_assistance',
    entityTypes: [],
    allowedSuggestionTypes: NONE_TYPES,
    privacyClass: 'personal',
    offlinePolicy: 'none',
    allowPersonalization: false,
    allowLiveContext: false,
    allowMemoryContext: false,
    allowAI: false,
    zeroStateAssistance: false,
    minChars: 0,
  },
  hashtag: {
    context: 'hashtag',
    defaultMode: 'search',
    entityTypes: ['hashtag'],
    allowedSuggestionTypes: ['entity', 'recent', 'validation'],
    privacyClass: 'public',
    offlinePolicy: 'recent_only',
    allowPersonalization: false,
    allowLiveContext: false,
    allowMemoryContext: true,
    allowAI: false,
    zeroStateAssistance: true,
    minChars: 1,
  },
  caption: {
    context: 'caption',
    defaultMode: 'free_text_assisted',
    // @mentions + #hashtags resolve to canonical refs (§26).
    entityTypes: ['user', 'place', 'trip', 'event', 'hashtag'],
    allowedSuggestionTypes: ['entity', 'ai_suggestion', 'completion'],
    privacyClass: 'public',
    offlinePolicy: 'none',
    allowPersonalization: false,
    allowLiveContext: false,
    allowMemoryContext: false,
    allowAI: true,
    zeroStateAssistance: false,
    minChars: 1,
  },
  comment: {
    context: 'comment',
    defaultMode: 'free_text_assisted',
    entityTypes: ['user', 'place', 'trip', 'event', 'hashtag'],
    allowedSuggestionTypes: ['entity', 'completion'],
    privacyClass: 'public',
    offlinePolicy: 'none',
    allowPersonalization: false,
    allowLiveContext: false,
    allowMemoryContext: false,
    allowAI: false,
    zeroStateAssistance: false,
    minChars: 1,
  },
  telegraph_recipient: {
    context: 'telegraph_recipient',
    defaultMode: 'search',
    entityTypes: ['user'],
    allowedSuggestionTypes: ['entity', 'recent', 'personalized'],
    // Recipient search must resist account enumeration (§47).
    privacyClass: 'personal',
    offlinePolicy: 'recent_only',
    allowPersonalization: true,
    allowLiveContext: false,
    allowMemoryContext: true,
    allowAI: false,
    zeroStateAssistance: true,
    minChars: 2,
  },
  telegraph_message: {
    context: 'telegraph_message',
    defaultMode: 'action_assisted',
    // Share Place / Trip stop / meeting point, plus @mentions (§21, §54).
    entityTypes: ['user', 'place', 'trip', 'event'],
    allowedSuggestionTypes: ['action', 'entity'],
    // Private message content — telemetry must never log raw text (§44).
    privacyClass: 'private_message',
    offlinePolicy: 'recent_only',
    allowPersonalization: false,
    allowLiveContext: true,
    allowMemoryContext: false,
    allowAI: false,
    zeroStateAssistance: false,
    minChars: 1,
  },
  compass_prompt: {
    context: 'compass_prompt',
    defaultMode: 'ai_assisted',
    entityTypes: ['place', 'trip', 'event', 'city'],
    allowedSuggestionTypes: ['ai_suggestion', 'completion', 'action'],
    privacyClass: 'personal',
    offlinePolicy: 'none',
    allowPersonalization: false,
    allowLiveContext: true,
    allowMemoryContext: true,
    allowAI: true,
    zeroStateAssistance: true,
    minChars: 0,
  },
  passport_homebase: {
    context: 'passport_homebase',
    defaultMode: 'canonical_picker',
    entityTypes: ['city', 'country'],
    allowedSuggestionTypes: ENTITY_PICKER_TYPES,
    privacyClass: 'personal',
    offlinePolicy: 'cached_entities',
    allowPersonalization: false,
    allowLiveContext: false,
    allowMemoryContext: true,
    allowAI: false,
    zeroStateAssistance: true,
    minChars: 1,
  },
  language: {
    context: 'language',
    defaultMode: 'canonical_picker',
    entityTypes: ['language'],
    allowedSuggestionTypes: ['entity', 'recent'],
    privacyClass: 'personal',
    offlinePolicy: 'static_dictionary',
    allowPersonalization: false,
    allowLiveContext: false,
    allowMemoryContext: true,
    allowAI: false,
    zeroStateAssistance: true,
    minChars: 0,
  },
  interest: {
    context: 'interest',
    defaultMode: 'canonical_picker',
    entityTypes: ['interest'],
    allowedSuggestionTypes: ['entity', 'structured_value', 'recent'],
    privacyClass: 'personal',
    offlinePolicy: 'static_dictionary',
    allowPersonalization: false,
    allowLiveContext: false,
    allowMemoryContext: true,
    allowAI: false,
    zeroStateAssistance: true,
    minChars: 0,
  },
  address: {
    context: 'address',
    defaultMode: 'canonical_picker',
    entityTypes: ['place'],
    allowedSuggestionTypes: ['entity', 'action', 'disambiguation'],
    privacyClass: 'sensitive',
    offlinePolicy: 'cached_entities',
    allowPersonalization: false,
    allowLiveContext: false,
    allowMemoryContext: true,
    allowAI: false,
    zeroStateAssistance: false,
    minChars: 2,
  },
  generic_text: {
    context: 'generic_text',
    defaultMode: 'no_assistance',
    entityTypes: [],
    allowedSuggestionTypes: NONE_TYPES,
    privacyClass: 'personal',
    offlinePolicy: 'none',
    allowPersonalization: false,
    allowLiveContext: false,
    allowMemoryContext: false,
    allowAI: false,
    zeroStateAssistance: false,
    minChars: 2,
  },
};

/** Look up a context descriptor. Returns the `generic_text` descriptor if the
 *  context is somehow unknown (defensive — the union should prevent this). */
export function getContextDescriptor(context: InputContext): InputContextDescriptor {
  return INPUT_CONTEXT_REGISTRY[context] ?? INPUT_CONTEXT_REGISTRY.generic_text;
}
