/**
 * chainRlsFacts — what the post-baseline migration chain says about each table
 * it creates: whether RLS is on, and which policies exist, read from the
 * migration TEXT in apply order. PURE: no filesystem, no network, no
 * environment; callers hand it file names and SQL.
 *
 * Two consumers:
 *   * rlsDispositionsChain.ts (generated by generateChainRlsDispositions.ts) —
 *     the RLS disposition of every post-baseline table, which the inverse audit
 *     (audit:live-unexplained) requires for every live table. rlsDispositions
 *     .test.ts re-derives each entry from these facts, so a disposition cannot
 *     drift from the chain.
 *   * explainedLiveObjects.ts's DYNAMIC_DDL ledger rows — the policies the chain
 *     creates through `EXECUTE format('CREATE POLICY %I …')` with names no plain
 *     text scan can read. deriveDynamicPolicies() is the generator, and every
 *     ledger row cites the file:line of the CREATE POLICY template that issues it.
 *
 * WHAT IS READ, IN APPLY ORDER (filename order; ORDER_OVERRIDES.json moves no
 * file that creates, drops or alters a policy or an RLS switch):
 *   * CREATE TABLE / DROP TABLE (clientTableAclDecisions.createdTables /
 *     droppedTables);
 *   * ALTER TABLE … ENABLE | DISABLE ROW LEVEL SECURITY, written out or inside
 *     an EXECUTE literal, and the same issued by FOREACH-literal loops
 *     (expandForeachLiteralLoops);
 *   * CREATE POLICY / DROP POLICY [IF EXISTS] / ALTER POLICY … RENAME TO, the
 *     same three ways;
 *   * the dynamic CREATE POLICY loops deriveDynamicPolicies() can evaluate
 *     exactly (see there).
 * A policy the text cannot name stays out of the count rather than being
 * guessed at; the test that consumes these facts then disagrees with the live
 * audit, which is the point.
 */
import {
  blankSqlComments,
  CHAIN_START_PREFIX,
  expandForeachLiteralLoops,
} from "./liveVsCanonicalCore.js";
import { createdTables, droppedTables, type MigrationText } from "./clientTableAclDecisions.js";

// ─────────────────────────────────────────────────────────────────────────────
// A tiny evaluator for the plpgsql string expressions policy loops use
// ─────────────────────────────────────────────────────────────────────────────

type Env = ReadonlyMap<string, string>;

/** Read a single-quoted literal at src[i]; returns value and end index, or null. */
function quoted(src: string, i: number): { value: string; end: number } | null {
  if (src[i] !== "'") return null;
  let v = "";
  let j = i + 1;
  while (j < src.length) {
    if (src[j] === "'" && src[j + 1] === "'") {
      v += "'";
      j += 2;
    } else if (src[j] === "'") return { value: v, end: j + 1 };
    else v += src[j++];
  }
  return null;
}

/** Split on commas at paren depth 0, outside single quotes. */
function splitArgs(s: string): string[] {
  const out: string[] = [];
  let depth = 0;
  let cur = "";
  for (let i = 0; i < s.length; i++) {
    const ch = s[i]!;
    if (ch === "'") {
      const q = quoted(s, i);
      if (!q) return [s];
      cur += s.slice(i, q.end);
      i = q.end - 1;
      continue;
    }
    if (ch === "(") depth++;
    else if (ch === ")") depth--;
    if (ch === "," && depth === 0) {
      out.push(cur.trim());
      cur = "";
    } else cur += ch;
  }
  if (cur.trim()) out.push(cur.trim());
  return out;
}

/** Index of the paren matching src[open] === "(", outside quotes; -1 if none. */
function matchParen(src: string, open: number): number {
  let depth = 0;
  for (let i = open; i < src.length; i++) {
    const ch = src[i]!;
    if (ch === "'") {
      const q = quoted(src, i);
      if (!q) return -1;
      i = q.end - 1;
      continue;
    }
    if (ch === "(") depth++;
    else if (ch === ")" && --depth === 0) return i;
  }
  return -1;
}

/** format() with %I, %s, %L and %% — exactly; null on anything else. */
export function pgFormat(tpl: string, args: readonly string[]): string | null {
  let k = 0;
  let out = "";
  for (let j = 0; j < tpl.length; j++) {
    const ch = tpl[j]!;
    if (ch !== "%") {
      out += ch;
      continue;
    }
    const spec = tpl[++j];
    if (spec === "%") out += "%";
    else if ((spec === "I" || spec === "s" || spec === "L") && k < args.length) {
      const a = args[k++]!;
      out += spec === "I" ? (/^[a-z_][a-z0-9_$]*$/.test(a) ? a : `"${a.replace(/"/g, '""')}"`) : spec === "L" ? `'${a.replace(/'/g, "''")}'` : a;
    } else return null;
  }
  return out;
}

/**
 * Evaluate a string expression: literals, variables bound in `env`, `||`,
 * lower()/upper(), and format(). Anything else — a CASE, a query, a variable
 * the env does not bind — is null: unknown, never guessed.
 */
export function evalStringExpr(expr: string, env: Env): string | null {
  const parts: string[] = [];
  // split on top-level ||
  let depth = 0;
  let cur = "";
  for (let i = 0; i < expr.length; i++) {
    const ch = expr[i]!;
    if (ch === "'") {
      const q = quoted(expr, i);
      if (!q) return null;
      cur += expr.slice(i, q.end);
      i = q.end - 1;
      continue;
    }
    if (ch === "(") depth++;
    else if (ch === ")") depth--;
    if (depth === 0 && ch === "|" && expr[i + 1] === "|") {
      parts.push(cur.trim());
      cur = "";
      i++;
      continue;
    }
    cur += ch;
  }
  parts.push(cur.trim());
  let acc = "";
  for (const p of parts) {
    const v = evalTerm(p, env);
    if (v === null) return null;
    acc += v;
  }
  return acc;
}

function evalTerm(t: string, env: Env): string | null {
  if (!t) return null;
  if (t.startsWith("'")) {
    const q = quoted(t, 0);
    return q && q.end === t.length ? q.value : null;
  }
  if (t.startsWith("(") && matchParen(t, 0) === t.length - 1) return evalStringExpr(t.slice(1, -1), env);
  const call = /^([A-Za-z_][\w.]*)\s*\(/.exec(t);
  if (call) {
    const close = matchParen(t, call[0].length - 1);
    if (close !== t.length - 1) return null;
    const args = splitArgs(t.slice(call[0].length, close));
    const fn = call[1]!.toLowerCase();
    if (fn === "lower" || fn === "upper") {
      if (args.length !== 1) return null;
      const v = evalStringExpr(args[0]!, env);
      return v === null ? null : fn === "lower" ? v.toLowerCase() : v.toUpperCase();
    }
    if (fn === "format") {
      const tpl = evalStringExpr(args[0] ?? "", env);
      if (tpl === null) return null;
      const vals: string[] = [];
      for (const a of args.slice(1)) {
        const v = evalStringExpr(a, env);
        if (v === null) return null;
        vals.push(v);
      }
      return pgFormat(tpl, vals);
    }
    return null;
  }
  const id = t.toLowerCase();
  return /^[a-z_][\w.]*$/.test(id) && env.has(id) ? env.get(id)! : null;
}

// ─────────────────────────────────────────────────────────────────────────────
// Dynamic CREATE POLICY derivation
// ─────────────────────────────────────────────────────────────────────────────

export interface DynamicPolicy {
  table: string;
  policy: string;
  /** Bare filename of the migration that issues it. */
  file: string;
  /** 1-based line of the `CREATE POLICY %I` format template that issues it. */
  line: number;
  /** Which derivation produced it. */
  via: "loop" | "keep-list";
}

const lineOf = (src: string, idx: number) => src.slice(0, idx).split("\n").length;

interface LoopSpan {
  v: string;
  values: string[];
  start: number;
  end: number;
}

/** Literal-array FOREACH loops in `src`, with their body spans. */
function literalLoops(src: string): LoopSpan[] {
  const out: LoopSpan[] = [];
  const re = /\bforeach\s+([A-Za-z_]\w*)\s+in\s+array\s+array\s*\[/gi;
  let m: RegExpExecArray | null;
  while ((m = re.exec(src)) !== null) {
    const values: string[] = [];
    let i = m.index + m[0].length;
    let ok = true;
    for (;;) {
      while (/\s/.test(src[i] ?? "")) i++;
      if (src[i] === "]") {
        i++;
        break;
      }
      const q = quoted(src, i);
      if (!q) {
        ok = false;
        break;
      }
      values.push(q.value);
      i = q.end;
      while (/\s/.test(src[i] ?? "")) i++;
      if (src[i] === ",") i++;
    }
    const kw = /^\s*loop\b/i.exec(src.slice(i));
    if (!ok || !values.length || !kw) continue;
    const start = i + kw[0].length;
    const wr = /\b(end\s+loop|loop)\b/gi;
    wr.lastIndex = start;
    let depth = 1;
    let w: RegExpExecArray | null;
    let end = -1;
    while ((w = wr.exec(src)) !== null) {
      if (/^end/i.test(w[1]!)) {
        if (--depth === 0) {
          end = w.index;
          break;
        }
      } else depth++;
    }
    if (end > 0) out.push({ v: m[1]!.toLowerCase(), values, start, end });
  }
  return out;
}

function* product(loops: readonly LoopSpan[]): Generator<Map<string, string>> {
  if (!loops.length) {
    yield new Map();
    return;
  }
  const [first, ...rest] = loops;
  for (const v of first!.values) {
    for (const env of product(rest)) {
      const e = new Map(env);
      e.set(first!.v, v);
      yield e;
    }
  }
}

/**
 * Policies a migration creates through `EXECUTE format('CREATE POLICY %I ON
 * public.<%I | table> …', <name>, [<table>], …)`, where every value the name
 * and the table need comes from literal FOREACH arrays enclosing the EXECUTE,
 * string literals, lower()/upper()/format(), and `v := <expr>` assignments made
 * earlier inside the same loop (3416, 3466, 3476, 3486, 3487, 3488, 3495,
 * 2762, 2763). An EXECUTE inside a `FOR r IN SELECT …` loop, or whose name
 * depends on anything else, yields nothing (3502's `spec.pname`).
 */
export function deriveLoopPolicies(file: string, sql: string): DynamicPolicy[] {
  const src = blankSqlComments(sql);
  const loops = literalLoops(src);
  const forSelect: Array<{ start: number; end: number }> = [];
  for (const m of src.matchAll(/\bfor\s+[A-Za-z_]\w*\s+in\s+select\b[\s\S]*?\bloop\b/gi)) {
    const start = m.index! + m[0].length;
    const wr = /\b(end\s+loop|loop)\b/gi;
    wr.lastIndex = start;
    let depth = 1;
    let w: RegExpExecArray | null;
    while ((w = wr.exec(src)) !== null) {
      if (/^end/i.test(w[1]!)) {
        if (--depth === 0) {
          forSelect.push({ start, end: w.index });
          break;
        }
      } else depth++;
    }
  }
  const out: DynamicPolicy[] = [];
  const execRe = /\bexecute\s+format\s*\(/gi;
  let e: RegExpExecArray | null;
  while ((e = execRe.exec(src)) !== null) {
    const open = e.index + e[0].length - 1;
    const close = matchParen(src, open);
    if (close < 0) continue;
    const args = splitArgs(src.slice(open + 1, close));
    const tq = quoted(args[0] ?? "", 0);
    if (!tq) continue;
    const head = /^\s*create\s+policy\s+%I\s+on\s+(?:public\.)?(%I|[A-Za-z_]\w*)\b/i.exec(tq.value);
    if (!head) continue;
    if (forSelect.some((f) => f.start <= e!.index && e!.index < f.end)) continue;
    const enclosing = loops.filter((l) => l.start <= e!.index && e!.index < l.end);
    const innermost = enclosing.reduce<LoopSpan | null>((a, l) => (!a || l.start > a.start ? l : a), null);
    const scopeStart = innermost ? innermost.start : 0;
    const assigns = [...src.slice(scopeStart, e.index).matchAll(/\b([A-Za-z_]\w*)\s*:=\s*([^;]+);/g)];
    for (const env of product(enclosing)) {
      const local = new Map(env);
      for (const a of assigns) {
        const v = evalStringExpr(a[2]!.trim(), local);
        if (v !== null) local.set(a[1]!.toLowerCase(), v);
        else local.delete(a[1]!.toLowerCase());
      }
      const policy = evalStringExpr(args[1] ?? "", local);
      const table = head[1] === "%I" ? evalStringExpr(args[2] ?? "", local) : head[1]!.toLowerCase();
      if (policy === null || table === null) continue;
      out.push({ table: table.toLowerCase(), policy: policy.toLowerCase(), file, line: lineOf(src, e.index), via: "loop" });
    }
  }
  return out;
}

/**
 * 3390's keep-list shape: a temp table of target tables and a temp table of
 * (table, verb, role) triples to KEEP; for every target and every verb in the
 * literal FOREACH array, the client roles not kept are denied by a RESTRICTIVE
 * policy named format('%s_deny_%s_%s', tbl, lower(verb), who), where who is
 * 'clients' when both roles are denied and the one role's name otherwise, and
 * no policy is created when neither is (3390_discovery_rls_explicit_policies.sql,
 * the DO $apply$ block). Recognised only when every one of those pieces is
 * present in the file as literal text; otherwise nothing is derived.
 */
export function deriveKeepListDenyPolicies(file: string, sql: string): DynamicPolicy[] {
  const src = blankSqlComments(sql);
  const tmpl = /execute\s+format\s*\(\s*'CREATE POLICY %I ON public\.%I AS RESTRICTIVE FOR %s TO %s %s'/i.exec(src);
  const nameFmt = /pname\s*:=\s*format\s*\(\s*'%s_deny_%s_%s'\s*,\s*([a-z_]\w*)\.([a-z_]\w*)\s*,\s*lower\(\s*v_op\s*\)\s*,\s*who\s*\)/i.exec(src);
  const whoRule = /who\s*:=\s*CASE\s+WHEN\s+array_length\(\s*denied\s*,\s*1\s*\)\s*=\s*2\s+THEN\s+'clients'\s+ELSE\s+denied\[1\]\s+END/i.exec(src);
  const ops = /FOREACH\s+v_op\s+IN\s+ARRAY\s+ARRAY\[([^\]]*)\]/i.exec(src);
  const tablesLoop = /FOR\s+([a-z_]\w*)\s+IN\s+SELECT\s+([a-z_]\w*)\s*,[^;]*?FROM\s+([a-z_]\w*)\s+ORDER\s+BY/i.exec(src);
  const deniedFrom = /unnest\(\s*ARRAY\['anon'\s*,\s*'authenticated'\]\s*\)\s*r\s+WHERE\s+NOT\s+EXISTS\s*\(\s*SELECT\s+1\s+FROM\s+([a-z_]\w*)\s+k\s+WHERE\s+k\.tbl\s*=\s*t\.tbl\s+AND\s+k\.op\s*=\s*v_op\s+AND\s+k\.role\s*=\s*r\s*\)/i.exec(src);
  if (!tmpl || !nameFmt || !whoRule || !ops || !tablesLoop || !deniedFrom) return [];
  const rowsOf = (tmp: string): string[][] => {
    const ins = new RegExp(String.raw`insert\s+into\s+${tmp}\s*\([^)]*\)\s*values\s*`, "i").exec(src);
    if (!ins) return [];
    const rows: string[][] = [];
    let i = ins.index + ins[0].length;
    for (;;) {
      while (/[\s,]/.test(src[i] ?? "")) i++;
      if (src[i] !== "(") break;
      const close = matchParen(src, i);
      if (close < 0) break;
      rows.push(splitArgs(src.slice(i + 1, close)).map((a) => quoted(a, 0)?.value ?? ""));
      i = close + 1;
    }
    return rows;
  };
  const targets = rowsOf(tablesLoop[3]!).map((r) => r[0]!).sort();
  const keep = new Set(rowsOf(deniedFrom[1]!).map((r) => `${r[0]}|${r[1]}|${r[2]}`));
  const verbs = [...ops[1]!.matchAll(/'([A-Z]+)'/g)].map((m) => m[1]!);
  const line = lineOf(src, tmpl.index);
  const out: DynamicPolicy[] = [];
  for (const t of targets) {
    for (const op of verbs) {
      const denied = ["anon", "authenticated"].filter((r) => !keep.has(`${t}|${op}|${r}`));
      if (!denied.length) continue;
      const who = denied.length === 2 ? "clients" : denied[0]!;
      out.push({ table: t, policy: `${t}_deny_${op.toLowerCase()}_${who}`, file, line, via: "keep-list" });
    }
  }
  return out;
}

/** Every dynamically created policy the chain's text fixes, in file order. */
export function deriveDynamicPolicies(files: readonly MigrationText[]): DynamicPolicy[] {
  const out: DynamicPolicy[] = [];
  for (const f of [...files].sort((a, b) => (a.name < b.name ? -1 : 1))) {
    out.push(...deriveLoopPolicies(f.name, f.sql), ...deriveKeepListDenyPolicies(f.name, f.sql));
  }
  return out;
}

// ─────────────────────────────────────────────────────────────────────────────
// Per-table RLS facts over the post-baseline chain
// ─────────────────────────────────────────────────────────────────────────────

export interface TableRlsFacts {
  /** The file whose CREATE TABLE made it. */
  createdBy: string;
  rlsEnabled: boolean;
  /** Policy names present after the whole chain. */
  policies: Set<string>;
}

type Ev =
  | { k: "rls"; t: string; on: boolean }
  | { k: "create"; t: string; p: string }
  | { k: "drop"; t: string; p: string }
  | { k: "rename"; t: string; p: string; to: string };

const QI = String.raw`(?:"?[A-Za-z_][\w$]*"?\.)?"?([A-Za-z_][\w$]*)"?`;
const PN = String.raw`(?:"([^"]+)"|([A-Za-z_][\w$]*))`;

/** RLS and policy events in one text, in text order. */
function events(text: string): Ev[] {
  const re = new RegExp(
    String.raw`alter\s+table\s+(?:if\s+exists\s+)?(?:only\s+)?${QI}\s+(enable|disable)\s+row\s+level\s+security` +
      String.raw`|create\s+policy\s+${PN}\s+on\s+${QI}` +
      String.raw`|drop\s+policy\s+(?:if\s+exists\s+)?${PN}\s+on\s+${QI}` +
      String.raw`|alter\s+policy\s+${PN}\s+on\s+${QI}\s+rename\s+to\s+${PN}`,
    "gi",
  );
  const out: Ev[] = [];
  for (const m of text.matchAll(re)) {
    const s = m[0].toLowerCase();
    if (m[1]) out.push({ k: "rls", t: m[1].toLowerCase(), on: m[2]!.toLowerCase() === "enable" });
    else if (s.startsWith("create")) out.push({ k: "create", p: (m[3] ?? m[4])!.toLowerCase(), t: m[5]!.toLowerCase() });
    else if (s.startsWith("drop")) out.push({ k: "drop", p: (m[6] ?? m[7])!.toLowerCase(), t: m[8]!.toLowerCase() });
    else out.push({ k: "rename", p: (m[9] ?? m[10])!.toLowerCase(), t: m[11]!.toLowerCase(), to: (m[12] ?? m[13])!.toLowerCase() });
  }
  return out;
}

/**
 * RLS facts for every table the post-baseline chain creates and does not drop.
 * Files below CHAIN_START_PREFIX are not read: the baseline already reflects them.
 */
export function chainRlsFacts(
  files: readonly MigrationText[],
  baselineTables: ReadonlySet<string>,
): Map<string, TableRlsFacts> {
  const chain = [...files].filter((f) => f.name >= CHAIN_START_PREFIX).sort((a, b) => (a.name < b.name ? -1 : 1));
  const facts = new Map<string, TableRlsFacts>();
  const dynamic = new Map<string, DynamicPolicy[]>();
  for (const d of deriveDynamicPolicies(chain)) {
    if (!dynamic.has(d.file)) dynamic.set(d.file, []);
    dynamic.get(d.file)!.push(d);
  }
  for (const f of chain) {
    const src = blankSqlComments(f.sql);
    for (const t of createdTables(src)) {
      if (!baselineTables.has(t) && !facts.has(t)) facts.set(t, { createdBy: f.name, rlsEnabled: false, policies: new Set() });
    }
    const evs = [...events(src), ...events(expandForeachLiteralLoops(src))];
    for (const d of dynamic.get(f.name) ?? []) {
      if (!evs.some((x) => x.k === "create" && x.t === d.table && x.p === d.policy)) evs.push({ k: "create", t: d.table, p: d.policy });
    }
    for (const ev of evs) {
      const fact = facts.get(ev.t);
      if (!fact) continue;
      if (ev.k === "rls") fact.rlsEnabled = ev.on;
      else if (ev.k === "create") fact.policies.add(ev.p);
      else if (ev.k === "drop") fact.policies.delete(ev.p);
      else if (fact.policies.delete(ev.p)) fact.policies.add(ev.to);
    }
    for (const t of droppedTables(src)) facts.delete(t);
  }
  return facts;
}

// ─────────────────────────────────────────────────────────────────────────────
// The generated disposition file
// ─────────────────────────────────────────────────────────────────────────────

/** The date stamped into generated DENY_ALL reasons (the generation that wrote them). */
export const CHAIN_DISPOSITIONS_GENERATED_ON = "2026-10-07";

/**
 * The exact text of src/scripts/rlsDispositionsChain.ts for these facts,
 * excluding tables `exclude` already carries (POST_BASELINE_RLS_DISPOSITIONS'
 * hand-written entries). rlsDispositions.test.ts compares the committed file
 * with this byte for byte; regenerate with
 *   WRITE_CHAIN_RLS_DISPOSITIONS=1 node --import tsx/esm --test src/test/rlsDispositions.test.ts
 */
export function renderChainRlsDispositions(
  facts: ReadonlyMap<string, TableRlsFacts>,
  exclude: ReadonlySet<string>,
): string {
  const lines: string[] = [];
  for (const t of [...facts.keys()].sort()) {
    if (exclude.has(t)) continue;
    const f = facts.get(t)!;
    const policies = [...f.policies].sort();
    const cls = !f.rlsEnabled ? "NEEDS_REVIEW" : policies.length ? "RLS_REQUIRED" : "DENY_ALL_BY_DESIGN";
    const reason =
      cls === "DENY_ALL_BY_DESIGN"
        ? `Chain-derived ${CHAIN_DISPOSITIONS_GENERATED_ON} from ${f.createdBy}: RLS enabled and no migration in the chain creates a policy on this table -- deny-all to every client role (service_role bypasses RLS). Mechanically classified; not yet reviewed for a table-specific justification.`
        : cls === "NEEDS_REVIEW"
          ? `Chain-derived ${CHAIN_DISPOSITIONS_GENERATED_ON} from ${f.createdBy}: no migration in the chain enables RLS on this table. Unresolved until reviewed.`
          : null;
    lines.push(
      `  ${JSON.stringify(t)}: { class: ${JSON.stringify(cls)}, policyCount: ${policies.length}, migration: ${JSON.stringify(f.createdBy)}, ` +
        `policies: ${JSON.stringify(policies)}${reason ? `, reason: ${JSON.stringify(reason)}` : ""} },`,
    );
  }
  return [
    "/**",
    " * GENERATED from the migration chain by renderChainRlsDispositions()",
    " * (src/scripts/lib/chainRlsFacts.ts). Do not edit by hand: change the",
    " * migrations, then regenerate with",
    " *   WRITE_CHAIN_RLS_DISPOSITIONS=1 node --import tsx/esm --test src/test/rlsDispositions.test.ts",
    " * and review the diff. rlsDispositions.test.ts fails while this file and the",
    " * chain disagree.",
    " *",
    " * One entry per table the post-baseline chain (files >= CHAIN_START_PREFIX)",
    " * creates and does not drop, except those POST_BASELINE_RLS_DISPOSITIONS in",
    " * rlsDispositions.ts already records by hand. Class follows that file's model:",
    " * RLS on with >= 1 policy is RLS_REQUIRED, RLS on with none is",
    " * DENY_ALL_BY_DESIGN, RLS never enabled is NEEDS_REVIEW (which the inverse",
    " * audit reports as unresolved). `policies` are the names present after the",
    " * whole chain, dynamic loop-created ones included (deriveDynamicPolicies).",
    " * At the next baseline recapture these move into RLS_DISPOSITIONS.",
    " */",
    'import type { RlsDisposition } from "./rlsDispositions.js";',
    "",
    "export type ChainRlsDisposition = RlsDisposition & { migration: string; policies: readonly string[] };",
    "",
    "export const CHAIN_RLS_DISPOSITIONS: Readonly<Record<string, ChainRlsDisposition>> = {",
    ...lines,
    "};",
    "",
  ].join("\n");
}
