// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/passport-header/Owner.tsx": () => import("../components/mockups/passport-header/Owner.tsx"),
  "./components/mockups/passport-header/Public.tsx": () => import("../components/mockups/passport-header/Public.tsx")
};
