-- Migration 2054: Backfill country on stamp ownership rows saved with country=null
--
-- The stamp-award pipeline fix (stampHelper.ts) prevents NEW rows from landing
-- with country=null, but existing rows written before the fix need a one-time
-- repair. This migration covers the common case via a static city→country map
-- (instant, no external calls, idempotent).
--
-- Rows whose city is not in the static map are left for the periodic
-- XX-catalog sweeper (startXXCatalogSweeper in index.ts) which applies forward
-- geocoding as a fallback — those rows will be resolved within minutes of the
-- next server boot.
--
-- Safe to re-run: WHERE country IS NULL AND city IS NOT NULL ensures already-
-- backfilled rows are never touched twice.

DO $$ DECLARE
  city_map CONSTANT TEXT[][] := ARRAY[
    -- Europe
    ARRAY['london',            'United Kingdom'],
    ARRAY['manchester',        'United Kingdom'],
    ARRAY['edinburgh',         'United Kingdom'],
    ARRAY['glasgow',           'United Kingdom'],
    ARRAY['liverpool',         'United Kingdom'],
    ARRAY['birmingham',        'United Kingdom'],
    ARRAY['bristol',           'United Kingdom'],
    ARRAY['dublin',            'Ireland'],
    ARRAY['paris',             'France'],
    ARRAY['lyon',              'France'],
    ARRAY['marseille',         'France'],
    ARRAY['nice',              'France'],
    ARRAY['bordeaux',          'France'],
    ARRAY['berlin',            'Germany'],
    ARRAY['munich',            'Germany'],
    ARRAY['hamburg',           'Germany'],
    ARRAY['frankfurt',         'Germany'],
    ARRAY['cologne',           'Germany'],
    ARRAY['madrid',            'Spain'],
    ARRAY['barcelona',         'Spain'],
    ARRAY['seville',           'Spain'],
    ARRAY['valencia',          'Spain'],
    ARRAY['malaga',            'Spain'],
    ARRAY['lisbon',            'Portugal'],
    ARRAY['porto',             'Portugal'],
    ARRAY['rome',              'Italy'],
    ARRAY['milan',             'Italy'],
    ARRAY['venice',            'Italy'],
    ARRAY['florence',          'Italy'],
    ARRAY['naples',            'Italy'],
    ARRAY['amsterdam',         'Netherlands'],
    ARRAY['rotterdam',         'Netherlands'],
    ARRAY['brussels',          'Belgium'],
    ARRAY['antwerp',           'Belgium'],
    ARRAY['vienna',            'Austria'],
    ARRAY['zurich',            'Switzerland'],
    ARRAY['geneva',            'Switzerland'],
    ARRAY['prague',            'Czech Republic'],
    ARRAY['budapest',          'Hungary'],
    ARRAY['warsaw',            'Poland'],
    ARRAY['krakow',            'Poland'],
    ARRAY['athens',            'Greece'],
    ARRAY['santorini',         'Greece'],
    ARRAY['stockholm',         'Sweden'],
    ARRAY['gothenburg',        'Sweden'],
    ARRAY['oslo',              'Norway'],
    ARRAY['copenhagen',        'Denmark'],
    ARRAY['helsinki',          'Finland'],
    ARRAY['reykjavik',         'Iceland'],
    ARRAY['moscow',            'Russia'],
    ARRAY['saint petersburg',  'Russia'],
    ARRAY['istanbul',          'Turkey'],
    ARRAY['dubrovnik',         'Croatia'],
    ARRAY['zagreb',            'Croatia'],
    ARRAY['split',             'Croatia'],
    ARRAY['bucharest',         'Romania'],
    ARRAY['sofia',             'Bulgaria'],
    ARRAY['belgrade',          'Serbia'],
    ARRAY['tallinn',           'Estonia'],
    ARRAY['riga',              'Latvia'],
    ARRAY['vilnius',           'Lithuania'],
    ARRAY['kyiv',              'Ukraine'],
    ARRAY['kiev',              'Ukraine'],
    -- Americas
    ARRAY['new york',          'United States'],
    ARRAY['new york city',     'United States'],
    ARRAY['los angeles',       'United States'],
    ARRAY['san francisco',     'United States'],
    ARRAY['chicago',           'United States'],
    ARRAY['miami',             'United States'],
    ARRAY['seattle',           'United States'],
    ARRAY['boston',            'United States'],
    ARRAY['austin',            'United States'],
    ARRAY['las vegas',         'United States'],
    ARRAY['honolulu',          'United States'],
    ARRAY['washington',        'United States'],
    ARRAY['denver',            'United States'],
    ARRAY['portland',          'United States'],
    ARRAY['new orleans',       'United States'],
    ARRAY['san diego',         'United States'],
    ARRAY['toronto',           'Canada'],
    ARRAY['vancouver',         'Canada'],
    ARRAY['montreal',          'Canada'],
    ARRAY['calgary',           'Canada'],
    ARRAY['ottawa',            'Canada'],
    ARRAY['mexico city',       'Mexico'],
    ARRAY['cancun',            'Mexico'],
    ARRAY['guadalajara',       'Mexico'],
    ARRAY['tulum',             'Mexico'],
    ARRAY['rio de janeiro',    'Brazil'],
    ARRAY['sao paulo',         'Brazil'],
    ARRAY['buenos aires',      'Argentina'],
    ARRAY['santiago',          'Chile'],
    ARRAY['lima',              'Peru'],
    ARRAY['cusco',             'Peru'],
    ARRAY['bogota',            'Colombia'],
    ARRAY['medellin',          'Colombia'],
    ARRAY['cartagena',         'Colombia'],
    ARRAY['quito',             'Ecuador'],
    ARRAY['havana',            'Cuba'],
    ARRAY['san jose',          'Costa Rica'],
    ARRAY['panama city',       'Panama'],
    ARRAY['montevideo',        'Uruguay'],
    -- Asia-Pacific
    ARRAY['tokyo',             'Japan'],
    ARRAY['osaka',             'Japan'],
    ARRAY['kyoto',             'Japan'],
    ARRAY['sapporo',           'Japan'],
    ARRAY['fukuoka',           'Japan'],
    ARRAY['seoul',             'South Korea'],
    ARRAY['busan',             'South Korea'],
    ARRAY['beijing',           'China'],
    ARRAY['shanghai',          'China'],
    ARRAY['shenzhen',          'China'],
    ARRAY['guangzhou',         'China'],
    ARRAY['chengdu',           'China'],
    ARRAY['hong kong',         'Hong Kong'],
    ARRAY['macau',             'Macau'],
    ARRAY['taipei',            'Taiwan'],
    ARRAY['bangkok',           'Thailand'],
    ARRAY['chiang mai',        'Thailand'],
    ARRAY['phuket',            'Thailand'],
    ARRAY['pattaya',           'Thailand'],
    ARRAY['singapore',         'Singapore'],
    ARRAY['kuala lumpur',      'Malaysia'],
    ARRAY['penang',            'Malaysia'],
    ARRAY['jakarta',           'Indonesia'],
    ARRAY['bali',              'Indonesia'],
    ARRAY['denpasar',          'Indonesia'],
    ARRAY['ubud',              'Indonesia'],
    ARRAY['manila',            'Philippines'],
    ARRAY['cebu',              'Philippines'],
    ARRAY['cebu city',         'Philippines'],
    ARRAY['davao',             'Philippines'],
    ARRAY['boracay',           'Philippines'],
    ARRAY['palawan',           'Philippines'],
    ARRAY['bohol',             'Philippines'],
    ARRAY['siargao',           'Philippines'],
    ARRAY['iloilo',            'Philippines'],
    ARRAY['bacolod',           'Philippines'],
    ARRAY['hanoi',             'Vietnam'],
    ARRAY['ho chi minh city',  'Vietnam'],
    ARRAY['saigon',            'Vietnam'],
    ARRAY['da nang',           'Vietnam'],
    ARRAY['hoi an',            'Vietnam'],
    ARRAY['phnom penh',        'Cambodia'],
    ARRAY['siem reap',         'Cambodia'],
    ARRAY['vientiane',         'Laos'],
    ARRAY['luang prabang',     'Laos'],
    ARRAY['yangon',            'Myanmar'],
    ARRAY['kathmandu',         'Nepal'],
    ARRAY['colombo',           'Sri Lanka'],
    ARRAY['mumbai',            'India'],
    ARRAY['delhi',             'India'],
    ARRAY['new delhi',         'India'],
    ARRAY['bangalore',         'India'],
    ARRAY['bengaluru',         'India'],
    ARRAY['goa',               'India'],
    ARRAY['jaipur',            'India'],
    ARRAY['chennai',           'India'],
    ARRAY['kolkata',           'India'],
    ARRAY['sydney',            'Australia'],
    ARRAY['melbourne',         'Australia'],
    ARRAY['brisbane',          'Australia'],
    ARRAY['perth',             'Australia'],
    ARRAY['adelaide',          'Australia'],
    ARRAY['cairns',            'Australia'],
    ARRAY['gold coast',        'Australia'],
    ARRAY['auckland',          'New Zealand'],
    ARRAY['wellington',        'New Zealand'],
    ARRAY['queenstown',        'New Zealand'],
    ARRAY['christchurch',      'New Zealand'],
    -- Middle East & Africa
    ARRAY['dubai',             'United Arab Emirates'],
    ARRAY['abu dhabi',         'United Arab Emirates'],
    ARRAY['doha',              'Qatar'],
    ARRAY['riyadh',            'Saudi Arabia'],
    ARRAY['jeddah',            'Saudi Arabia'],
    ARRAY['tel aviv',          'Israel'],
    ARRAY['jerusalem',         'Israel'],
    ARRAY['amman',             'Jordan'],
    ARRAY['beirut',            'Lebanon'],
    ARRAY['muscat',            'Oman'],
    ARRAY['kuwait city',       'Kuwait'],
    ARRAY['manama',            'Bahrain'],
    ARRAY['cairo',             'Egypt'],
    ARRAY['alexandria',        'Egypt'],
    ARRAY['marrakech',         'Morocco'],
    ARRAY['marrakesh',         'Morocco'],
    ARRAY['casablanca',        'Morocco'],
    ARRAY['fez',               'Morocco'],
    ARRAY['tunis',             'Tunisia'],
    ARRAY['cape town',         'South Africa'],
    ARRAY['johannesburg',      'South Africa'],
    ARRAY['durban',            'South Africa'],
    ARRAY['nairobi',           'Kenya'],
    ARRAY['lagos',             'Nigeria'],
    ARRAY['accra',             'Ghana'],
    ARRAY['addis ababa',       'Ethiopia'],
    ARRAY['dar es salaam',     'Tanzania'],
    ARRAY['zanzibar',          'Tanzania'],
    ARRAY['kampala',           'Uganda']
  ];
  tbl TEXT;
  pair TEXT[];
BEGIN
  FOREACH tbl IN ARRAY ARRAY['user_stamps', 'passport_stamps'] LOOP
    BEGIN
      FOREACH pair SLICE 1 IN ARRAY city_map LOOP
        EXECUTE format(
          'UPDATE %I SET country = $2
           WHERE country IS NULL
             AND city IS NOT NULL
             AND lower(trim(city)) = $1',
          tbl
        ) USING pair[1], pair[2];
      END LOOP;
    EXCEPTION WHEN undefined_table THEN
      -- table may not exist in all environments; skip silently
      NULL;
    END;
  END LOOP;
END $$;
