-- Upgrade the stubs to the shape the kernel actually writes.
ALTER TABLE public.trips ADD PRIMARY KEY (id);
ALTER TABLE public.trips ALTER COLUMN version SET DEFAULT 0, ALTER COLUMN version SET NOT NULL;
ALTER TABLE public.trips ALTER COLUMN created_at SET DEFAULT now();
ALTER TABLE public.trips ALTER COLUMN updated_at SET DEFAULT now();
ALTER TABLE public.trip_events ADD PRIMARY KEY (event_id);
ALTER TABLE public.trip_events ALTER COLUMN recorded_at SET DEFAULT now();
ALTER TABLE public.trip_command_receipts ADD PRIMARY KEY (trip_id, idempotency_key);
ALTER TABLE public.trip_command_receipts ALTER COLUMN created_at SET DEFAULT now();
ALTER TABLE public.trip_outbox DROP COLUMN id;
ALTER TABLE public.trip_outbox ADD COLUMN id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;
ALTER TABLE public.trip_outbox ALTER COLUMN created_at SET DEFAULT now();
ALTER TABLE public.trip_outbox ALTER COLUMN attempts SET DEFAULT 0;
ALTER TABLE public.trip_plan_items ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE public.trip_plan_items ADD PRIMARY KEY (id);
ALTER TABLE public.trip_plan_items ALTER COLUMN created_at SET DEFAULT now();
ALTER TABLE public.trip_plan_items ALTER COLUMN updated_at SET DEFAULT now();
ALTER TABLE public.trip_members ADD PRIMARY KEY (trip_id, user_id);
ALTER TABLE public.profiles ADD PRIMARY KEY (id);
DROP TABLE public.trip_stages;
-- authz.is_trip_crew is only referenced by 2760's RLS policy, which no probe
-- exercises (every probe runs as superuser). Stubbed true, and nothing here
-- claims otherwise.
CREATE FUNCTION authz.is_trip_crew(uuid) RETURNS boolean LANGUAGE sql AS $$ SELECT true $$;
-- authz.is_accepted_trip_member IS exercised: it is the 'crew' capability every
-- stage command requires, so it is the REAL rule, not a stub that returns true.
CREATE OR REPLACE FUNCTION authz.is_accepted_trip_member(p_trip uuid, p_user uuid)
  RETURNS boolean LANGUAGE sql AS $$
    SELECT EXISTS (SELECT 1 FROM public.trip_members m
                    WHERE m.trip_id = p_trip AND m.user_id = p_user AND m.status = 'accepted') $$;
-- The real 2420 gives trip_events.event_id a default; tables.sql carries column
-- types only, so it is restored here.
ALTER TABLE public.trip_events ALTER COLUMN event_id SET DEFAULT gen_random_uuid();
