/**
 * discoveryLetterFoldCompleteness — census-discovery §73 (lane P27): DV-20 and
 * B01, the Latin letter fold, enumerated over every Latin letter Node knows.
 *
 * §66.5 and §66.11 found one cause behind two rows. The stroke table in
 * lib/canonicalLocations ran BEFORE NFD, so Ǿ/ǿ (Ø/ø plus an acute) never met
 * it, and it had no entry for the hooked, barred and curled letters. So
 * "Ǿresund" keyed `resund` (B01), and the Trail slug, which reuses the table,
 * deleted 114 of the 398 Latin letters in U+00C0–U+024F (DV-20).
 *
 * The criterion (census-discovery §66.11): the fold runs NFD first, then a
 * stroke/hook/bar table covers every letter whose Unicode name is
 * "LATIN … LETTER X WITH …", in the TS folds and their SQL twins, pinned by an
 * exhaustive enumeration. The enumeration here is every code point that is a
 * letter (\p{L}) of the Latin script (\p{Script=Latin}) in this runtime's Unicode
 * (17.0): 1453 letters, far beyond U+00C0–U+024F.
 *
 * LETTERS lists every one of them that NFD does NOT reduce to one ASCII letter
 * plus combining marks, with its name from UnicodeData.txt 17.0. Every other
 * Latin letter is checked by computation (L1). The kinds follow
 * lib/latinLetterFold's rule:
 *   fold     the name is "… LETTER X WITH …", "… BARRED X" or "… X BAR" with X
 *            one letter A–Z (or TH), or the letter is the other case of one,
 *            or its uppercase is ASCII (ſ ı), or it is 2220's eth: every fold
 *            gives the spelling shown (Ŀ ŀ ẚ keep their compatibility spelling).
 *   as       X is itself a Latin letter (AE, THORN, EZH, the DZ digraph, …),
 *            given here: every fold treats the letter exactly as it treats X.
 *   outside  not "X WITH …" (a letter of its own, a ligature, a digraph, a
 *            MODIFIER LETTER form), or X names no letter (ƻ TWO). Not in the
 *            criterion. What searchKey and the slug do with them is RECORDED
 *            (L8), so a change shows. ß æ œ are census-discovery §66.9 owner
 *            question 4 and are not decided here.
 *
 * MUTATIONS (census-discovery §73), each run and restored byte-identically:
 * delete one line of hook/bar letters from LATIN_LETTER_FOLD and L2, L6 and L7
 * go red; make strokeFold stop decomposing and L2, L3 and L5 go red; make
 * trailLetterFold stop decomposing and L3 goes red (ǽ).
 */
import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { searchKey, STROKE_FOLD } from "../lib/canonicalLocations.js";
import { canonicalTrailSlug, canonicaliseTrailProposal } from "../lib/discoveryTrailObject.js";
import { trailDestinationKey } from "../lib/discoveryTrailFold.js";

type Kind = "fold" | "as" | "outside";
/** [letter, UnicodeData 17.0 name, kind, spelling (fold) | the letter X (as) | "" (outside)] */
const LETTERS: ReadonlyArray<readonly [string, string, Kind, string]> = [
  ["ª", "FEMININE ORDINAL INDICATOR", "outside", ""],
  ["º", "MASCULINE ORDINAL INDICATOR", "outside", ""],
  ["Æ", "LATIN CAPITAL LETTER AE", "outside", ""],
  ["Ð", "LATIN CAPITAL LETTER ETH", "fold", "d"],
  ["Ø", "LATIN CAPITAL LETTER O WITH STROKE", "fold", "o"],
  ["Þ", "LATIN CAPITAL LETTER THORN", "outside", ""],
  ["ß", "LATIN SMALL LETTER SHARP S", "outside", ""],
  ["æ", "LATIN SMALL LETTER AE", "outside", ""],
  ["ð", "LATIN SMALL LETTER ETH", "fold", "d"],
  ["ø", "LATIN SMALL LETTER O WITH STROKE", "fold", "o"],
  ["þ", "LATIN SMALL LETTER THORN", "outside", ""],
  ["Đ", "LATIN CAPITAL LETTER D WITH STROKE", "fold", "d"],
  ["đ", "LATIN SMALL LETTER D WITH STROKE", "fold", "d"],
  ["Ħ", "LATIN CAPITAL LETTER H WITH STROKE", "fold", "h"],
  ["ħ", "LATIN SMALL LETTER H WITH STROKE", "fold", "h"],
  ["ı", "LATIN SMALL LETTER DOTLESS I", "fold", "i"],
  ["Ĳ", "LATIN CAPITAL LIGATURE IJ", "outside", ""],
  ["ĳ", "LATIN SMALL LIGATURE IJ", "outside", ""],
  ["ĸ", "LATIN SMALL LETTER KRA", "outside", ""],
  ["Ŀ", "LATIN CAPITAL LETTER L WITH MIDDLE DOT", "fold", "l·"],
  ["ŀ", "LATIN SMALL LETTER L WITH MIDDLE DOT", "fold", "l·"],
  ["Ł", "LATIN CAPITAL LETTER L WITH STROKE", "fold", "l"],
  ["ł", "LATIN SMALL LETTER L WITH STROKE", "fold", "l"],
  ["ŉ", "LATIN SMALL LETTER N PRECEDED BY APOSTROPHE", "outside", ""],
  ["Ŋ", "LATIN CAPITAL LETTER ENG", "outside", ""],
  ["ŋ", "LATIN SMALL LETTER ENG", "outside", ""],
  ["Œ", "LATIN CAPITAL LIGATURE OE", "outside", ""],
  ["œ", "LATIN SMALL LIGATURE OE", "outside", ""],
  ["Ŧ", "LATIN CAPITAL LETTER T WITH STROKE", "fold", "t"],
  ["ŧ", "LATIN SMALL LETTER T WITH STROKE", "fold", "t"],
  ["ſ", "LATIN SMALL LETTER LONG S", "fold", "s"],
  ["ƀ", "LATIN SMALL LETTER B WITH STROKE", "fold", "b"],
  ["Ɓ", "LATIN CAPITAL LETTER B WITH HOOK", "fold", "b"],
  ["Ƃ", "LATIN CAPITAL LETTER B WITH TOPBAR", "fold", "b"],
  ["ƃ", "LATIN SMALL LETTER B WITH TOPBAR", "fold", "b"],
  ["Ƅ", "LATIN CAPITAL LETTER TONE SIX", "outside", ""],
  ["ƅ", "LATIN SMALL LETTER TONE SIX", "outside", ""],
  ["Ɔ", "LATIN CAPITAL LETTER OPEN O", "outside", ""],
  ["Ƈ", "LATIN CAPITAL LETTER C WITH HOOK", "fold", "c"],
  ["ƈ", "LATIN SMALL LETTER C WITH HOOK", "fold", "c"],
  ["Ɖ", "LATIN CAPITAL LETTER AFRICAN D", "fold", "d"],
  ["Ɗ", "LATIN CAPITAL LETTER D WITH HOOK", "fold", "d"],
  ["Ƌ", "LATIN CAPITAL LETTER D WITH TOPBAR", "fold", "d"],
  ["ƌ", "LATIN SMALL LETTER D WITH TOPBAR", "fold", "d"],
  ["ƍ", "LATIN SMALL LETTER TURNED DELTA", "outside", ""],
  ["Ǝ", "LATIN CAPITAL LETTER REVERSED E", "outside", ""],
  ["Ə", "LATIN CAPITAL LETTER SCHWA", "outside", ""],
  ["Ɛ", "LATIN CAPITAL LETTER OPEN E", "outside", ""],
  ["Ƒ", "LATIN CAPITAL LETTER F WITH HOOK", "fold", "f"],
  ["ƒ", "LATIN SMALL LETTER F WITH HOOK", "fold", "f"],
  ["Ɠ", "LATIN CAPITAL LETTER G WITH HOOK", "fold", "g"],
  ["Ɣ", "LATIN CAPITAL LETTER GAMMA", "outside", ""],
  ["ƕ", "LATIN SMALL LETTER HV", "outside", ""],
  ["Ɩ", "LATIN CAPITAL LETTER IOTA", "outside", ""],
  ["Ɨ", "LATIN CAPITAL LETTER I WITH STROKE", "fold", "i"],
  ["Ƙ", "LATIN CAPITAL LETTER K WITH HOOK", "fold", "k"],
  ["ƙ", "LATIN SMALL LETTER K WITH HOOK", "fold", "k"],
  ["ƚ", "LATIN SMALL LETTER L WITH BAR", "fold", "l"],
  ["ƛ", "LATIN SMALL LETTER LAMBDA WITH STROKE", "as", "ꟛ"],
  ["Ɯ", "LATIN CAPITAL LETTER TURNED M", "outside", ""],
  ["Ɲ", "LATIN CAPITAL LETTER N WITH LEFT HOOK", "fold", "n"],
  ["ƞ", "LATIN SMALL LETTER N WITH LONG RIGHT LEG", "fold", "n"],
  ["Ɵ", "LATIN CAPITAL LETTER O WITH MIDDLE TILDE", "fold", "o"],
  ["Ƣ", "LATIN CAPITAL LETTER OI", "outside", ""],
  ["ƣ", "LATIN SMALL LETTER OI", "outside", ""],
  ["Ƥ", "LATIN CAPITAL LETTER P WITH HOOK", "fold", "p"],
  ["ƥ", "LATIN SMALL LETTER P WITH HOOK", "fold", "p"],
  ["Ʀ", "LATIN LETTER YR", "outside", ""],
  ["Ƨ", "LATIN CAPITAL LETTER TONE TWO", "outside", ""],
  ["ƨ", "LATIN SMALL LETTER TONE TWO", "outside", ""],
  ["Ʃ", "LATIN CAPITAL LETTER ESH", "outside", ""],
  ["ƪ", "LATIN LETTER REVERSED ESH LOOP", "outside", ""],
  ["ƫ", "LATIN SMALL LETTER T WITH PALATAL HOOK", "fold", "t"],
  ["Ƭ", "LATIN CAPITAL LETTER T WITH HOOK", "fold", "t"],
  ["ƭ", "LATIN SMALL LETTER T WITH HOOK", "fold", "t"],
  ["Ʈ", "LATIN CAPITAL LETTER T WITH RETROFLEX HOOK", "fold", "t"],
  ["Ʊ", "LATIN CAPITAL LETTER UPSILON", "outside", ""],
  ["Ʋ", "LATIN CAPITAL LETTER V WITH HOOK", "fold", "v"],
  ["Ƴ", "LATIN CAPITAL LETTER Y WITH HOOK", "fold", "y"],
  ["ƴ", "LATIN SMALL LETTER Y WITH HOOK", "fold", "y"],
  ["Ƶ", "LATIN CAPITAL LETTER Z WITH STROKE", "fold", "z"],
  ["ƶ", "LATIN SMALL LETTER Z WITH STROKE", "fold", "z"],
  ["Ʒ", "LATIN CAPITAL LETTER EZH", "outside", ""],
  ["Ƹ", "LATIN CAPITAL LETTER EZH REVERSED", "outside", ""],
  ["ƹ", "LATIN SMALL LETTER EZH REVERSED", "outside", ""],
  ["ƺ", "LATIN SMALL LETTER EZH WITH TAIL", "as", "ʒ"],
  ["ƻ", "LATIN LETTER TWO WITH STROKE", "outside", ""],
  ["Ƽ", "LATIN CAPITAL LETTER TONE FIVE", "outside", ""],
  ["ƽ", "LATIN SMALL LETTER TONE FIVE", "outside", ""],
  ["ƾ", "LATIN LETTER INVERTED GLOTTAL STOP WITH STROKE", "as", "ʖ"],
  ["ƿ", "LATIN LETTER WYNN", "outside", ""],
  ["ǀ", "LATIN LETTER DENTAL CLICK", "outside", ""],
  ["ǁ", "LATIN LETTER LATERAL CLICK", "outside", ""],
  ["ǂ", "LATIN LETTER ALVEOLAR CLICK", "outside", ""],
  ["ǃ", "LATIN LETTER RETROFLEX CLICK", "outside", ""],
  ["Ǆ", "LATIN CAPITAL LETTER DZ WITH CARON", "as", "Ǳ"],
  ["ǅ", "LATIN CAPITAL LETTER D WITH SMALL LETTER Z WITH CARON", "as", "Ǆ"],
  ["ǆ", "LATIN SMALL LETTER DZ WITH CARON", "as", "ǳ"],
  ["Ǉ", "LATIN CAPITAL LETTER LJ", "outside", ""],
  ["ǈ", "LATIN CAPITAL LETTER L WITH SMALL LETTER J", "as", "Ǉ"],
  ["ǉ", "LATIN SMALL LETTER LJ", "outside", ""],
  ["Ǌ", "LATIN CAPITAL LETTER NJ", "outside", ""],
  ["ǋ", "LATIN CAPITAL LETTER N WITH SMALL LETTER J", "as", "Ǌ"],
  ["ǌ", "LATIN SMALL LETTER NJ", "outside", ""],
  ["ǝ", "LATIN SMALL LETTER TURNED E", "outside", ""],
  ["Ǣ", "LATIN CAPITAL LETTER AE WITH MACRON", "as", "Æ"],
  ["ǣ", "LATIN SMALL LETTER AE WITH MACRON", "as", "æ"],
  ["Ǥ", "LATIN CAPITAL LETTER G WITH STROKE", "fold", "g"],
  ["ǥ", "LATIN SMALL LETTER G WITH STROKE", "fold", "g"],
  ["Ǯ", "LATIN CAPITAL LETTER EZH WITH CARON", "as", "Ʒ"],
  ["ǯ", "LATIN SMALL LETTER EZH WITH CARON", "as", "ʒ"],
  ["Ǳ", "LATIN CAPITAL LETTER DZ", "outside", ""],
  ["ǲ", "LATIN CAPITAL LETTER D WITH SMALL LETTER Z", "as", "Ǳ"],
  ["ǳ", "LATIN SMALL LETTER DZ", "outside", ""],
  ["Ƕ", "LATIN CAPITAL LETTER HWAIR", "outside", ""],
  ["Ƿ", "LATIN CAPITAL LETTER WYNN", "outside", ""],
  ["Ǽ", "LATIN CAPITAL LETTER AE WITH ACUTE", "as", "Æ"],
  ["ǽ", "LATIN SMALL LETTER AE WITH ACUTE", "as", "æ"],
  ["Ǿ", "LATIN CAPITAL LETTER O WITH STROKE AND ACUTE", "fold", "o"],
  ["ǿ", "LATIN SMALL LETTER O WITH STROKE AND ACUTE", "fold", "o"],
  ["Ȝ", "LATIN CAPITAL LETTER YOGH", "outside", ""],
  ["ȝ", "LATIN SMALL LETTER YOGH", "outside", ""],
  ["Ƞ", "LATIN CAPITAL LETTER N WITH LONG RIGHT LEG", "fold", "n"],
  ["ȡ", "LATIN SMALL LETTER D WITH CURL", "fold", "d"],
  ["Ȣ", "LATIN CAPITAL LETTER OU", "outside", ""],
  ["ȣ", "LATIN SMALL LETTER OU", "outside", ""],
  ["Ȥ", "LATIN CAPITAL LETTER Z WITH HOOK", "fold", "z"],
  ["ȥ", "LATIN SMALL LETTER Z WITH HOOK", "fold", "z"],
  ["ȴ", "LATIN SMALL LETTER L WITH CURL", "fold", "l"],
  ["ȵ", "LATIN SMALL LETTER N WITH CURL", "fold", "n"],
  ["ȶ", "LATIN SMALL LETTER T WITH CURL", "fold", "t"],
  ["ȷ", "LATIN SMALL LETTER DOTLESS J", "outside", ""],
  ["ȸ", "LATIN SMALL LETTER DB DIGRAPH", "outside", ""],
  ["ȹ", "LATIN SMALL LETTER QP DIGRAPH", "outside", ""],
  ["Ⱥ", "LATIN CAPITAL LETTER A WITH STROKE", "fold", "a"],
  ["Ȼ", "LATIN CAPITAL LETTER C WITH STROKE", "fold", "c"],
  ["ȼ", "LATIN SMALL LETTER C WITH STROKE", "fold", "c"],
  ["Ƚ", "LATIN CAPITAL LETTER L WITH BAR", "fold", "l"],
  ["Ⱦ", "LATIN CAPITAL LETTER T WITH DIAGONAL STROKE", "fold", "t"],
  ["ȿ", "LATIN SMALL LETTER S WITH SWASH TAIL", "fold", "s"],
  ["ɀ", "LATIN SMALL LETTER Z WITH SWASH TAIL", "fold", "z"],
  ["Ɂ", "LATIN CAPITAL LETTER GLOTTAL STOP", "outside", ""],
  ["ɂ", "LATIN SMALL LETTER GLOTTAL STOP", "outside", ""],
  ["Ƀ", "LATIN CAPITAL LETTER B WITH STROKE", "fold", "b"],
  ["Ʉ", "LATIN CAPITAL LETTER U BAR", "fold", "u"],
  ["Ʌ", "LATIN CAPITAL LETTER TURNED V", "outside", ""],
  ["Ɇ", "LATIN CAPITAL LETTER E WITH STROKE", "fold", "e"],
  ["ɇ", "LATIN SMALL LETTER E WITH STROKE", "fold", "e"],
  ["Ɉ", "LATIN CAPITAL LETTER J WITH STROKE", "fold", "j"],
  ["ɉ", "LATIN SMALL LETTER J WITH STROKE", "fold", "j"],
  ["Ɋ", "LATIN CAPITAL LETTER SMALL Q WITH HOOK TAIL", "fold", "q"],
  ["ɋ", "LATIN SMALL LETTER Q WITH HOOK TAIL", "fold", "q"],
  ["Ɍ", "LATIN CAPITAL LETTER R WITH STROKE", "fold", "r"],
  ["ɍ", "LATIN SMALL LETTER R WITH STROKE", "fold", "r"],
  ["Ɏ", "LATIN CAPITAL LETTER Y WITH STROKE", "fold", "y"],
  ["ɏ", "LATIN SMALL LETTER Y WITH STROKE", "fold", "y"],
  ["ɐ", "LATIN SMALL LETTER TURNED A", "outside", ""],
  ["ɑ", "LATIN SMALL LETTER ALPHA", "outside", ""],
  ["ɒ", "LATIN SMALL LETTER TURNED ALPHA", "outside", ""],
  ["ɓ", "LATIN SMALL LETTER B WITH HOOK", "fold", "b"],
  ["ɔ", "LATIN SMALL LETTER OPEN O", "outside", ""],
  ["ɕ", "LATIN SMALL LETTER C WITH CURL", "fold", "c"],
  ["ɖ", "LATIN SMALL LETTER D WITH TAIL", "fold", "d"],
  ["ɗ", "LATIN SMALL LETTER D WITH HOOK", "fold", "d"],
  ["ɘ", "LATIN SMALL LETTER REVERSED E", "outside", ""],
  ["ə", "LATIN SMALL LETTER SCHWA", "outside", ""],
  ["ɚ", "LATIN SMALL LETTER SCHWA WITH HOOK", "as", "ə"],
  ["ɛ", "LATIN SMALL LETTER OPEN E", "outside", ""],
  ["ɜ", "LATIN SMALL LETTER REVERSED OPEN E", "outside", ""],
  ["ɝ", "LATIN SMALL LETTER REVERSED OPEN E WITH HOOK", "as", "ɜ"],
  ["ɞ", "LATIN SMALL LETTER CLOSED REVERSED OPEN E", "outside", ""],
  ["ɟ", "LATIN SMALL LETTER DOTLESS J WITH STROKE", "as", "ȷ"],
  ["ɠ", "LATIN SMALL LETTER G WITH HOOK", "fold", "g"],
  ["ɡ", "LATIN SMALL LETTER SCRIPT G", "outside", ""],
  ["ɢ", "LATIN LETTER SMALL CAPITAL G", "outside", ""],
  ["ɣ", "LATIN SMALL LETTER GAMMA", "outside", ""],
  ["ɤ", "LATIN SMALL LETTER RAMS HORN", "outside", ""],
  ["ɥ", "LATIN SMALL LETTER TURNED H", "outside", ""],
  ["ɦ", "LATIN SMALL LETTER H WITH HOOK", "fold", "h"],
  ["ɧ", "LATIN SMALL LETTER HENG WITH HOOK", "as", "ꜧ"],
  ["ɨ", "LATIN SMALL LETTER I WITH STROKE", "fold", "i"],
  ["ɩ", "LATIN SMALL LETTER IOTA", "outside", ""],
  ["ɪ", "LATIN LETTER SMALL CAPITAL I", "outside", ""],
  ["ɫ", "LATIN SMALL LETTER L WITH MIDDLE TILDE", "fold", "l"],
  ["ɬ", "LATIN SMALL LETTER L WITH BELT", "fold", "l"],
  ["ɭ", "LATIN SMALL LETTER L WITH RETROFLEX HOOK", "fold", "l"],
  ["ɮ", "LATIN SMALL LETTER LEZH", "outside", ""],
  ["ɯ", "LATIN SMALL LETTER TURNED M", "outside", ""],
  ["ɰ", "LATIN SMALL LETTER TURNED M WITH LONG LEG", "as", "ɯ"],
  ["ɱ", "LATIN SMALL LETTER M WITH HOOK", "fold", "m"],
  ["ɲ", "LATIN SMALL LETTER N WITH LEFT HOOK", "fold", "n"],
  ["ɳ", "LATIN SMALL LETTER N WITH RETROFLEX HOOK", "fold", "n"],
  ["ɴ", "LATIN LETTER SMALL CAPITAL N", "outside", ""],
  ["ɵ", "LATIN SMALL LETTER BARRED O", "fold", "o"],
  ["ɶ", "LATIN LETTER SMALL CAPITAL OE", "outside", ""],
  ["ɷ", "LATIN SMALL LETTER CLOSED OMEGA", "outside", ""],
  ["ɸ", "LATIN SMALL LETTER PHI", "outside", ""],
  ["ɹ", "LATIN SMALL LETTER TURNED R", "outside", ""],
  ["ɺ", "LATIN SMALL LETTER TURNED R WITH LONG LEG", "as", "ɹ"],
  ["ɻ", "LATIN SMALL LETTER TURNED R WITH HOOK", "as", "ɹ"],
  ["ɼ", "LATIN SMALL LETTER R WITH LONG LEG", "fold", "r"],
  ["ɽ", "LATIN SMALL LETTER R WITH TAIL", "fold", "r"],
  ["ɾ", "LATIN SMALL LETTER R WITH FISHHOOK", "fold", "r"],
  ["ɿ", "LATIN SMALL LETTER REVERSED R WITH FISHHOOK", "outside", ""],
  ["ʀ", "LATIN LETTER SMALL CAPITAL R", "outside", ""],
  ["ʁ", "LATIN LETTER SMALL CAPITAL INVERTED R", "outside", ""],
  ["ʂ", "LATIN SMALL LETTER S WITH HOOK", "fold", "s"],
  ["ʃ", "LATIN SMALL LETTER ESH", "outside", ""],
  ["ʄ", "LATIN SMALL LETTER DOTLESS J WITH STROKE AND HOOK", "as", "ȷ"],
  ["ʅ", "LATIN SMALL LETTER SQUAT REVERSED ESH", "outside", ""],
  ["ʆ", "LATIN SMALL LETTER ESH WITH CURL", "as", "ʃ"],
  ["ʇ", "LATIN SMALL LETTER TURNED T", "outside", ""],
  ["ʈ", "LATIN SMALL LETTER T WITH RETROFLEX HOOK", "fold", "t"],
  ["ʉ", "LATIN SMALL LETTER U BAR", "fold", "u"],
  ["ʊ", "LATIN SMALL LETTER UPSILON", "outside", ""],
  ["ʋ", "LATIN SMALL LETTER V WITH HOOK", "fold", "v"],
  ["ʌ", "LATIN SMALL LETTER TURNED V", "outside", ""],
  ["ʍ", "LATIN SMALL LETTER TURNED W", "outside", ""],
  ["ʎ", "LATIN SMALL LETTER TURNED Y", "outside", ""],
  ["ʏ", "LATIN LETTER SMALL CAPITAL Y", "outside", ""],
  ["ʐ", "LATIN SMALL LETTER Z WITH RETROFLEX HOOK", "fold", "z"],
  ["ʑ", "LATIN SMALL LETTER Z WITH CURL", "fold", "z"],
  ["ʒ", "LATIN SMALL LETTER EZH", "outside", ""],
  ["ʓ", "LATIN SMALL LETTER EZH WITH CURL", "as", "ʒ"],
  ["ʔ", "LATIN LETTER GLOTTAL STOP", "outside", ""],
  ["ʕ", "LATIN LETTER PHARYNGEAL VOICED FRICATIVE", "outside", ""],
  ["ʖ", "LATIN LETTER INVERTED GLOTTAL STOP", "outside", ""],
  ["ʗ", "LATIN LETTER STRETCHED C", "outside", ""],
  ["ʘ", "LATIN LETTER BILABIAL CLICK", "outside", ""],
  ["ʙ", "LATIN LETTER SMALL CAPITAL B", "outside", ""],
  ["ʚ", "LATIN SMALL LETTER CLOSED OPEN E", "outside", ""],
  ["ʛ", "LATIN LETTER SMALL CAPITAL G WITH HOOK", "as", "ɢ"],
  ["ʜ", "LATIN LETTER SMALL CAPITAL H", "outside", ""],
  ["ʝ", "LATIN SMALL LETTER J WITH CROSSED-TAIL", "fold", "j"],
  ["ʞ", "LATIN SMALL LETTER TURNED K", "outside", ""],
  ["ʟ", "LATIN LETTER SMALL CAPITAL L", "outside", ""],
  ["ʠ", "LATIN SMALL LETTER Q WITH HOOK", "fold", "q"],
  ["ʡ", "LATIN LETTER GLOTTAL STOP WITH STROKE", "as", "ɂ"],
  ["ʢ", "LATIN LETTER REVERSED GLOTTAL STOP WITH STROKE", "outside", ""],
  ["ʣ", "LATIN SMALL LETTER DZ DIGRAPH", "outside", ""],
  ["ʤ", "LATIN SMALL LETTER DEZH DIGRAPH", "outside", ""],
  ["ʥ", "LATIN SMALL LETTER DZ DIGRAPH WITH CURL", "as", "ʣ"],
  ["ʦ", "LATIN SMALL LETTER TS DIGRAPH", "outside", ""],
  ["ʧ", "LATIN SMALL LETTER TESH DIGRAPH", "outside", ""],
  ["ʨ", "LATIN SMALL LETTER TC DIGRAPH WITH CURL", "outside", ""],
  ["ʩ", "LATIN SMALL LETTER FENG DIGRAPH", "outside", ""],
  ["ʪ", "LATIN SMALL LETTER LS DIGRAPH", "outside", ""],
  ["ʫ", "LATIN SMALL LETTER LZ DIGRAPH", "outside", ""],
  ["ʬ", "LATIN LETTER BILABIAL PERCUSSIVE", "outside", ""],
  ["ʭ", "LATIN LETTER BIDENTAL PERCUSSIVE", "outside", ""],
  ["ʮ", "LATIN SMALL LETTER TURNED H WITH FISHHOOK", "as", "ɥ"],
  ["ʯ", "LATIN SMALL LETTER TURNED H WITH FISHHOOK AND TAIL", "as", "ɥ"],
  ["ʰ", "MODIFIER LETTER SMALL H", "outside", ""],
  ["ʱ", "MODIFIER LETTER SMALL H WITH HOOK", "outside", ""],
  ["ʲ", "MODIFIER LETTER SMALL J", "outside", ""],
  ["ʳ", "MODIFIER LETTER SMALL R", "outside", ""],
  ["ʴ", "MODIFIER LETTER SMALL TURNED R", "outside", ""],
  ["ʵ", "MODIFIER LETTER SMALL TURNED R WITH HOOK", "outside", ""],
  ["ʶ", "MODIFIER LETTER SMALL CAPITAL INVERTED R", "outside", ""],
  ["ʷ", "MODIFIER LETTER SMALL W", "outside", ""],
  ["ʸ", "MODIFIER LETTER SMALL Y", "outside", ""],
  ["ˠ", "MODIFIER LETTER SMALL GAMMA", "outside", ""],
  ["ˡ", "MODIFIER LETTER SMALL L", "outside", ""],
  ["ˢ", "MODIFIER LETTER SMALL S", "outside", ""],
  ["ˣ", "MODIFIER LETTER SMALL X", "outside", ""],
  ["ˤ", "MODIFIER LETTER SMALL REVERSED GLOTTAL STOP", "outside", ""],
  ["ᴀ", "LATIN LETTER SMALL CAPITAL A", "outside", ""],
  ["ᴁ", "LATIN LETTER SMALL CAPITAL AE", "outside", ""],
  ["ᴂ", "LATIN SMALL LETTER TURNED AE", "outside", ""],
  ["ᴃ", "LATIN LETTER SMALL CAPITAL BARRED B", "as", "ʙ"],
  ["ᴄ", "LATIN LETTER SMALL CAPITAL C", "outside", ""],
  ["ᴅ", "LATIN LETTER SMALL CAPITAL D", "outside", ""],
  ["ᴆ", "LATIN LETTER SMALL CAPITAL ETH", "outside", ""],
  ["ᴇ", "LATIN LETTER SMALL CAPITAL E", "outside", ""],
  ["ᴈ", "LATIN SMALL LETTER TURNED OPEN E", "outside", ""],
  ["ᴉ", "LATIN SMALL LETTER TURNED I", "outside", ""],
  ["ᴊ", "LATIN LETTER SMALL CAPITAL J", "outside", ""],
  ["ᴋ", "LATIN LETTER SMALL CAPITAL K", "outside", ""],
  ["ᴌ", "LATIN LETTER SMALL CAPITAL L WITH STROKE", "as", "ʟ"],
  ["ᴍ", "LATIN LETTER SMALL CAPITAL M", "outside", ""],
  ["ᴎ", "LATIN LETTER SMALL CAPITAL REVERSED N", "outside", ""],
  ["ᴏ", "LATIN LETTER SMALL CAPITAL O", "outside", ""],
  ["ᴐ", "LATIN LETTER SMALL CAPITAL OPEN O", "outside", ""],
  ["ᴑ", "LATIN SMALL LETTER SIDEWAYS O", "outside", ""],
  ["ᴒ", "LATIN SMALL LETTER SIDEWAYS OPEN O", "outside", ""],
  ["ᴓ", "LATIN SMALL LETTER SIDEWAYS O WITH STROKE", "as", "ᴑ"],
  ["ᴔ", "LATIN SMALL LETTER TURNED OE", "outside", ""],
  ["ᴕ", "LATIN LETTER SMALL CAPITAL OU", "outside", ""],
  ["ᴖ", "LATIN SMALL LETTER TOP HALF O", "outside", ""],
  ["ᴗ", "LATIN SMALL LETTER BOTTOM HALF O", "outside", ""],
  ["ᴘ", "LATIN LETTER SMALL CAPITAL P", "outside", ""],
  ["ᴙ", "LATIN LETTER SMALL CAPITAL REVERSED R", "outside", ""],
  ["ᴚ", "LATIN LETTER SMALL CAPITAL TURNED R", "outside", ""],
  ["ᴛ", "LATIN LETTER SMALL CAPITAL T", "outside", ""],
  ["ᴜ", "LATIN LETTER SMALL CAPITAL U", "outside", ""],
  ["ᴝ", "LATIN SMALL LETTER SIDEWAYS U", "outside", ""],
  ["ᴞ", "LATIN SMALL LETTER SIDEWAYS DIAERESIZED U", "outside", ""],
  ["ᴟ", "LATIN SMALL LETTER SIDEWAYS TURNED M", "outside", ""],
  ["ᴠ", "LATIN LETTER SMALL CAPITAL V", "outside", ""],
  ["ᴡ", "LATIN LETTER SMALL CAPITAL W", "outside", ""],
  ["ᴢ", "LATIN LETTER SMALL CAPITAL Z", "outside", ""],
  ["ᴣ", "LATIN LETTER SMALL CAPITAL EZH", "outside", ""],
  ["ᴤ", "LATIN LETTER VOICED LARYNGEAL SPIRANT", "outside", ""],
  ["ᴥ", "LATIN LETTER AIN", "outside", ""],
  ["ᴬ", "MODIFIER LETTER CAPITAL A", "outside", ""],
  ["ᴭ", "MODIFIER LETTER CAPITAL AE", "outside", ""],
  ["ᴮ", "MODIFIER LETTER CAPITAL B", "outside", ""],
  ["ᴯ", "MODIFIER LETTER CAPITAL BARRED B", "outside", ""],
  ["ᴰ", "MODIFIER LETTER CAPITAL D", "outside", ""],
  ["ᴱ", "MODIFIER LETTER CAPITAL E", "outside", ""],
  ["ᴲ", "MODIFIER LETTER CAPITAL REVERSED E", "outside", ""],
  ["ᴳ", "MODIFIER LETTER CAPITAL G", "outside", ""],
  ["ᴴ", "MODIFIER LETTER CAPITAL H", "outside", ""],
  ["ᴵ", "MODIFIER LETTER CAPITAL I", "outside", ""],
  ["ᴶ", "MODIFIER LETTER CAPITAL J", "outside", ""],
  ["ᴷ", "MODIFIER LETTER CAPITAL K", "outside", ""],
  ["ᴸ", "MODIFIER LETTER CAPITAL L", "outside", ""],
  ["ᴹ", "MODIFIER LETTER CAPITAL M", "outside", ""],
  ["ᴺ", "MODIFIER LETTER CAPITAL N", "outside", ""],
  ["ᴻ", "MODIFIER LETTER CAPITAL REVERSED N", "outside", ""],
  ["ᴼ", "MODIFIER LETTER CAPITAL O", "outside", ""],
  ["ᴽ", "MODIFIER LETTER CAPITAL OU", "outside", ""],
  ["ᴾ", "MODIFIER LETTER CAPITAL P", "outside", ""],
  ["ᴿ", "MODIFIER LETTER CAPITAL R", "outside", ""],
  ["ᵀ", "MODIFIER LETTER CAPITAL T", "outside", ""],
  ["ᵁ", "MODIFIER LETTER CAPITAL U", "outside", ""],
  ["ᵂ", "MODIFIER LETTER CAPITAL W", "outside", ""],
  ["ᵃ", "MODIFIER LETTER SMALL A", "outside", ""],
  ["ᵄ", "MODIFIER LETTER SMALL TURNED A", "outside", ""],
  ["ᵅ", "MODIFIER LETTER SMALL ALPHA", "outside", ""],
  ["ᵆ", "MODIFIER LETTER SMALL TURNED AE", "outside", ""],
  ["ᵇ", "MODIFIER LETTER SMALL B", "outside", ""],
  ["ᵈ", "MODIFIER LETTER SMALL D", "outside", ""],
  ["ᵉ", "MODIFIER LETTER SMALL E", "outside", ""],
  ["ᵊ", "MODIFIER LETTER SMALL SCHWA", "outside", ""],
  ["ᵋ", "MODIFIER LETTER SMALL OPEN E", "outside", ""],
  ["ᵌ", "MODIFIER LETTER SMALL TURNED OPEN E", "outside", ""],
  ["ᵍ", "MODIFIER LETTER SMALL G", "outside", ""],
  ["ᵎ", "MODIFIER LETTER SMALL TURNED I", "outside", ""],
  ["ᵏ", "MODIFIER LETTER SMALL K", "outside", ""],
  ["ᵐ", "MODIFIER LETTER SMALL M", "outside", ""],
  ["ᵑ", "MODIFIER LETTER SMALL ENG", "outside", ""],
  ["ᵒ", "MODIFIER LETTER SMALL O", "outside", ""],
  ["ᵓ", "MODIFIER LETTER SMALL OPEN O", "outside", ""],
  ["ᵔ", "MODIFIER LETTER SMALL TOP HALF O", "outside", ""],
  ["ᵕ", "MODIFIER LETTER SMALL BOTTOM HALF O", "outside", ""],
  ["ᵖ", "MODIFIER LETTER SMALL P", "outside", ""],
  ["ᵗ", "MODIFIER LETTER SMALL T", "outside", ""],
  ["ᵘ", "MODIFIER LETTER SMALL U", "outside", ""],
  ["ᵙ", "MODIFIER LETTER SMALL SIDEWAYS U", "outside", ""],
  ["ᵚ", "MODIFIER LETTER SMALL TURNED M", "outside", ""],
  ["ᵛ", "MODIFIER LETTER SMALL V", "outside", ""],
  ["ᵜ", "MODIFIER LETTER SMALL AIN", "outside", ""],
  ["ᵢ", "LATIN SUBSCRIPT SMALL LETTER I", "outside", ""],
  ["ᵣ", "LATIN SUBSCRIPT SMALL LETTER R", "outside", ""],
  ["ᵤ", "LATIN SUBSCRIPT SMALL LETTER U", "outside", ""],
  ["ᵥ", "LATIN SUBSCRIPT SMALL LETTER V", "outside", ""],
  ["ᵫ", "LATIN SMALL LETTER UE", "outside", ""],
  ["ᵬ", "LATIN SMALL LETTER B WITH MIDDLE TILDE", "fold", "b"],
  ["ᵭ", "LATIN SMALL LETTER D WITH MIDDLE TILDE", "fold", "d"],
  ["ᵮ", "LATIN SMALL LETTER F WITH MIDDLE TILDE", "fold", "f"],
  ["ᵯ", "LATIN SMALL LETTER M WITH MIDDLE TILDE", "fold", "m"],
  ["ᵰ", "LATIN SMALL LETTER N WITH MIDDLE TILDE", "fold", "n"],
  ["ᵱ", "LATIN SMALL LETTER P WITH MIDDLE TILDE", "fold", "p"],
  ["ᵲ", "LATIN SMALL LETTER R WITH MIDDLE TILDE", "fold", "r"],
  ["ᵳ", "LATIN SMALL LETTER R WITH FISHHOOK AND MIDDLE TILDE", "fold", "r"],
  ["ᵴ", "LATIN SMALL LETTER S WITH MIDDLE TILDE", "fold", "s"],
  ["ᵵ", "LATIN SMALL LETTER T WITH MIDDLE TILDE", "fold", "t"],
  ["ᵶ", "LATIN SMALL LETTER Z WITH MIDDLE TILDE", "fold", "z"],
  ["ᵷ", "LATIN SMALL LETTER TURNED G", "outside", ""],
  ["ᵹ", "LATIN SMALL LETTER INSULAR G", "outside", ""],
  ["ᵺ", "LATIN SMALL LETTER TH WITH STRIKETHROUGH", "fold", "th"],
  ["ᵻ", "LATIN SMALL CAPITAL LETTER I WITH STROKE", "as", "ɪ"],
  ["ᵼ", "LATIN SMALL LETTER IOTA WITH STROKE", "as", "ɩ"],
  ["ᵽ", "LATIN SMALL LETTER P WITH STROKE", "fold", "p"],
  ["ᵾ", "LATIN SMALL CAPITAL LETTER U WITH STROKE", "as", "ᴜ"],
  ["ᵿ", "LATIN SMALL LETTER UPSILON WITH STROKE", "as", "ʊ"],
  ["ᶀ", "LATIN SMALL LETTER B WITH PALATAL HOOK", "fold", "b"],
  ["ᶁ", "LATIN SMALL LETTER D WITH PALATAL HOOK", "fold", "d"],
  ["ᶂ", "LATIN SMALL LETTER F WITH PALATAL HOOK", "fold", "f"],
  ["ᶃ", "LATIN SMALL LETTER G WITH PALATAL HOOK", "fold", "g"],
  ["ᶄ", "LATIN SMALL LETTER K WITH PALATAL HOOK", "fold", "k"],
  ["ᶅ", "LATIN SMALL LETTER L WITH PALATAL HOOK", "fold", "l"],
  ["ᶆ", "LATIN SMALL LETTER M WITH PALATAL HOOK", "fold", "m"],
  ["ᶇ", "LATIN SMALL LETTER N WITH PALATAL HOOK", "fold", "n"],
  ["ᶈ", "LATIN SMALL LETTER P WITH PALATAL HOOK", "fold", "p"],
  ["ᶉ", "LATIN SMALL LETTER R WITH PALATAL HOOK", "fold", "r"],
  ["ᶊ", "LATIN SMALL LETTER S WITH PALATAL HOOK", "fold", "s"],
  ["ᶋ", "LATIN SMALL LETTER ESH WITH PALATAL HOOK", "as", "ʃ"],
  ["ᶌ", "LATIN SMALL LETTER V WITH PALATAL HOOK", "fold", "v"],
  ["ᶍ", "LATIN SMALL LETTER X WITH PALATAL HOOK", "fold", "x"],
  ["ᶎ", "LATIN SMALL LETTER Z WITH PALATAL HOOK", "fold", "z"],
  ["ᶏ", "LATIN SMALL LETTER A WITH RETROFLEX HOOK", "fold", "a"],
  ["ᶐ", "LATIN SMALL LETTER ALPHA WITH RETROFLEX HOOK", "as", "ɑ"],
  ["ᶑ", "LATIN SMALL LETTER D WITH HOOK AND TAIL", "fold", "d"],
  ["ᶒ", "LATIN SMALL LETTER E WITH RETROFLEX HOOK", "fold", "e"],
  ["ᶓ", "LATIN SMALL LETTER OPEN E WITH RETROFLEX HOOK", "as", "ɛ"],
  ["ᶔ", "LATIN SMALL LETTER REVERSED OPEN E WITH RETROFLEX HOOK", "as", "ɜ"],
  ["ᶕ", "LATIN SMALL LETTER SCHWA WITH RETROFLEX HOOK", "as", "ə"],
  ["ᶖ", "LATIN SMALL LETTER I WITH RETROFLEX HOOK", "fold", "i"],
  ["ᶗ", "LATIN SMALL LETTER OPEN O WITH RETROFLEX HOOK", "as", "ɔ"],
  ["ᶘ", "LATIN SMALL LETTER ESH WITH RETROFLEX HOOK", "as", "ʃ"],
  ["ᶙ", "LATIN SMALL LETTER U WITH RETROFLEX HOOK", "fold", "u"],
  ["ᶚ", "LATIN SMALL LETTER EZH WITH RETROFLEX HOOK", "as", "ʒ"],
  ["ᶛ", "MODIFIER LETTER SMALL TURNED ALPHA", "outside", ""],
  ["ᶜ", "MODIFIER LETTER SMALL C", "outside", ""],
  ["ᶝ", "MODIFIER LETTER SMALL C WITH CURL", "outside", ""],
  ["ᶞ", "MODIFIER LETTER SMALL ETH", "outside", ""],
  ["ᶟ", "MODIFIER LETTER SMALL REVERSED OPEN E", "outside", ""],
  ["ᶠ", "MODIFIER LETTER SMALL F", "outside", ""],
  ["ᶡ", "MODIFIER LETTER SMALL DOTLESS J WITH STROKE", "outside", ""],
  ["ᶢ", "MODIFIER LETTER SMALL SCRIPT G", "outside", ""],
  ["ᶣ", "MODIFIER LETTER SMALL TURNED H", "outside", ""],
  ["ᶤ", "MODIFIER LETTER SMALL I WITH STROKE", "outside", ""],
  ["ᶥ", "MODIFIER LETTER SMALL IOTA", "outside", ""],
  ["ᶦ", "MODIFIER LETTER SMALL CAPITAL I", "outside", ""],
  ["ᶧ", "MODIFIER LETTER SMALL CAPITAL I WITH STROKE", "outside", ""],
  ["ᶨ", "MODIFIER LETTER SMALL J WITH CROSSED-TAIL", "outside", ""],
  ["ᶩ", "MODIFIER LETTER SMALL L WITH RETROFLEX HOOK", "outside", ""],
  ["ᶪ", "MODIFIER LETTER SMALL L WITH PALATAL HOOK", "outside", ""],
  ["ᶫ", "MODIFIER LETTER SMALL CAPITAL L", "outside", ""],
  ["ᶬ", "MODIFIER LETTER SMALL M WITH HOOK", "outside", ""],
  ["ᶭ", "MODIFIER LETTER SMALL TURNED M WITH LONG LEG", "outside", ""],
  ["ᶮ", "MODIFIER LETTER SMALL N WITH LEFT HOOK", "outside", ""],
  ["ᶯ", "MODIFIER LETTER SMALL N WITH RETROFLEX HOOK", "outside", ""],
  ["ᶰ", "MODIFIER LETTER SMALL CAPITAL N", "outside", ""],
  ["ᶱ", "MODIFIER LETTER SMALL BARRED O", "outside", ""],
  ["ᶲ", "MODIFIER LETTER SMALL PHI", "outside", ""],
  ["ᶳ", "MODIFIER LETTER SMALL S WITH HOOK", "outside", ""],
  ["ᶴ", "MODIFIER LETTER SMALL ESH", "outside", ""],
  ["ᶵ", "MODIFIER LETTER SMALL T WITH PALATAL HOOK", "outside", ""],
  ["ᶶ", "MODIFIER LETTER SMALL U BAR", "outside", ""],
  ["ᶷ", "MODIFIER LETTER SMALL UPSILON", "outside", ""],
  ["ᶸ", "MODIFIER LETTER SMALL CAPITAL U", "outside", ""],
  ["ᶹ", "MODIFIER LETTER SMALL V WITH HOOK", "outside", ""],
  ["ᶺ", "MODIFIER LETTER SMALL TURNED V", "outside", ""],
  ["ᶻ", "MODIFIER LETTER SMALL Z", "outside", ""],
  ["ᶼ", "MODIFIER LETTER SMALL Z WITH RETROFLEX HOOK", "outside", ""],
  ["ᶽ", "MODIFIER LETTER SMALL Z WITH CURL", "outside", ""],
  ["ᶾ", "MODIFIER LETTER SMALL EZH", "outside", ""],
  ["ẚ", "LATIN SMALL LETTER A WITH RIGHT HALF RING", "fold", "aʾ"],
  ["ẛ", "LATIN SMALL LETTER LONG S WITH DOT ABOVE", "as", "ſ"],
  ["ẜ", "LATIN SMALL LETTER LONG S WITH DIAGONAL STROKE", "as", "ſ"],
  ["ẝ", "LATIN SMALL LETTER LONG S WITH HIGH STROKE", "as", "ſ"],
  ["ẞ", "LATIN CAPITAL LETTER SHARP S", "outside", ""],
  ["ẟ", "LATIN SMALL LETTER DELTA", "outside", ""],
  ["Ỻ", "LATIN CAPITAL LETTER MIDDLE-WELSH LL", "outside", ""],
  ["ỻ", "LATIN SMALL LETTER MIDDLE-WELSH LL", "outside", ""],
  ["Ỽ", "LATIN CAPITAL LETTER MIDDLE-WELSH V", "outside", ""],
  ["ỽ", "LATIN SMALL LETTER MIDDLE-WELSH V", "outside", ""],
  ["Ỿ", "LATIN CAPITAL LETTER Y WITH LOOP", "fold", "y"],
  ["ỿ", "LATIN SMALL LETTER Y WITH LOOP", "fold", "y"],
  ["ⁱ", "SUPERSCRIPT LATIN SMALL LETTER I", "outside", ""],
  ["ⁿ", "SUPERSCRIPT LATIN SMALL LETTER N", "outside", ""],
  ["ₐ", "LATIN SUBSCRIPT SMALL LETTER A", "outside", ""],
  ["ₑ", "LATIN SUBSCRIPT SMALL LETTER E", "outside", ""],
  ["ₒ", "LATIN SUBSCRIPT SMALL LETTER O", "outside", ""],
  ["ₓ", "LATIN SUBSCRIPT SMALL LETTER X", "outside", ""],
  ["ₔ", "LATIN SUBSCRIPT SMALL LETTER SCHWA", "outside", ""],
  ["ₕ", "LATIN SUBSCRIPT SMALL LETTER H", "outside", ""],
  ["ₖ", "LATIN SUBSCRIPT SMALL LETTER K", "outside", ""],
  ["ₗ", "LATIN SUBSCRIPT SMALL LETTER L", "outside", ""],
  ["ₘ", "LATIN SUBSCRIPT SMALL LETTER M", "outside", ""],
  ["ₙ", "LATIN SUBSCRIPT SMALL LETTER N", "outside", ""],
  ["ₚ", "LATIN SUBSCRIPT SMALL LETTER P", "outside", ""],
  ["ₛ", "LATIN SUBSCRIPT SMALL LETTER S", "outside", ""],
  ["ₜ", "LATIN SUBSCRIPT SMALL LETTER T", "outside", ""],
  ["Ⅎ", "TURNED CAPITAL F", "outside", ""],
  ["ⅎ", "TURNED SMALL F", "outside", ""],
  ["Ↄ", "ROMAN NUMERAL REVERSED ONE HUNDRED", "outside", ""],
  ["ↄ", "LATIN SMALL LETTER REVERSED C", "outside", ""],
  ["Ⱡ", "LATIN CAPITAL LETTER L WITH DOUBLE BAR", "fold", "l"],
  ["ⱡ", "LATIN SMALL LETTER L WITH DOUBLE BAR", "fold", "l"],
  ["Ɫ", "LATIN CAPITAL LETTER L WITH MIDDLE TILDE", "fold", "l"],
  ["Ᵽ", "LATIN CAPITAL LETTER P WITH STROKE", "fold", "p"],
  ["Ɽ", "LATIN CAPITAL LETTER R WITH TAIL", "fold", "r"],
  ["ⱥ", "LATIN SMALL LETTER A WITH STROKE", "fold", "a"],
  ["ⱦ", "LATIN SMALL LETTER T WITH DIAGONAL STROKE", "fold", "t"],
  ["Ⱨ", "LATIN CAPITAL LETTER H WITH DESCENDER", "fold", "h"],
  ["ⱨ", "LATIN SMALL LETTER H WITH DESCENDER", "fold", "h"],
  ["Ⱪ", "LATIN CAPITAL LETTER K WITH DESCENDER", "fold", "k"],
  ["ⱪ", "LATIN SMALL LETTER K WITH DESCENDER", "fold", "k"],
  ["Ⱬ", "LATIN CAPITAL LETTER Z WITH DESCENDER", "fold", "z"],
  ["ⱬ", "LATIN SMALL LETTER Z WITH DESCENDER", "fold", "z"],
  ["Ɑ", "LATIN CAPITAL LETTER ALPHA", "outside", ""],
  ["Ɱ", "LATIN CAPITAL LETTER M WITH HOOK", "fold", "m"],
  ["Ɐ", "LATIN CAPITAL LETTER TURNED A", "outside", ""],
  ["Ɒ", "LATIN CAPITAL LETTER TURNED ALPHA", "outside", ""],
  ["ⱱ", "LATIN SMALL LETTER V WITH RIGHT HOOK", "fold", "v"],
  ["Ⱳ", "LATIN CAPITAL LETTER W WITH HOOK", "fold", "w"],
  ["ⱳ", "LATIN SMALL LETTER W WITH HOOK", "fold", "w"],
  ["ⱴ", "LATIN SMALL LETTER V WITH CURL", "fold", "v"],
  ["Ⱶ", "LATIN CAPITAL LETTER HALF H", "outside", ""],
  ["ⱶ", "LATIN SMALL LETTER HALF H", "outside", ""],
  ["ⱷ", "LATIN SMALL LETTER TAILLESS PHI", "outside", ""],
  ["ⱸ", "LATIN SMALL LETTER E WITH NOTCH", "fold", "e"],
  ["ⱹ", "LATIN SMALL LETTER TURNED R WITH TAIL", "as", "ɹ"],
  ["ⱺ", "LATIN SMALL LETTER O WITH LOW RING INSIDE", "fold", "o"],
  ["ⱻ", "LATIN LETTER SMALL CAPITAL TURNED E", "outside", ""],
  ["ⱼ", "LATIN SUBSCRIPT SMALL LETTER J", "outside", ""],
  ["ⱽ", "MODIFIER LETTER CAPITAL V", "outside", ""],
  ["Ȿ", "LATIN CAPITAL LETTER S WITH SWASH TAIL", "fold", "s"],
  ["Ɀ", "LATIN CAPITAL LETTER Z WITH SWASH TAIL", "fold", "z"],
  ["Ꜣ", "LATIN CAPITAL LETTER EGYPTOLOGICAL ALEF", "outside", ""],
  ["ꜣ", "LATIN SMALL LETTER EGYPTOLOGICAL ALEF", "outside", ""],
  ["Ꜥ", "LATIN CAPITAL LETTER EGYPTOLOGICAL AIN", "outside", ""],
  ["ꜥ", "LATIN SMALL LETTER EGYPTOLOGICAL AIN", "outside", ""],
  ["Ꜧ", "LATIN CAPITAL LETTER HENG", "outside", ""],
  ["ꜧ", "LATIN SMALL LETTER HENG", "outside", ""],
  ["Ꜩ", "LATIN CAPITAL LETTER TZ", "outside", ""],
  ["ꜩ", "LATIN SMALL LETTER TZ", "outside", ""],
  ["Ꜫ", "LATIN CAPITAL LETTER TRESILLO", "outside", ""],
  ["ꜫ", "LATIN SMALL LETTER TRESILLO", "outside", ""],
  ["Ꜭ", "LATIN CAPITAL LETTER CUATRILLO", "outside", ""],
  ["ꜭ", "LATIN SMALL LETTER CUATRILLO", "outside", ""],
  ["Ꜯ", "LATIN CAPITAL LETTER CUATRILLO WITH COMMA", "as", "Ꜭ"],
  ["ꜯ", "LATIN SMALL LETTER CUATRILLO WITH COMMA", "as", "ꜭ"],
  ["ꜰ", "LATIN LETTER SMALL CAPITAL F", "outside", ""],
  ["ꜱ", "LATIN LETTER SMALL CAPITAL S", "outside", ""],
  ["Ꜳ", "LATIN CAPITAL LETTER AA", "outside", ""],
  ["ꜳ", "LATIN SMALL LETTER AA", "outside", ""],
  ["Ꜵ", "LATIN CAPITAL LETTER AO", "outside", ""],
  ["ꜵ", "LATIN SMALL LETTER AO", "outside", ""],
  ["Ꜷ", "LATIN CAPITAL LETTER AU", "outside", ""],
  ["ꜷ", "LATIN SMALL LETTER AU", "outside", ""],
  ["Ꜹ", "LATIN CAPITAL LETTER AV", "outside", ""],
  ["ꜹ", "LATIN SMALL LETTER AV", "outside", ""],
  ["Ꜻ", "LATIN CAPITAL LETTER AV WITH HORIZONTAL BAR", "as", "Ꜹ"],
  ["ꜻ", "LATIN SMALL LETTER AV WITH HORIZONTAL BAR", "as", "ꜹ"],
  ["Ꜽ", "LATIN CAPITAL LETTER AY", "outside", ""],
  ["ꜽ", "LATIN SMALL LETTER AY", "outside", ""],
  ["Ꜿ", "LATIN CAPITAL LETTER REVERSED C WITH DOT", "as", "ↄ"],
  ["ꜿ", "LATIN SMALL LETTER REVERSED C WITH DOT", "as", "ↄ"],
  ["Ꝁ", "LATIN CAPITAL LETTER K WITH STROKE", "fold", "k"],
  ["ꝁ", "LATIN SMALL LETTER K WITH STROKE", "fold", "k"],
  ["Ꝃ", "LATIN CAPITAL LETTER K WITH DIAGONAL STROKE", "fold", "k"],
  ["ꝃ", "LATIN SMALL LETTER K WITH DIAGONAL STROKE", "fold", "k"],
  ["Ꝅ", "LATIN CAPITAL LETTER K WITH STROKE AND DIAGONAL STROKE", "fold", "k"],
  ["ꝅ", "LATIN SMALL LETTER K WITH STROKE AND DIAGONAL STROKE", "fold", "k"],
  ["Ꝇ", "LATIN CAPITAL LETTER BROKEN L", "outside", ""],
  ["ꝇ", "LATIN SMALL LETTER BROKEN L", "outside", ""],
  ["Ꝉ", "LATIN CAPITAL LETTER L WITH HIGH STROKE", "fold", "l"],
  ["ꝉ", "LATIN SMALL LETTER L WITH HIGH STROKE", "fold", "l"],
  ["Ꝋ", "LATIN CAPITAL LETTER O WITH LONG STROKE OVERLAY", "fold", "o"],
  ["ꝋ", "LATIN SMALL LETTER O WITH LONG STROKE OVERLAY", "fold", "o"],
  ["Ꝍ", "LATIN CAPITAL LETTER O WITH LOOP", "fold", "o"],
  ["ꝍ", "LATIN SMALL LETTER O WITH LOOP", "fold", "o"],
  ["Ꝏ", "LATIN CAPITAL LETTER OO", "outside", ""],
  ["ꝏ", "LATIN SMALL LETTER OO", "outside", ""],
  ["Ꝑ", "LATIN CAPITAL LETTER P WITH STROKE THROUGH DESCENDER", "fold", "p"],
  ["ꝑ", "LATIN SMALL LETTER P WITH STROKE THROUGH DESCENDER", "fold", "p"],
  ["Ꝓ", "LATIN CAPITAL LETTER P WITH FLOURISH", "fold", "p"],
  ["ꝓ", "LATIN SMALL LETTER P WITH FLOURISH", "fold", "p"],
  ["Ꝕ", "LATIN CAPITAL LETTER P WITH SQUIRREL TAIL", "fold", "p"],
  ["ꝕ", "LATIN SMALL LETTER P WITH SQUIRREL TAIL", "fold", "p"],
  ["Ꝗ", "LATIN CAPITAL LETTER Q WITH STROKE THROUGH DESCENDER", "fold", "q"],
  ["ꝗ", "LATIN SMALL LETTER Q WITH STROKE THROUGH DESCENDER", "fold", "q"],
  ["Ꝙ", "LATIN CAPITAL LETTER Q WITH DIAGONAL STROKE", "fold", "q"],
  ["ꝙ", "LATIN SMALL LETTER Q WITH DIAGONAL STROKE", "fold", "q"],
  ["Ꝛ", "LATIN CAPITAL LETTER R ROTUNDA", "outside", ""],
  ["ꝛ", "LATIN SMALL LETTER R ROTUNDA", "outside", ""],
  ["Ꝝ", "LATIN CAPITAL LETTER RUM ROTUNDA", "outside", ""],
  ["ꝝ", "LATIN SMALL LETTER RUM ROTUNDA", "outside", ""],
  ["Ꝟ", "LATIN CAPITAL LETTER V WITH DIAGONAL STROKE", "fold", "v"],
  ["ꝟ", "LATIN SMALL LETTER V WITH DIAGONAL STROKE", "fold", "v"],
  ["Ꝡ", "LATIN CAPITAL LETTER VY", "outside", ""],
  ["ꝡ", "LATIN SMALL LETTER VY", "outside", ""],
  ["Ꝣ", "LATIN CAPITAL LETTER VISIGOTHIC Z", "outside", ""],
  ["ꝣ", "LATIN SMALL LETTER VISIGOTHIC Z", "outside", ""],
  ["Ꝥ", "LATIN CAPITAL LETTER THORN WITH STROKE", "as", "Þ"],
  ["ꝥ", "LATIN SMALL LETTER THORN WITH STROKE", "as", "þ"],
  ["Ꝧ", "LATIN CAPITAL LETTER THORN WITH STROKE THROUGH DESCENDER", "as", "Þ"],
  ["ꝧ", "LATIN SMALL LETTER THORN WITH STROKE THROUGH DESCENDER", "as", "þ"],
  ["Ꝩ", "LATIN CAPITAL LETTER VEND", "outside", ""],
  ["ꝩ", "LATIN SMALL LETTER VEND", "outside", ""],
  ["Ꝫ", "LATIN CAPITAL LETTER ET", "outside", ""],
  ["ꝫ", "LATIN SMALL LETTER ET", "outside", ""],
  ["Ꝭ", "LATIN CAPITAL LETTER IS", "outside", ""],
  ["ꝭ", "LATIN SMALL LETTER IS", "outside", ""],
  ["Ꝯ", "LATIN CAPITAL LETTER CON", "outside", ""],
  ["ꝯ", "LATIN SMALL LETTER CON", "outside", ""],
  ["ꝰ", "MODIFIER LETTER US", "outside", ""],
  ["ꝱ", "LATIN SMALL LETTER DUM", "outside", ""],
  ["ꝲ", "LATIN SMALL LETTER LUM", "outside", ""],
  ["ꝳ", "LATIN SMALL LETTER MUM", "outside", ""],
  ["ꝴ", "LATIN SMALL LETTER NUM", "outside", ""],
  ["ꝵ", "LATIN SMALL LETTER RUM", "outside", ""],
  ["ꝶ", "LATIN LETTER SMALL CAPITAL RUM", "outside", ""],
  ["ꝷ", "LATIN SMALL LETTER TUM", "outside", ""],
  ["ꝸ", "LATIN SMALL LETTER UM", "outside", ""],
  ["Ꝺ", "LATIN CAPITAL LETTER INSULAR D", "outside", ""],
  ["ꝺ", "LATIN SMALL LETTER INSULAR D", "outside", ""],
  ["Ꝼ", "LATIN CAPITAL LETTER INSULAR F", "outside", ""],
  ["ꝼ", "LATIN SMALL LETTER INSULAR F", "outside", ""],
  ["Ᵹ", "LATIN CAPITAL LETTER INSULAR G", "outside", ""],
  ["Ꝿ", "LATIN CAPITAL LETTER TURNED INSULAR G", "outside", ""],
  ["ꝿ", "LATIN SMALL LETTER TURNED INSULAR G", "outside", ""],
  ["Ꞁ", "LATIN CAPITAL LETTER TURNED L", "outside", ""],
  ["ꞁ", "LATIN SMALL LETTER TURNED L", "outside", ""],
  ["Ꞃ", "LATIN CAPITAL LETTER INSULAR R", "outside", ""],
  ["ꞃ", "LATIN SMALL LETTER INSULAR R", "outside", ""],
  ["Ꞅ", "LATIN CAPITAL LETTER INSULAR S", "outside", ""],
  ["ꞅ", "LATIN SMALL LETTER INSULAR S", "outside", ""],
  ["Ꞇ", "LATIN CAPITAL LETTER INSULAR T", "outside", ""],
  ["ꞇ", "LATIN SMALL LETTER INSULAR T", "outside", ""],
  ["Ꞌ", "LATIN CAPITAL LETTER SALTILLO", "outside", ""],
  ["ꞌ", "LATIN SMALL LETTER SALTILLO", "outside", ""],
  ["Ɥ", "LATIN CAPITAL LETTER TURNED H", "outside", ""],
  ["ꞎ", "LATIN SMALL LETTER L WITH RETROFLEX HOOK AND BELT", "fold", "l"],
  ["ꞏ", "LATIN LETTER SINOLOGICAL DOT", "outside", ""],
  ["Ꞑ", "LATIN CAPITAL LETTER N WITH DESCENDER", "fold", "n"],
  ["ꞑ", "LATIN SMALL LETTER N WITH DESCENDER", "fold", "n"],
  ["Ꞓ", "LATIN CAPITAL LETTER C WITH BAR", "fold", "c"],
  ["ꞓ", "LATIN SMALL LETTER C WITH BAR", "fold", "c"],
  ["ꞔ", "LATIN SMALL LETTER C WITH PALATAL HOOK", "fold", "c"],
  ["ꞕ", "LATIN SMALL LETTER H WITH PALATAL HOOK", "fold", "h"],
  ["Ꞗ", "LATIN CAPITAL LETTER B WITH FLOURISH", "fold", "b"],
  ["ꞗ", "LATIN SMALL LETTER B WITH FLOURISH", "fold", "b"],
  ["Ꞙ", "LATIN CAPITAL LETTER F WITH STROKE", "fold", "f"],
  ["ꞙ", "LATIN SMALL LETTER F WITH STROKE", "fold", "f"],
  ["Ꞛ", "LATIN CAPITAL LETTER VOLAPUK AE", "outside", ""],
  ["ꞛ", "LATIN SMALL LETTER VOLAPUK AE", "outside", ""],
  ["Ꞝ", "LATIN CAPITAL LETTER VOLAPUK OE", "outside", ""],
  ["ꞝ", "LATIN SMALL LETTER VOLAPUK OE", "outside", ""],
  ["Ꞟ", "LATIN CAPITAL LETTER VOLAPUK UE", "outside", ""],
  ["ꞟ", "LATIN SMALL LETTER VOLAPUK UE", "outside", ""],
  ["Ꞡ", "LATIN CAPITAL LETTER G WITH OBLIQUE STROKE", "fold", "g"],
  ["ꞡ", "LATIN SMALL LETTER G WITH OBLIQUE STROKE", "fold", "g"],
  ["Ꞣ", "LATIN CAPITAL LETTER K WITH OBLIQUE STROKE", "fold", "k"],
  ["ꞣ", "LATIN SMALL LETTER K WITH OBLIQUE STROKE", "fold", "k"],
  ["Ꞥ", "LATIN CAPITAL LETTER N WITH OBLIQUE STROKE", "fold", "n"],
  ["ꞥ", "LATIN SMALL LETTER N WITH OBLIQUE STROKE", "fold", "n"],
  ["Ꞧ", "LATIN CAPITAL LETTER R WITH OBLIQUE STROKE", "fold", "r"],
  ["ꞧ", "LATIN SMALL LETTER R WITH OBLIQUE STROKE", "fold", "r"],
  ["Ꞩ", "LATIN CAPITAL LETTER S WITH OBLIQUE STROKE", "fold", "s"],
  ["ꞩ", "LATIN SMALL LETTER S WITH OBLIQUE STROKE", "fold", "s"],
  ["Ɦ", "LATIN CAPITAL LETTER H WITH HOOK", "fold", "h"],
  ["Ɜ", "LATIN CAPITAL LETTER REVERSED OPEN E", "outside", ""],
  ["Ɡ", "LATIN CAPITAL LETTER SCRIPT G", "outside", ""],
  ["Ɬ", "LATIN CAPITAL LETTER L WITH BELT", "fold", "l"],
  ["Ɪ", "LATIN CAPITAL LETTER SMALL CAPITAL I", "outside", ""],
  ["ꞯ", "LATIN LETTER SMALL CAPITAL Q", "outside", ""],
  ["Ʞ", "LATIN CAPITAL LETTER TURNED K", "outside", ""],
  ["Ʇ", "LATIN CAPITAL LETTER TURNED T", "outside", ""],
  ["Ʝ", "LATIN CAPITAL LETTER J WITH CROSSED-TAIL", "fold", "j"],
  ["Ꭓ", "LATIN CAPITAL LETTER CHI", "outside", ""],
  ["Ꞵ", "LATIN CAPITAL LETTER BETA", "outside", ""],
  ["ꞵ", "LATIN SMALL LETTER BETA", "outside", ""],
  ["Ꞷ", "LATIN CAPITAL LETTER OMEGA", "outside", ""],
  ["ꞷ", "LATIN SMALL LETTER OMEGA", "outside", ""],
  ["Ꞹ", "LATIN CAPITAL LETTER U WITH STROKE", "fold", "u"],
  ["ꞹ", "LATIN SMALL LETTER U WITH STROKE", "fold", "u"],
  ["Ꞻ", "LATIN CAPITAL LETTER GLOTTAL A", "outside", ""],
  ["ꞻ", "LATIN SMALL LETTER GLOTTAL A", "outside", ""],
  ["Ꞽ", "LATIN CAPITAL LETTER GLOTTAL I", "outside", ""],
  ["ꞽ", "LATIN SMALL LETTER GLOTTAL I", "outside", ""],
  ["Ꞿ", "LATIN CAPITAL LETTER GLOTTAL U", "outside", ""],
  ["ꞿ", "LATIN SMALL LETTER GLOTTAL U", "outside", ""],
  ["Ꟁ", "LATIN CAPITAL LETTER OLD POLISH O", "outside", ""],
  ["ꟁ", "LATIN SMALL LETTER OLD POLISH O", "outside", ""],
  ["Ꟃ", "LATIN CAPITAL LETTER ANGLICANA W", "outside", ""],
  ["ꟃ", "LATIN SMALL LETTER ANGLICANA W", "outside", ""],
  ["Ꞔ", "LATIN CAPITAL LETTER C WITH PALATAL HOOK", "fold", "c"],
  ["Ʂ", "LATIN CAPITAL LETTER S WITH HOOK", "fold", "s"],
  ["Ᶎ", "LATIN CAPITAL LETTER Z WITH PALATAL HOOK", "fold", "z"],
  ["Ꟈ", "LATIN CAPITAL LETTER D WITH SHORT STROKE OVERLAY", "fold", "d"],
  ["ꟈ", "LATIN SMALL LETTER D WITH SHORT STROKE OVERLAY", "fold", "d"],
  ["Ꟊ", "LATIN CAPITAL LETTER S WITH SHORT STROKE OVERLAY", "fold", "s"],
  ["ꟊ", "LATIN SMALL LETTER S WITH SHORT STROKE OVERLAY", "fold", "s"],
  ["Ɤ", "LATIN CAPITAL LETTER RAMS HORN", "outside", ""],
  ["Ꟍ", "LATIN CAPITAL LETTER S WITH DIAGONAL STROKE", "fold", "s"],
  ["ꟍ", "LATIN SMALL LETTER S WITH DIAGONAL STROKE", "fold", "s"],
  ["꟎", "LATIN CAPITAL LETTER PHARYNGEAL VOICED FRICATIVE", "outside", ""],
  ["꟏", "LATIN SMALL LETTER PHARYNGEAL VOICED FRICATIVE", "outside", ""],
  ["Ꟑ", "LATIN CAPITAL LETTER CLOSED INSULAR G", "outside", ""],
  ["ꟑ", "LATIN SMALL LETTER CLOSED INSULAR G", "outside", ""],
  ["꟒", "LATIN CAPITAL LETTER DOUBLE THORN", "outside", ""],
  ["ꟓ", "LATIN SMALL LETTER DOUBLE THORN", "outside", ""],
  ["꟔", "LATIN CAPITAL LETTER DOUBLE WYNN", "outside", ""],
  ["ꟕ", "LATIN SMALL LETTER DOUBLE WYNN", "outside", ""],
  ["Ꟗ", "LATIN CAPITAL LETTER MIDDLE SCOTS S", "outside", ""],
  ["ꟗ", "LATIN SMALL LETTER MIDDLE SCOTS S", "outside", ""],
  ["Ꟙ", "LATIN CAPITAL LETTER SIGMOID S", "outside", ""],
  ["ꟙ", "LATIN SMALL LETTER SIGMOID S", "outside", ""],
  ["Ꟛ", "LATIN CAPITAL LETTER LAMBDA", "outside", ""],
  ["ꟛ", "LATIN SMALL LETTER LAMBDA", "outside", ""],
  ["Ƛ", "LATIN CAPITAL LETTER LAMBDA WITH STROKE", "as", "Ꟛ"],
  ["꟱", "MODIFIER LETTER CAPITAL S", "outside", ""],
  ["ꟲ", "MODIFIER LETTER CAPITAL C", "outside", ""],
  ["ꟳ", "MODIFIER LETTER CAPITAL F", "outside", ""],
  ["ꟴ", "MODIFIER LETTER CAPITAL Q", "outside", ""],
  ["Ꟶ", "LATIN CAPITAL LETTER REVERSED HALF H", "outside", ""],
  ["ꟶ", "LATIN SMALL LETTER REVERSED HALF H", "outside", ""],
  ["ꟷ", "LATIN EPIGRAPHIC LETTER SIDEWAYS I", "outside", ""],
  ["ꟸ", "MODIFIER LETTER CAPITAL H WITH STROKE", "outside", ""],
  ["ꟹ", "MODIFIER LETTER SMALL LIGATURE OE", "outside", ""],
  ["ꟺ", "LATIN LETTER SMALL CAPITAL TURNED M", "outside", ""],
  ["ꟻ", "LATIN EPIGRAPHIC LETTER REVERSED F", "outside", ""],
  ["ꟼ", "LATIN EPIGRAPHIC LETTER REVERSED P", "outside", ""],
  ["ꟽ", "LATIN EPIGRAPHIC LETTER INVERTED M", "outside", ""],
  ["ꟾ", "LATIN EPIGRAPHIC LETTER I LONGA", "outside", ""],
  ["ꟿ", "LATIN EPIGRAPHIC LETTER ARCHAIC M", "outside", ""],
  ["ꬰ", "LATIN SMALL LETTER BARRED ALPHA", "as", "ɑ"],
  ["ꬱ", "LATIN SMALL LETTER A REVERSED-SCHWA", "outside", ""],
  ["ꬲ", "LATIN SMALL LETTER BLACKLETTER E", "outside", ""],
  ["ꬳ", "LATIN SMALL LETTER BARRED E", "fold", "e"],
  ["ꬴ", "LATIN SMALL LETTER E WITH FLOURISH", "fold", "e"],
  ["ꬵ", "LATIN SMALL LETTER LENIS F", "outside", ""],
  ["ꬶ", "LATIN SMALL LETTER SCRIPT G WITH CROSSED-TAIL", "as", "ɡ"],
  ["ꬷ", "LATIN SMALL LETTER L WITH INVERTED LAZY S", "fold", "l"],
  ["ꬸ", "LATIN SMALL LETTER L WITH DOUBLE MIDDLE TILDE", "fold", "l"],
  ["ꬹ", "LATIN SMALL LETTER L WITH MIDDLE RING", "fold", "l"],
  ["ꬺ", "LATIN SMALL LETTER M WITH CROSSED-TAIL", "fold", "m"],
  ["ꬻ", "LATIN SMALL LETTER N WITH CROSSED-TAIL", "fold", "n"],
  ["ꬼ", "LATIN SMALL LETTER ENG WITH CROSSED-TAIL", "as", "ŋ"],
  ["ꬽ", "LATIN SMALL LETTER BLACKLETTER O", "outside", ""],
  ["ꬾ", "LATIN SMALL LETTER BLACKLETTER O WITH STROKE", "as", "ꬽ"],
  ["ꬿ", "LATIN SMALL LETTER OPEN O WITH STROKE", "as", "ɔ"],
  ["ꭀ", "LATIN SMALL LETTER INVERTED OE", "outside", ""],
  ["ꭁ", "LATIN SMALL LETTER TURNED OE WITH STROKE", "as", "ᴔ"],
  ["ꭂ", "LATIN SMALL LETTER TURNED OE WITH HORIZONTAL STROKE", "as", "ᴔ"],
  ["ꭃ", "LATIN SMALL LETTER TURNED O OPEN-O", "outside", ""],
  ["ꭄ", "LATIN SMALL LETTER TURNED O OPEN-O WITH STROKE", "as", "ꭃ"],
  ["ꭅ", "LATIN SMALL LETTER STIRRUP R", "outside", ""],
  ["ꭆ", "LATIN LETTER SMALL CAPITAL R WITH RIGHT LEG", "as", "ʀ"],
  ["ꭇ", "LATIN SMALL LETTER R WITHOUT HANDLE", "outside", ""],
  ["ꭈ", "LATIN SMALL LETTER DOUBLE R", "outside", ""],
  ["ꭉ", "LATIN SMALL LETTER R WITH CROSSED-TAIL", "fold", "r"],
  ["ꭊ", "LATIN SMALL LETTER DOUBLE R WITH CROSSED-TAIL", "as", "ꭈ"],
  ["ꭋ", "LATIN SMALL LETTER SCRIPT R", "outside", ""],
  ["ꭌ", "LATIN SMALL LETTER SCRIPT R WITH RING", "as", "ꭋ"],
  ["ꭍ", "LATIN SMALL LETTER BASELINE ESH", "outside", ""],
  ["ꭎ", "LATIN SMALL LETTER U WITH SHORT RIGHT LEG", "fold", "u"],
  ["ꭏ", "LATIN SMALL LETTER U BAR WITH SHORT RIGHT LEG", "as", "ʉ"],
  ["ꭐ", "LATIN SMALL LETTER UI", "outside", ""],
  ["ꭑ", "LATIN SMALL LETTER TURNED UI", "outside", ""],
  ["ꭒ", "LATIN SMALL LETTER U WITH LEFT HOOK", "fold", "u"],
  ["ꭓ", "LATIN SMALL LETTER CHI", "outside", ""],
  ["ꭔ", "LATIN SMALL LETTER CHI WITH LOW RIGHT RING", "as", "ꭓ"],
  ["ꭕ", "LATIN SMALL LETTER CHI WITH LOW LEFT SERIF", "as", "ꭓ"],
  ["ꭖ", "LATIN SMALL LETTER X WITH LOW RIGHT RING", "fold", "x"],
  ["ꭗ", "LATIN SMALL LETTER X WITH LONG LEFT LEG", "fold", "x"],
  ["ꭘ", "LATIN SMALL LETTER X WITH LONG LEFT LEG AND LOW RIGHT RING", "fold", "x"],
  ["ꭙ", "LATIN SMALL LETTER X WITH LONG LEFT LEG WITH SERIF", "fold", "x"],
  ["ꭚ", "LATIN SMALL LETTER Y WITH SHORT RIGHT LEG", "fold", "y"],
  ["ꭜ", "MODIFIER LETTER SMALL HENG", "outside", ""],
  ["ꭝ", "MODIFIER LETTER SMALL L WITH INVERTED LAZY S", "outside", ""],
  ["ꭞ", "MODIFIER LETTER SMALL L WITH MIDDLE TILDE", "outside", ""],
  ["ꭟ", "MODIFIER LETTER SMALL U WITH LEFT HOOK", "outside", ""],
  ["ꭠ", "LATIN SMALL LETTER SAKHA YAT", "outside", ""],
  ["ꭡ", "LATIN SMALL LETTER IOTIFIED E", "outside", ""],
  ["ꭢ", "LATIN SMALL LETTER OPEN OE", "outside", ""],
  ["ꭣ", "LATIN SMALL LETTER UO", "outside", ""],
  ["ꭤ", "LATIN SMALL LETTER INVERTED ALPHA", "outside", ""],
  ["ꭦ", "LATIN SMALL LETTER DZ DIGRAPH WITH RETROFLEX HOOK", "as", "ʣ"],
  ["ꭧ", "LATIN SMALL LETTER TS DIGRAPH WITH RETROFLEX HOOK", "as", "ʦ"],
  ["ꭨ", "LATIN SMALL LETTER TURNED R WITH MIDDLE TILDE", "as", "ɹ"],
  ["ꭩ", "MODIFIER LETTER SMALL TURNED W", "outside", ""],
  ["ﬀ", "LATIN SMALL LIGATURE FF", "outside", ""],
  ["ﬁ", "LATIN SMALL LIGATURE FI", "outside", ""],
  ["ﬂ", "LATIN SMALL LIGATURE FL", "outside", ""],
  ["ﬃ", "LATIN SMALL LIGATURE FFI", "outside", ""],
  ["ﬄ", "LATIN SMALL LIGATURE FFL", "outside", ""],
  ["ﬅ", "LATIN SMALL LIGATURE LONG S T", "outside", ""],
  ["ﬆ", "LATIN SMALL LIGATURE ST", "outside", ""],
  ["Ａ", "FULLWIDTH LATIN CAPITAL LETTER A", "outside", ""],
  ["Ｂ", "FULLWIDTH LATIN CAPITAL LETTER B", "outside", ""],
  ["Ｃ", "FULLWIDTH LATIN CAPITAL LETTER C", "outside", ""],
  ["Ｄ", "FULLWIDTH LATIN CAPITAL LETTER D", "outside", ""],
  ["Ｅ", "FULLWIDTH LATIN CAPITAL LETTER E", "outside", ""],
  ["Ｆ", "FULLWIDTH LATIN CAPITAL LETTER F", "outside", ""],
  ["Ｇ", "FULLWIDTH LATIN CAPITAL LETTER G", "outside", ""],
  ["Ｈ", "FULLWIDTH LATIN CAPITAL LETTER H", "outside", ""],
  ["Ｉ", "FULLWIDTH LATIN CAPITAL LETTER I", "outside", ""],
  ["Ｊ", "FULLWIDTH LATIN CAPITAL LETTER J", "outside", ""],
  ["Ｋ", "FULLWIDTH LATIN CAPITAL LETTER K", "outside", ""],
  ["Ｌ", "FULLWIDTH LATIN CAPITAL LETTER L", "outside", ""],
  ["Ｍ", "FULLWIDTH LATIN CAPITAL LETTER M", "outside", ""],
  ["Ｎ", "FULLWIDTH LATIN CAPITAL LETTER N", "outside", ""],
  ["Ｏ", "FULLWIDTH LATIN CAPITAL LETTER O", "outside", ""],
  ["Ｐ", "FULLWIDTH LATIN CAPITAL LETTER P", "outside", ""],
  ["Ｑ", "FULLWIDTH LATIN CAPITAL LETTER Q", "outside", ""],
  ["Ｒ", "FULLWIDTH LATIN CAPITAL LETTER R", "outside", ""],
  ["Ｓ", "FULLWIDTH LATIN CAPITAL LETTER S", "outside", ""],
  ["Ｔ", "FULLWIDTH LATIN CAPITAL LETTER T", "outside", ""],
  ["Ｕ", "FULLWIDTH LATIN CAPITAL LETTER U", "outside", ""],
  ["Ｖ", "FULLWIDTH LATIN CAPITAL LETTER V", "outside", ""],
  ["Ｗ", "FULLWIDTH LATIN CAPITAL LETTER W", "outside", ""],
  ["Ｘ", "FULLWIDTH LATIN CAPITAL LETTER X", "outside", ""],
  ["Ｙ", "FULLWIDTH LATIN CAPITAL LETTER Y", "outside", ""],
  ["Ｚ", "FULLWIDTH LATIN CAPITAL LETTER Z", "outside", ""],
  ["ａ", "FULLWIDTH LATIN SMALL LETTER A", "outside", ""],
  ["ｂ", "FULLWIDTH LATIN SMALL LETTER B", "outside", ""],
  ["ｃ", "FULLWIDTH LATIN SMALL LETTER C", "outside", ""],
  ["ｄ", "FULLWIDTH LATIN SMALL LETTER D", "outside", ""],
  ["ｅ", "FULLWIDTH LATIN SMALL LETTER E", "outside", ""],
  ["ｆ", "FULLWIDTH LATIN SMALL LETTER F", "outside", ""],
  ["ｇ", "FULLWIDTH LATIN SMALL LETTER G", "outside", ""],
  ["ｈ", "FULLWIDTH LATIN SMALL LETTER H", "outside", ""],
  ["ｉ", "FULLWIDTH LATIN SMALL LETTER I", "outside", ""],
  ["ｊ", "FULLWIDTH LATIN SMALL LETTER J", "outside", ""],
  ["ｋ", "FULLWIDTH LATIN SMALL LETTER K", "outside", ""],
  ["ｌ", "FULLWIDTH LATIN SMALL LETTER L", "outside", ""],
  ["ｍ", "FULLWIDTH LATIN SMALL LETTER M", "outside", ""],
  ["ｎ", "FULLWIDTH LATIN SMALL LETTER N", "outside", ""],
  ["ｏ", "FULLWIDTH LATIN SMALL LETTER O", "outside", ""],
  ["ｐ", "FULLWIDTH LATIN SMALL LETTER P", "outside", ""],
  ["ｑ", "FULLWIDTH LATIN SMALL LETTER Q", "outside", ""],
  ["ｒ", "FULLWIDTH LATIN SMALL LETTER R", "outside", ""],
  ["ｓ", "FULLWIDTH LATIN SMALL LETTER S", "outside", ""],
  ["ｔ", "FULLWIDTH LATIN SMALL LETTER T", "outside", ""],
  ["ｕ", "FULLWIDTH LATIN SMALL LETTER U", "outside", ""],
  ["ｖ", "FULLWIDTH LATIN SMALL LETTER V", "outside", ""],
  ["ｗ", "FULLWIDTH LATIN SMALL LETTER W", "outside", ""],
  ["ｘ", "FULLWIDTH LATIN SMALL LETTER X", "outside", ""],
  ["ｙ", "FULLWIDTH LATIN SMALL LETTER Y", "outside", ""],
  ["ｚ", "FULLWIDTH LATIN SMALL LETTER Z", "outside", ""],
  ["𐞀", "MODIFIER LETTER SMALL CAPITAL AA", "outside", ""],
  ["𐞁", "MODIFIER LETTER SUPERSCRIPT TRIANGULAR COLON", "outside", ""],
  ["𐞂", "MODIFIER LETTER SUPERSCRIPT HALF TRIANGULAR COLON", "outside", ""],
  ["𐞃", "MODIFIER LETTER SMALL AE", "outside", ""],
  ["𐞄", "MODIFIER LETTER SMALL CAPITAL B", "outside", ""],
  ["𐞅", "MODIFIER LETTER SMALL B WITH HOOK", "outside", ""],
  ["𐞇", "MODIFIER LETTER SMALL DZ DIGRAPH", "outside", ""],
  ["𐞈", "MODIFIER LETTER SMALL DZ DIGRAPH WITH RETROFLEX HOOK", "outside", ""],
  ["𐞉", "MODIFIER LETTER SMALL DZ DIGRAPH WITH CURL", "outside", ""],
  ["𐞊", "MODIFIER LETTER SMALL DEZH DIGRAPH", "outside", ""],
  ["𐞋", "MODIFIER LETTER SMALL D WITH TAIL", "outside", ""],
  ["𐞌", "MODIFIER LETTER SMALL D WITH HOOK", "outside", ""],
  ["𐞍", "MODIFIER LETTER SMALL D WITH HOOK AND TAIL", "outside", ""],
  ["𐞎", "MODIFIER LETTER SMALL REVERSED E", "outside", ""],
  ["𐞏", "MODIFIER LETTER SMALL CLOSED REVERSED OPEN E", "outside", ""],
  ["𐞐", "MODIFIER LETTER SMALL FENG DIGRAPH", "outside", ""],
  ["𐞑", "MODIFIER LETTER SMALL RAMS HORN", "outside", ""],
  ["𐞒", "MODIFIER LETTER SMALL CAPITAL G", "outside", ""],
  ["𐞓", "MODIFIER LETTER SMALL G WITH HOOK", "outside", ""],
  ["𐞔", "MODIFIER LETTER SMALL CAPITAL G WITH HOOK", "outside", ""],
  ["𐞕", "MODIFIER LETTER SMALL H WITH STROKE", "outside", ""],
  ["𐞖", "MODIFIER LETTER SMALL CAPITAL H", "outside", ""],
  ["𐞗", "MODIFIER LETTER SMALL HENG WITH HOOK", "outside", ""],
  ["𐞘", "MODIFIER LETTER SMALL DOTLESS J WITH STROKE AND HOOK", "outside", ""],
  ["𐞙", "MODIFIER LETTER SMALL LS DIGRAPH", "outside", ""],
  ["𐞚", "MODIFIER LETTER SMALL LZ DIGRAPH", "outside", ""],
  ["𐞛", "MODIFIER LETTER SMALL L WITH BELT", "outside", ""],
  ["𐞜", "MODIFIER LETTER SMALL CAPITAL L WITH BELT", "outside", ""],
  ["𐞝", "MODIFIER LETTER SMALL L WITH RETROFLEX HOOK AND BELT", "outside", ""],
  ["𐞞", "MODIFIER LETTER SMALL LEZH", "outside", ""],
  ["𐞟", "MODIFIER LETTER SMALL LEZH WITH RETROFLEX HOOK", "outside", ""],
  ["𐞠", "MODIFIER LETTER SMALL TURNED Y", "outside", ""],
  ["𐞡", "MODIFIER LETTER SMALL TURNED Y WITH BELT", "outside", ""],
  ["𐞢", "MODIFIER LETTER SMALL O WITH STROKE", "outside", ""],
  ["𐞣", "MODIFIER LETTER SMALL CAPITAL OE", "outside", ""],
  ["𐞤", "MODIFIER LETTER SMALL CLOSED OMEGA", "outside", ""],
  ["𐞥", "MODIFIER LETTER SMALL Q", "outside", ""],
  ["𐞦", "MODIFIER LETTER SMALL TURNED R WITH LONG LEG", "outside", ""],
  ["𐞧", "MODIFIER LETTER SMALL TURNED R WITH LONG LEG AND RETROFLEX HOOK", "outside", ""],
  ["𐞨", "MODIFIER LETTER SMALL R WITH TAIL", "outside", ""],
  ["𐞩", "MODIFIER LETTER SMALL R WITH FISHHOOK", "outside", ""],
  ["𐞪", "MODIFIER LETTER SMALL CAPITAL R", "outside", ""],
  ["𐞫", "MODIFIER LETTER SMALL TC DIGRAPH WITH CURL", "outside", ""],
  ["𐞬", "MODIFIER LETTER SMALL TS DIGRAPH", "outside", ""],
  ["𐞭", "MODIFIER LETTER SMALL TS DIGRAPH WITH RETROFLEX HOOK", "outside", ""],
  ["𐞮", "MODIFIER LETTER SMALL TESH DIGRAPH", "outside", ""],
  ["𐞯", "MODIFIER LETTER SMALL T WITH RETROFLEX HOOK", "outside", ""],
  ["𐞰", "MODIFIER LETTER SMALL V WITH RIGHT HOOK", "outside", ""],
  ["𐞲", "MODIFIER LETTER SMALL CAPITAL Y", "outside", ""],
  ["𐞳", "MODIFIER LETTER GLOTTAL STOP WITH STROKE", "outside", ""],
  ["𐞴", "MODIFIER LETTER REVERSED GLOTTAL STOP WITH STROKE", "outside", ""],
  ["𐞵", "MODIFIER LETTER BILABIAL CLICK", "outside", ""],
  ["𐞶", "MODIFIER LETTER DENTAL CLICK", "outside", ""],
  ["𐞷", "MODIFIER LETTER LATERAL CLICK", "outside", ""],
  ["𐞸", "MODIFIER LETTER ALVEOLAR CLICK", "outside", ""],
  ["𐞹", "MODIFIER LETTER RETROFLEX CLICK WITH RETROFLEX HOOK", "outside", ""],
  ["𐞺", "MODIFIER LETTER SMALL S WITH CURL", "outside", ""],
  ["𝼀", "LATIN SMALL LETTER FENG DIGRAPH WITH TRILL", "as", "ʩ"],
  ["𝼁", "LATIN SMALL LETTER REVERSED SCRIPT G", "outside", ""],
  ["𝼂", "LATIN LETTER SMALL CAPITAL TURNED G", "outside", ""],
  ["𝼃", "LATIN SMALL LETTER REVERSED K", "outside", ""],
  ["𝼄", "LATIN LETTER SMALL CAPITAL L WITH BELT", "as", "ʟ"],
  ["𝼅", "LATIN SMALL LETTER LEZH WITH RETROFLEX HOOK", "as", "ɮ"],
  ["𝼆", "LATIN SMALL LETTER TURNED Y WITH BELT", "as", "ʎ"],
  ["𝼇", "LATIN SMALL LETTER REVERSED ENG", "outside", ""],
  ["𝼈", "LATIN SMALL LETTER TURNED R WITH LONG LEG AND RETROFLEX HOOK", "as", "ɹ"],
  ["𝼉", "LATIN SMALL LETTER T WITH HOOK AND RETROFLEX HOOK", "fold", "t"],
  ["𝼊", "LATIN LETTER RETROFLEX CLICK WITH RETROFLEX HOOK", "as", "ǃ"],
  ["𝼋", "LATIN SMALL LETTER ESH WITH DOUBLE BAR", "as", "ʃ"],
  ["𝼌", "LATIN SMALL LETTER ESH WITH DOUBLE BAR AND CURL", "as", "ʃ"],
  ["𝼍", "LATIN SMALL LETTER TURNED T WITH CURL", "as", "ʇ"],
  ["𝼎", "LATIN LETTER INVERTED GLOTTAL STOP WITH CURL", "as", "ʖ"],
  ["𝼏", "LATIN LETTER STRETCHED C WITH CURL", "as", "ʗ"],
  ["𝼐", "LATIN LETTER SMALL CAPITAL TURNED K", "outside", ""],
  ["𝼑", "LATIN SMALL LETTER L WITH FISHHOOK", "fold", "l"],
  ["𝼒", "LATIN SMALL LETTER DEZH DIGRAPH WITH PALATAL HOOK", "as", "ʤ"],
  ["𝼓", "LATIN SMALL LETTER L WITH BELT AND PALATAL HOOK", "fold", "l"],
  ["𝼔", "LATIN SMALL LETTER ENG WITH PALATAL HOOK", "as", "ŋ"],
  ["𝼕", "LATIN SMALL LETTER TURNED R WITH PALATAL HOOK", "as", "ɹ"],
  ["𝼖", "LATIN SMALL LETTER R WITH FISHHOOK AND PALATAL HOOK", "fold", "r"],
  ["𝼗", "LATIN SMALL LETTER TESH DIGRAPH WITH PALATAL HOOK", "as", "ʧ"],
  ["𝼘", "LATIN SMALL LETTER EZH WITH PALATAL HOOK", "as", "ʒ"],
  ["𝼙", "LATIN SMALL LETTER DEZH DIGRAPH WITH RETROFLEX HOOK", "as", "ʤ"],
  ["𝼚", "LATIN SMALL LETTER I WITH STROKE AND RETROFLEX HOOK", "fold", "i"],
  ["𝼛", "LATIN SMALL LETTER O WITH RETROFLEX HOOK", "fold", "o"],
  ["𝼜", "LATIN SMALL LETTER TESH DIGRAPH WITH RETROFLEX HOOK", "as", "ʧ"],
  ["𝼝", "LATIN SMALL LETTER C WITH RETROFLEX HOOK", "fold", "c"],
  ["𝼞", "LATIN SMALL LETTER S WITH CURL", "fold", "s"],
  ["𝼥", "LATIN SMALL LETTER D WITH MID-HEIGHT LEFT HOOK", "fold", "d"],
  ["𝼦", "LATIN SMALL LETTER L WITH MID-HEIGHT LEFT HOOK", "fold", "l"],
  ["𝼧", "LATIN SMALL LETTER N WITH MID-HEIGHT LEFT HOOK", "fold", "n"],
  ["𝼨", "LATIN SMALL LETTER R WITH MID-HEIGHT LEFT HOOK", "fold", "r"],
  ["𝼩", "LATIN SMALL LETTER S WITH MID-HEIGHT LEFT HOOK", "fold", "s"],
  ["𝼪", "LATIN SMALL LETTER T WITH MID-HEIGHT LEFT HOOK", "fold", "t"],
];

const FOLDS: ReadonlyArray<readonly [string, (s: string) => string]> = [
  ["searchKey", searchKey],
  ["canonicalTrailSlug", (s) => canonicalTrailSlug(s) ?? ""],
  ["trailDestinationKey", trailDestinationKey],
];
const LATIN = /^(?=\p{Script=Latin})\p{L}$/u;
function latinLetters(): string[] {
  const out: string[] = [];
  for (let cp = 0; cp <= 0x10ffff; cp++) { if (cp === 0xd800) cp = 0xe000; const ch = String.fromCodePoint(cp); if (LATIN.test(ch)) out.push(ch); }
  return out;
}
const asciiBase = (ch: string) => { const b = ch.normalize("NFD").replace(/[̀-ͯ]/g, ""); return /^[A-Za-z]$/.test(b) ? b : null; };
const byKind = (k: Kind) => LETTERS.filter((r) => r[2] === k);
const sqlOf = (file: string) => readFileSync(new URL(`../migrations/${file}`, import.meta.url), "utf8");
const fnBody = (sql: string, name: string) => { const at = sql.indexOf(`FUNCTION public.${name}(`); assert.ok(at >= 0, `${name} not defined`); return sql.slice(at, sql.indexOf("$fn$;", at)); };

describe("§73 — the Latin letter fold, enumerated over every Latin letter (DV-20, B01)", () => {
  it("L1. exhaustive: every Latin letter in Unicode 17 is NFD-reducible to an ASCII letter, which every fold keeps, or is classified with its name", () => {
    assert.equal(process.versions.unicode, "17.0", "LETTERS carries UnicodeData.txt 17.0's names; another Unicode needs them regenerated");
    const listed = new Map(LETTERS.map((r) => [r[0], r]));
    assert.equal(listed.size, LETTERS.length, "a letter is listed twice");
    const all = latinLetters();
    assert.equal(all.length, 1453);
    let reducible = 0;
    for (const ch of all) {
      const base = asciiBase(ch);
      if (base === null) { assert.ok(listed.has(ch), `U+${ch.codePointAt(0)!.toString(16).toUpperCase()} ${ch} is not classified`); continue; }
      reducible++;
      assert.ok(!listed.has(ch), `${ch} is NFD-reducible and must not be listed`);
      for (const [name, f] of FOLDS) assert.equal(f(`x${ch}x`), f(`x${base}x`), `${name}: ${ch} vs ${base}`);
    }
    assert.equal(reducible + LETTERS.length, all.length, "every listed letter is a Latin letter");
    for (const [ch] of LETTERS) assert.ok(LATIN.test(ch), `${ch} is not a Latin letter`);
    assert.equal(all.filter((c) => c.codePointAt(0)! >= 0xc0 && c.codePointAt(0)! <= 0x24f).length, 398, "the 398 letters §66.11 counted");
    assert.deepEqual([byKind("fold").length, byKind("as").length, byKind("outside").length], [247, 95, 569]);
    // The classification follows the names: every "LATIN … LETTER X WITH …" is fold or as, except where X names no letter.
    const unfolded = byKind("outside").filter(([, n]) => /^LATIN .*LETTER .+ WITH /.test(n)).map(([c, n]) => `${c} ${n}`);
    assert.deepEqual(unfolded, [
      "ƻ LATIN LETTER TWO WITH STROKE", "ɿ LATIN SMALL LETTER REVERSED R WITH FISHHOOK",
      "ʢ LATIN LETTER REVERSED GLOTTAL STOP WITH STROKE", "ʨ LATIN SMALL LETTER TC DIGRAPH WITH CURL",
    ], "X names no Latin letter: TWO, REVERSED R, REVERSED GLOTTAL STOP, TC DIGRAPH");
  });

  it("L2. every 'X WITH …' letter whose X is a letter A–Z folds to X, alone, inside a word and before 'resund', in all three folds", () => {
    const wrong: string[] = [];
    for (const [ch, name, , to] of byKind("fold")) for (const [fold, f] of FOLDS) {
      if (f(ch) === "" || f(ch) !== f(to) || f(`x${ch}x`) !== f(`x${to}x`) || f(`${ch}resund`) !== f(`${to}resund`)) wrong.push(`${fold}: ${ch} (${name}) → ${JSON.stringify(f(ch))}, want ${JSON.stringify(f(to))}`);
    }
    assert.deepEqual(wrong, []);
  });

  it("L3. a letter whose X is itself a Latin letter (AE, THORN, ENG, EZH, DZ, …) folds exactly as X does, in every fold", () => {
    const wrong: string[] = [];
    for (const [ch, name, , base] of byKind("as")) for (const [fold, f] of FOLDS) {
      if (f(`x${ch}x`) !== f(`x${base}x`)) wrong.push(`${fold}: ${ch} (${name}) → ${JSON.stringify(f(`x${ch}x`))}, ${base} → ${JSON.stringify(f(`x${base}x`))}`);
    }
    assert.deepEqual(wrong, []);
    assert.equal(canonicalTrailSlug("Ꝥ"), "th", "THORN WITH STROKE is spelled as þ is, in a Trail");
    assert.equal(canonicalTrailSlug("ǽ"), "ae", "æ with an acute meets the Trail's letter fold");
  });

  it("L4. case-closed: the other case of every folded letter folds the same, wherever Unicode puts it", () => {
    const wrong: string[] = [];
    for (const [ch] of byKind("fold")) for (const other of [ch.toLowerCase(), ch.toUpperCase()]) {
      if (other === ch || [...other].length !== 1) continue;
      for (const [fold, f] of FOLDS) if (f(other) !== f(ch)) wrong.push(`${fold}: ${ch} → ${JSON.stringify(f(ch))} but ${other} → ${JSON.stringify(f(other))}`);
    }
    assert.deepEqual(wrong, []);
  });

  it("L5. DV-20's and B01's own case: 'Ǿresund' and 'Øresund' are one Trail, one destination and one search key", () => {
    assert.equal(canonicalTrailSlug("Ǿresund cycling"), "oresund-cycling");
    assert.equal(canonicalTrailSlug("Øresund cycling"), "oresund-cycling");
    assert.equal(canonicalTrailSlug("Ƀerlin street art"), "berlin-street-art");
    assert.equal(searchKey("Ǿresund"), "oresund");
    assert.equal(searchKey("ǿresund"), searchKey("Oresund"));
    assert.equal(trailDestinationKey("Ǿresund"), trailDestinationKey("oresund"));
    const r = canonicaliseTrailProposal({ title: "Ǿresund cycling", destination: null }, [{ id: "t-1", slug: "oresund-cycling", title: "Øresund cycling", destination: null }]);
    assert.equal(r.ok, false);
    assert.ok(r.refusals.some((x) => x.check === "duplicate_title_similarity" && x.conflictsWith === "t-1"), JSON.stringify(r.refusals));
  });

  it("L6. the table is exactly the folded letters (less the two that reach it through NFD), İ, and the 'as' letters whose X survives a fold", () => {
    const keys = new Set(Object.keys(STROKE_FOLD));
    assert.deepEqual(byKind("fold").filter(([ch]) => !keys.has(ch)).map(([ch]) => ch), ["Ǿ", "ǿ"], "only Ǿ ǿ reach the table through their decomposition");
    for (const [ch, to] of Object.entries(STROKE_FOLD)) {
      const row = LETTERS.find((r) => r[0] === ch);
      assert.ok(!Object.keys(STROKE_FOLD).some((k) => to.includes(k)), `${ch} folds onto a table key`);
      if (ch === "İ") { assert.equal(row, undefined, "İ decomposes, and stays because 2220's table had it"); continue; }
      assert.ok(row, `${ch} is in the table but not a listed letter`);
      if (row[2] === "fold") assert.equal(to, row[3], `${ch}`);
      else assert.ok(row[2] === "as" && FOLDS.every(([, f]) => f(to) === f(row[3])), `${ch} → ${to} is not how its X folds`);
    }
    assert.equal(keys.size, 257);
    assert.equal(byKind("as").filter(([ch]) => keys.has(ch)).map(([ch]) => ch).join(""), "ǄǆẜẝꝤꝥꝦꝧꬼꭏ𝼔");
  });

  it("L7. both SQL twins carry the same table, and apply it to the NFD form: 3440's input_normalize_city_key and 3441's trail_letter_fold", () => {
    for (const [file, fn, arg] of [["3440_canonical_search_key_letter_fold.sql", "input_normalize_city_key", "p_name"], ["3441_trail_letter_fold_decompose_first.sql", "trail_letter_fold", "p_text"]] as const) {
      const body = fnBody(sqlOf(file), fn);
      const t = new RegExp(`translate\\(normalize\\(${arg}, NFD\\), '([^']+)', '([^']+)'\\)`, "u").exec(body);
      assert.ok(t, `${file}: ${fn} must apply its table to normalize(${arg}, NFD), not to the raw text`);
      const [from, to] = [[...t![1]!], [...t![2]!]];
      assert.equal(from.length, to.length, `${file}: translate strings are not codepoint-aligned`);
      const table: Record<string, string> = Object.fromEntries(from.map((c, i) => [c, to[i]!]));
      for (const m of body.matchAll(/'(.)', '([^']{2,})'\)/gu)) if (m[1]! in STROKE_FOLD) table[m[1]!] = m[2]!;
      assert.deepEqual(table, { ...STROKE_FOLD }, `${file}: ${fn}'s table is not STROKE_FOLD`);
    }
  });

  it("L8. RECORDED, not a criterion: the 569 'outside' letters. searchKey deletes every one; the slug spells the ones NFKD or the Trail letter fold spells; ß æ œ unchanged (owner question 4)", () => {
    const out = byKind("outside").map((r) => r[0]);
    assert.deepEqual(out.filter((c) => searchKey(c) !== ""), [], "searchKey keeps no outside letter");
    const kept = out.filter((c) => (canonicalTrailSlug(c) ?? "") !== "");
    assert.equal(kept.length, 146, "the MODIFIER LETTER and ligature forms NFKD spells, and the Trail letter fold's ten");
    assert.equal(out.filter((c) => trailDestinationKey(c) !== "").join(""), "ÆÞßæþŊŋŒœẞ", "a destination keeps exactly the Trail letter fold's ten");
    for (const [c, s] of [["ß", "ss"], ["æ", "ae"], ["œ", "oe"], ["þ", "th"], ["ŋ", "ng"], ["Ĳ", "ij"], ["Ǳ", "dz"]] as const) assert.equal(canonicalTrailSlug(c), s);
    assert.equal(searchKey("Straße"), "stra e", "Q4: searchKey still deletes ß");
    assert.equal(searchKey("Æbeltoft"), "beltoft", "Q4: and æ");
    assert.equal(searchKey("Œuf"), "uf", "Q4: and œ");
  });
});

// ── §77 (lane P35): every combining diacritic a Latin word can carry, not only U+0300–U+036F ──
//
// §74 (lane P32) found the three folds stripping one block of combining marks, U+0300–U+036F, while
// Unicode encodes Latin's combining diacritics in FOUR: Combining Diacritical Marks, … Extended
// (U+1AB0–U+1AFF), … Supplement (U+1DC0–U+1DFF) and Combining Half Marks (U+FE20–U+FE2F). 91 marks of
// the other three carry Unicode's Diacritic property, and each one split the word it sat in:
// "I︠A︡roslavl" (ALA-LC's tie as the half marks U+FE20/U+FE21) keyed `i a roslavl` and slugged
// `i-a-roslavl`. THE RULE (lib/latinLetterFold.LATIN_MARK_BLOCKS): each of the four blocks is stripped
// WHOLE, as U+0300–U+036F always was — including the 19 marks of U+0300–U+036F and the 47 of the other
// three that lack the Diacritic property (the combining small letters above, U+1DC0's Greek accents), and
// the block's unassigned code points, which Unicode reserves for more combining marks. L9 checks the
// rule against this runtime's Unicode data over every code point; L10 pins the SQL twins to it.
// NOT stripped, and stated so the owner can overrule it: U+20D0–U+20FF (Combining Diacritical Marks
// for Symbols — none has the Diacritic property), the variation selectors, and marks of other scripts,
// U+0485 U+0486 U+0951 U+0952 among them though their Script_Extensions name Latin.
const MARK_BLOCKS: ReadonlyArray<readonly [number, number]> = [[0x0300, 0x036f], [0x1ab0, 0x1aff], [0x1dc0, 0x1dff], [0xfe20, 0xfe2f]];
const inMarkBlock = (cp: number) => MARK_BLOCKS.some(([lo, hi]) => cp >= lo && cp <= hi);
const U = (cp: number) => `U+${cp.toString(16).toUpperCase().padStart(4, "0")}`;

describe("§77 — every Latin combining diacritic folds (DV-20, B01)", () => {
  it("L9. exhaustive: a code point vanishes inside a word, in all three folds, exactly when it is in one of the four Latin combining blocks", () => {
    assert.equal(process.versions.unicode, "17.0", "the counts below are Unicode 17.0's");
    let assigned = 0, diacritic = 0;
    const notMark: string[] = [];
    for (const [lo, hi] of MARK_BLOCKS) for (let cp = lo; cp <= hi; cp++) {
      const ch = String.fromCodePoint(cp);
      if (/\p{Cn}/u.test(ch)) continue;
      if (lo !== 0x0300) { assigned++; if (/\p{Mn}/u.test(ch) && /\p{Diacritic}/u.test(ch)) diacritic++; }
      if (!/\p{M}/u.test(ch)) notMark.push(U(cp));
    }
    assert.deepEqual(notMark, [], "every assigned code point of the four blocks is a combining mark, so stripping one never deletes a letter");
    assert.deepEqual([assigned, diacritic], [138, 91], "the three blocks beyond U+036F: 138 assigned marks, 91 of them Diacritic (§74's population)");
    const wrong: string[] = [];
    let vanished = 0;
    for (const [name, f] of FOLDS) {
      const plain = f("zurich");
      for (let cp = 0; cp <= 0x10ffff; cp++) {
        if (cp === 0xd800) cp = 0xe000;
        const gone = f(`zu${String.fromCodePoint(cp)}rich`) === plain;
        if (gone) vanished++;
        if (gone !== inMarkBlock(cp) && wrong.length < 40) wrong.push(`${name}: ${U(cp)} ${gone ? "vanishes outside the blocks" : "splits the word inside a block"}`);
      }
    }
    assert.deepEqual(wrong, []);
    assert.equal(vanished, 3 * 272, "112 + 80 + 64 + 16 code points, in each of the three folds");
  });

  it("L10. the SQL twins strip the same four blocks: 3440's input_normalize_city_key, 3441's trail_canonical_slug and trail_normalised_destination; 3441 recomputes stored slugs and keys destinations", () => {
    const ranges = (body: string) => [...body.matchAll(/chr\((\d+)\) \|\| '-' \|\| chr\((\d+)\)/g)].map((m) => [Number(m[1]), Number(m[2])]);
    const m3441 = sqlOf("3441_trail_letter_fold_decompose_first.sql");
    for (const [file, fn] of [["3440_canonical_search_key_letter_fold.sql", "input_normalize_city_key"], ["3441_trail_letter_fold_decompose_first.sql", "trail_canonical_slug"], ["3441_trail_letter_fold_decompose_first.sql", "trail_normalised_destination"]] as const) {
      assert.deepEqual(ranges(fnBody(sqlOf(file), fn)), MARK_BLOCKS.map((b) => [...b]), `${file}: ${fn} does not strip the four blocks`);
    }
    assert.match(m3441, /UPDATE public\.trails\s+SET slug = public\.trail_canonical_slug\(title\)/, "3441 must recompute the stored slug (§74.4 #2)");
    assert.match(m3441, /ADD COLUMN destination_key text\s+GENERATED ALWAYS AS \(public\.trail_normalised_destination\(destination\)\) STORED/, "listTrails filters on the stored destination key");
  });
});
