/**
 * Enum filter-literal guard.
 *
 * THE DEFECT THIS EXISTS FOR
 * --------------------------
 * `searchHiddenGems` filtered `.in("status", ["approved", "active"])`. The enum
 * `hidden_gem_status` has labels pending | active | hidden | merged. Postgres
 * does not treat an unknown enum literal as a non-match — it raises 22P02, a
 * HARD ERROR. PostgREST turns that into a 400, supabase-js resolves
 * `{ data: null, error }` rather than throwing, and the caller's
 * `if (error || !data) return []` turns the 400 into an empty result set.
 *
 * So the search did not fail. It returned nothing, for every query, forever,
 * and looked exactly like "no gems matched".
 *
 * THE SHAPE: A STRING LITERAL COMPARED AGAINST AN ENUM-TYPED COLUMN, WHERE THE
 * STRING IS NOT ONE OF THAT ENUM'S LABELS. One bad literal kills the WHOLE
 * query — including an `.in()` list whose other values are perfectly valid —
 * because Postgres casts every element before matching any of them.
 *
 * Two properties make it near-invisible:
 *  - The same typo is HARMLESS on a `text` column (an ordinary non-match) and
 *    TOTAL on an enum column. Nothing in the call site distinguishes them.
 *  - The fixtures invent the label too. Six emitters shipped with tests that
 *    asserted on `status: "approved"`, `status: "published"`, `status:
 *    "deleted"` — values no row in either database can hold — and were green
 *    for months.
 *
 * WHAT THIS GUARD CHECKS
 * ----------------------
 * Every `.eq()` / `.neq()` / `.in()` / `.not(…, "in", …)` string literal fed to
 * a column that `src/lib/database.types.ts` declares as enum-typed, held
 * against that enum's labels. Both the column→enum mapping and the label sets
 * are read out of the generated types — no hand-transcribed schema to drift.
 *
 * KNOWN_DEAD_QUERIES below is a RATCHET, not an allowlist: it records the sites
 * that already existed when this guard was written, with what each one breaks.
 * The count per file is exact, so BOTH directions fail — a new bad literal in
 * an already-listed file, and a fixed one that was not struck off. The list is
 * meant to reach zero.
 *
 * WHAT THIS GUARD CANNOT CHECK — read this before trusting it
 * -----------------------------------------------------------
 * This is a source scan against a generated types file, not a live-schema diff.
 *
 *  - `database.types.ts` is regenerated by hand and IS observably stale for
 *    COLUMNS (it lacks `post_media.feed_url` and `profiles.phone_e164`, both
 *    live). It has not been observed to name an enum or a label that does not
 *    exist, and its labels match a 2026-09-03 production read exactly. Staleness
 *    therefore shows up as a FALSE POSITIVE on a newly added label — loud and
 *    fixable — never as a silent pass. Regenerate the types rather than
 *    allowlisting such a hit.
 *  - Table attribution is positional: a filter belongs to the nearest preceding
 *    `.from("literal")` in the same statement. `.from(tableVar)` is invisible,
 *    and so is any filter built dynamically or held in a variable.
 *  - It sees only string LITERALS. `.eq("status", someVar)` is out of scope,
 *    which is where the next instance of this class will most likely hide.
 *  - It says nothing about whether a query with only real labels asks the RIGHT
 *    question. `searchPosts` filtered `.neq("status","deleted")` using a real
 *    label while leaving `hidden` and `reported` posts publicly searchable;
 *    this guard would have passed that.
 *  - Comments are stripped before scanning, so prose describing a bad filter
 *    (including the comments explaining the fixes) is not counted.
 *
 * Sibling guards, deliberately not duplicated here: `check:write-path-columns`
 * diffs select lists against the LIVE schema ("is the query wrong?");
 * `silentSchemaErrorCatches.test.ts` finds the catches that hide the answer
 * ("would anyone find out?"). This one asks: "is the VALUE wrong?".
 */
import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { readFileSync, readdirSync, statSync } from "node:fs";
import { join, dirname, resolve, relative } from "node:path";
import { fileURLToPath } from "node:url";

const __dir = dirname(fileURLToPath(import.meta.url));
const API_ROOT = resolve(__dir, "../..");
const SRC = resolve(__dir, "..");
const TYPES = join(SRC, "lib/database.types.ts");

// ── The known dead queries, as a ratchet ──────────────────────────────────────
//
// Each entry: the file, how many bad literals it contains today, and what the
// dead query costs. Reported by the 2026-09-03 enum-literal sweep and left
// UNFIXED — each needs its own judgement about which real label carries the
// intent, which is the work the fix actually is (see searchPosts: the label it
// was missing was not the one it looked like it was missing).
//
// To fix one: correct the literal, then drop its count here.

const KNOWN_DEAD_QUERIES: Record<string, { count: number; effect: string }> = {
  "src/compass/CompassAbuseDefenseEngine.ts": {
    count: 1,
    effect: 'rent_buddy_bookings "refunded" — the cancellation/refund abuse signal never fires.',
  },
  "src/compass/CompassFallbackFeedBuilder.ts": {
    count: 1,
    effect: 'trips .in("status", ["in_progress", "upcoming"]) — "upcoming" is real and ' +
      '"in_progress" is not, and Postgres casts every element before matching any, so the ' +
      "fallback feed loses ALL of the user's owned trips, not just in-progress ones. The " +
      "clearest example of why one bad literal in a list kills the whole query.",
  },
  "src/compass/CompassItemHydrator.ts": {
    count: 1,
    effect: 'hidden_gems "approved" — Compass hydrates no hidden gems at all.',
  },
  "src/compass/CompassLiveEngine.ts": {
    count: 1,
    effect: 'trips "in_progress" — live intel never binds to the trip the user is on.',
  },
  "src/compass/CompassSenseEngine.ts": {
    count: 1,
    effect: 'trips "in_progress" — same, on the sense path.',
  },
  "src/compass/CompassTools.ts": {
    count: 4,
    effect: 'events "deleted"/"banned" at two sites — both Compass event tools return nothing. ' +
      "Identical to the searchEvents defect fixed in 51402fe99; this copy was never updated.",
  },
  "src/lib/inputAssistance/duplicateDetection.ts": {
    count: 1,
    effect: 'hidden_gems "approved" — duplicate detection finds no duplicates, so duplicate ' +
      "gems are created unchallenged.",
  },
  "src/routes/adminCompass.ts": {
    count: 1,
    effect: 'posts.post_status "delayed_post" — the admin pending-publish count is always empty.',
  },
  "src/routes/compass.ts": {
    count: 1,
    effect: 'trips.visibility "friends" (the real label is "buddies") — the traveller-overlap ' +
      "query is dead.",
  },
  "src/routes/compassHome.ts": {
    count: 2,
    effect: 'events "deleted"/"banned" — Compass Home shows no events.',
  },
  "src/routes/dailyBrief.ts": {
    count: 1,
    effect: 'trips "in_progress" — the daily brief never picks up the trip in progress, which ' +
      "is its stated highest-priority input.",
  },
  "src/services/hiddenGems/HiddenGemModerationService.ts": {
    count: 1,
    effect: 'hidden_gems "approved" — the moderation queue\'s active list. The ONLY site of ' +
      "these fifteen that rethrows its error instead of swallowing it, so it is the only one " +
      "that ever surfaced as a failure rather than as emptiness.",
  },
  "src/services/interactionPermissions.ts": {
    count: 1,
    effect: 'rent_buddy_bookings "pre_booking" — `rabPreBooking` is permanently false, so the ' +
      "`rab_off_app_payment_risk` safety warning can never be raised.",
  },
  "src/services/ranking/CreatorActivityScoreService.ts": {
    count: 1,
    effect: 'posts "published" — posts contribute 0 to every creator activity score.',
  },
};

// ── Schema facts, read from the generated types ───────────────────────────────

/** `table.column` -> enum type name, from the `Row` annotations. */
function readColumnEnums(src: string): Map<string, string> {
  const out = new Map<string, string>();
  let cur: string | null = null;
  let inRow = false;
  for (const l of src.split("\n")) {
    let m;
    if ((m = l.match(/^      (\w+): \{$/))) { cur = m[1]!; inRow = false; continue; }
    if (cur && /^        Row: \{$/.test(l)) { inRow = true; continue; }
    if (!inRow) continue;
    if (/^        \}/.test(l)) { inRow = false; continue; }
    const c = l.match(/^          (\w+)\??: Database\["public"\]\["Enums"\]\["(\w+)"\]/);
    if (c) out.set(`${cur}.${c[1]}`, c[2]!);
  }
  return out;
}

/** enum type name -> its labels, from the exported `Constants` block. */
function readEnumLabels(src: string): Map<string, Set<string>> {
  const out = new Map<string, Set<string>>();
  const i = src.indexOf("export const Constants = {");
  assert.ok(i >= 0, "database.types.ts has no exported Constants block");
  const block = src.slice(i);
  // one-line form: `  name: ["a", "b"],`
  for (const m of block.matchAll(/^      (\w+): \[([^\][]*)\],$/gm)) {
    out.set(m[1]!, new Set([...m[2]!.matchAll(/"([^"]*)"/g)].map((x) => x[1]!)));
  }
  // multi-line form
  for (const m of block.matchAll(/^      (\w+): \[\n((?:\s+"[^"]*",\n)+)      \],$/gm)) {
    out.set(m[1]!, new Set([...m[2]!.matchAll(/"([^"]*)"/g)].map((x) => x[1]!)));
  }
  return out;
}

// ── The scan ──────────────────────────────────────────────────────────────────

/** Blank out comments, preserving byte offsets so line numbers stay right. */
function stripComments(text: string): string {
  return text
    .replace(/\/\*[\s\S]*?\*\//g, (m) => m.replace(/[^\n]/g, " "))
    .replace(/(^|[^:])\/\/[^\n]*/g, (m, p1: string) => p1 + " ".repeat(m.length - p1.length));
}

function* sourceFiles(dir: string): Generator<string> {
  for (const e of readdirSync(dir)) {
    const p = join(dir, e);
    if (statSync(p).isDirectory()) {
      if (e === "node_modules" || e === "test" || e === "__tests__") continue;
      yield* sourceFiles(p);
    } else if (/\.ts$/.test(e) && !/\.d\.ts$/.test(e) && !/\.test\.ts$/.test(e)) {
      yield p;
    }
  }
}

interface Hit { file: string; line: number; column: string; enumName: string; value: string; op: string }

function scan(colEnum: Map<string, string>, enumLabels: Map<string, Set<string>>): Hit[] {
  const hits: Hit[] = [];
  for (const abs of sourceFiles(SRC)) {
    const raw = readFileSync(abs, "utf8");
    const text = stripComments(raw);
    const file = relative(API_ROOT, abs);

    const marks: Array<{ table: string; at: number }> = [];
    for (const m of text.matchAll(/\.from\(\s*["'`](\w+)["'`]\s*\)/g)) {
      marks.push({ table: m[1]!, at: m.index! });
    }

    for (let i = 0; i < marks.length; i++) {
      const { table, at } = marks[i]!;
      const hardStop = i + 1 < marks.length ? marks[i + 1]!.at : text.length;
      const seg = text.slice(at, Math.min(hardStop, at + 2500));

      const emit = (col: string, value: string, op: string, offset: number) => {
        const key = `${table}.${col}`;
        const enumName = colEnum.get(key);
        if (!enumName) return;                       // not an enum column: harmless
        const labels = enumLabels.get(enumName);
        if (!labels) return;                         // enum we could not parse: not our call
        if (labels.has(value)) return;
        hits.push({
          file, line: text.slice(0, at + offset).split("\n").length,
          column: key, enumName, value, op,
        });
      };

      for (const x of seg.matchAll(/\.(eq|neq)\(\s*["'`](\w+)["'`]\s*,\s*["'`]([^"'`]*)["'`]\s*\)/g)) {
        emit(x[2]!, x[3]!, `.${x[1]}()`, x.index!);
      }
      for (const x of seg.matchAll(/\.in\(\s*["'`](\w+)["'`]\s*,\s*\[([^\]]*)\]/g)) {
        for (const v of x[2]!.matchAll(/["'`]([^"'`]*)["'`]/g)) emit(x[1]!, v[1]!, ".in()", x.index!);
      }
      for (const x of seg.matchAll(/\.not\(\s*["'`](\w+)["'`]\s*,\s*["'`]in["'`]\s*,\s*["'`]\(([^)]*)\)["'`]/g)) {
        for (const v of x[2]!.matchAll(/"([^"]*)"/g)) emit(x[1]!, v[1]!, '.not(…,"in",…)', x.index!);
      }
    }
  }
  return hits;
}

// ── Tests ─────────────────────────────────────────────────────────────────────

const typesSrc = readFileSync(TYPES, "utf8");
const COLUMN_ENUMS = readColumnEnums(typesSrc);
const ENUM_LABELS = readEnumLabels(typesSrc);

describe("enum filter literals — the scan's own inputs", () => {
  it("parsed a plausible number of enum-typed columns and enums", () => {
    // If a types regeneration changes the file's shape, the parse can silently
    // collapse to zero and this guard passes while checking nothing.
    assert.ok(COLUMN_ENUMS.size >= 40, `only ${COLUMN_ENUMS.size} enum-typed columns parsed — the parse broke`);
    assert.ok(ENUM_LABELS.size >= 40, `only ${ENUM_LABELS.size} enums parsed — the parse broke`);
  });

  it("resolves the columns the known defects were found on", () => {
    for (const [col, en] of [
      ["hidden_gems.status", "hidden_gem_status"],
      ["events.state", "event_state"],
      ["trips.status", "trip_status"],
      ["posts.status", "post_status"],
      ["trips.visibility", "trip_visibility"],
    ] as const) {
      assert.equal(COLUMN_ENUMS.get(col), en, `${col} no longer resolves to ${en}`);
      assert.ok((ENUM_LABELS.get(en)?.size ?? 0) > 0, `${en} has no labels`);
    }
  });

  it("does not treat text columns as enums", () => {
    // `trip_plan_items.status` is `text` (DEFAULT 'tentative'). A wrong literal
    // there is a non-match, not a 400, and flagging it would be a false alarm.
    assert.equal(COLUMN_ENUMS.get("trip_plan_items.status"), undefined);
    assert.equal(COLUMN_ENUMS.get("trip_plan_items.visibility"), undefined);
  });

  it("finds real call sites at all", () => {
    // A scan that matched nothing would pass every ratchet check below.
    const anyFrom = [...sourceFiles(SRC)].some((f) =>
      /\.from\(\s*["'`]\w+["'`]\s*\)/.test(stripComments(readFileSync(f, "utf8"))));
    assert.ok(anyFrom, "no .from(\"literal\") call sites found — the scan is inert");
  });

  it("ignores a bad literal that appears only in a comment", () => {
    const sample = `
      // .eq("status", "totally_fake")
      /* .in("status", ["also_fake"]) */
      const x = 1;`;
    assert.ok(!stripComments(sample).includes("totally_fake"));
    assert.ok(!stripComments(sample).includes("also_fake"));
    assert.equal(stripComments(sample).split("\n").length, sample.split("\n").length,
      "stripComments must preserve line count so reported line numbers stay right");
  });
});

describe("enum filter literals — no query compares an enum column to a label it lacks", () => {
  const hits = scan(COLUMN_ENUMS, ENUM_LABELS);
  const byFile = new Map<string, Hit[]>();
  for (const h of hits) {
    if (!byFile.has(h.file)) byFile.set(h.file, []);
    byFile.get(h.file)!.push(h);
  }

  it("introduces no NEW dead query", () => {
    const offenders: string[] = [];
    for (const [file, fileHits] of byFile) {
      const known = KNOWN_DEAD_QUERIES[file];
      if (!known) {
        offenders.push(
          `${file} is not in KNOWN_DEAD_QUERIES:\n` +
          fileHits.map((h) =>
            `    :${h.line}  ${h.column} ${h.op} "${h.value}" — ${h.enumName} has ` +
            `[${[...ENUM_LABELS.get(h.enumName)!].join(", ")}]`).join("\n"));
        continue;
      }
      if (fileHits.length > known.count) {
        offenders.push(
          `${file} grew from ${known.count} to ${fileHits.length} bad literal(s):\n` +
          fileHits.map((h) => `    :${h.line}  ${h.column} ${h.op} "${h.value}"`).join("\n"));
      }
    }
    assert.deepEqual(
      offenders, [],
      "A string literal compared against an enum-typed column is not one of that enum's " +
      "labels. Postgres raises 22P02 and PostgREST returns 400 — the query does not match " +
      "nothing, it FAILS, and any `if (error || !data) return []` above it will hide that.\n\n" +
      offenders.join("\n"),
    );
  });

  it("keeps the ratchet honest — a fixed file must be struck off", () => {
    const stale: string[] = [];
    for (const [file, { count }] of Object.entries(KNOWN_DEAD_QUERIES)) {
      const actual = byFile.get(file)?.length ?? 0;
      if (actual < count) {
        stale.push(
          `${file}: KNOWN_DEAD_QUERIES says ${count}, scan finds ${actual}` +
          (actual === 0 ? " — fixed; delete the entry." : ` — partly fixed; set count to ${actual}.`));
      }
    }
    assert.deepEqual(stale, [], stale.join("\n"));
  });

  it("still sees every file the 2026-09-03 sweep recorded", () => {
    // Guards against the scan quietly losing reach — a refactor that moves a
    // query behind a variable table name would otherwise read as a fix.
    const missing = Object.keys(KNOWN_DEAD_QUERIES).filter((f) => !byFile.has(f));
    assert.deepEqual(
      missing, [],
      "these files were known to contain a bad enum literal and the scan no longer sees " +
      "them at all — either they were fixed (strike them off) or the scan lost reach:\n" +
      missing.join("\n"),
    );
  });

  it("reports the total, so the backlog is visible rather than implied", () => {
    const expected = Object.values(KNOWN_DEAD_QUERIES).reduce((n, k) => n + k.count, 0);
    assert.equal(
      hits.length, expected,
      `expected ${expected} known bad literal(s), scan found ${hits.length}. ` +
      "Update KNOWN_DEAD_QUERIES in the same commit as the fix.",
    );
  });
});
