/**
 * videoProbeFixtures — REAL container bytes for the videoProbe tests.
 *
 * Every buffer below was written by a real muxer, not built by hand: ffmpeg
 * 6.0 (static build, johnvansickle.com) from lavfi test sources, then base64-
 * encoded verbatim. They are tiny (a few KB each) because the probe reads
 * container fields and never decodes a frame, so resolution and bitrate are
 * irrelevant to what is being tested — only the BOX / ELEMENT LAYOUT a real
 * muxer produces is, and that is exactly what a hand-built fixture cannot
 * vouch for.
 *
 * The expected values in the tests are ffmpeg's OWN reading of each file
 * (`ffmpeg -i <file>` "Duration:" and "Stream" lines), recorded here beside
 * each fixture, so a test asserts agreement with an independent parser rather
 * than with this module's author.
 *
 * Deliberately NOT a .test.ts file (importing one test file from another runs
 * its suites twice).
 */

function b64(s: string): Buffer {
  return Buffer.from(s, "base64");
}

/**
 * H.264 + AAC, 64x48, 1.50 s; moov AFTER mdat (ffmpeg's default layout).
 * ffmpeg -f lavfi -i testsrc=size=64x48:rate=5 -f lavfi -i sine=frequency=440:sample_rate=8000 -t 1.5 -c:v libx264 -preset ultrafast -crf 51 -c:a aac -b:a 8k -shortest
 * (5702 bytes)
 */
export const PLAIN_MP4: Buffer = b64(
  "AAAAIGZ0eXBpc29tAAACAGlzb21pc28yYXZjMW1wNDEAAAAIZnJlZQAAD/1tZGF03ABMYXZjNjAuMy4xMDAAAjilUtNG7rP2j7fE" +
  "lXctEiRIkSSDatp2radq2nauM7Vxnatpnp2xTtisO1bTtXGdq4zlWU5VtOVbTYsTjsTlWUhAhAhAhElGSjKoyqUyVpTXXK6u7cwN" +
  "2KUCUDAwMDAxs3LLLLLLKblllllllNyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy" +
  "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy8AAACUwYF//9P3EXpvebZ" +
  "SLeWLNgg2SPu73gyNjQgLSBjb3JlIDE2NCByMzEwNiBlYWE2OGZhIC0gSC4yNjQvTVBFRy00IEFWQyBjb2RlYyAtIENvcHlsZWZ0" +
  "IDIwMDMtMjAyMyAtIGh0dHA6Ly93d3cudmlkZW9sYW4ub3JnL3gyNjQuaHRtbCAtIG9wdGlvbnM6IGNhYmFjPTAgcmVmPTEgZGVi" +
  "bG9jaz0wOjA6MCBhbmFseXNlPTA6MCBtZT1kaWEgc3VibWU9MCBwc3k9MSBwc3lfcmQ9MS4wMDowLjAwIG1peGVkX3JlZj0wIG1l" +
  "X3JhbmdlPTE2IGNocm9tYV9tZT0xIHRyZWxsaXM9MCA4eDhkY3Q9MCBjcW09MCBkZWFkem9uZT0yMSwxMSBmYXN0X3Bza2lwPTEg" +
  "Y2hyb21hX3FwX29mZnNldD02IHRocmVhZHM9MSBsb29rYWhlYWRfdGhyZWFkcz0xIHNsaWNlZF90aHJlYWRzPTAgbnI9MCBkZWNp" +
  "bWF0ZT0xIGludGVybGFjZWQ9MCBibHVyYXlfY29tcGF0PTAgY29uc3RyYWluZWRfaW50cmE9MCBiZnJhbWVzPTAgd2VpZ2h0cD0w" +
  "IGtleWludD0yNTAga2V5aW50X21pbj01IHNjZW5lY3V0PTAgaW50cmFfcmVmcmVzaD0wIHJjPWNyZiBtYnRyZWU9MCBjcmY9NTEu" +
  "MCBxY29tcD0wLjYwIHFwbWluPTAgcXBtYXg9NjkgcXBzdGVwPTQgaXBfcmF0aW89MS40MCBhcT0wAIAAAAHNZYiEOghAGPcw3F3X" +
  "/wsjJ8AEP1xZ8fG+G+/X98ABZkQ2VWcPhXf8Aj55E+AAR88ifAnGqo7eZ2KInwA/hCDkD///jgCANyALZ/C///iAAHAABAA8Y723" +
  "wAw//4Qg5AAv//4OAgACBv/hL/r/4OAAeL/gIvW2//hCAQfQcDL8T/+O6ZIjJhE/lEwABAEEx+8ZIP///w43dGYL5KgFT3ZwaNaD" +
  "8AWtpjYx6/xi/fHb/8dAddJk9fB1v+DrfB1v8O0z//w0pn//rUnXcdAcSmmexiNXP1VzVXP//4epn//joBUka5bSPjFz8xyUk3Hb" +
  "4AMokemAFBBp/f5dCzL9bLKzl60ggAd2CF2kWxqyw62q6qDFS1UvyZllFS8B9NIbGPQ6BgNSl/+bTbgB/SYAAgBegFNcfu4dI5ZW" +
  "cs0/15WcsrcvwAzEKQBLSPV21+VnLDpDltzdtvJmWTMvx0HC9P+3t8AaD4AAgGoAGQm3+HmUsPMUvw8xSw8xS/AEYAL2Aso0279y" +
  "tyyZl+qllFS/CEAIvdptH655zD7cul3AA/mYcnp6ghv1UolLVfKOY/gATo0CZlmIFYd//t/t0AMu5sofgAyaPwk9/oNhUsoqX8AB" +
  "AJzZPRVEuhlEuxdkvn2+f/4v/P9euONauR/0/T/8P/P8eePN6l1n/T8/+n/z9dccX1WpP/T8/+n/3+utccaXSZdGKPAy6MSccujF" +
  "HhpmbDFc00y5lzPNNMlmjZZfkP14LsEDhKMJ1nOiqoxjUGjoojoN0DqFBug3VPRRWFK2bIt7Zs2Ed9IuEbRLi+yewjs2bIr8iRwV" +
  "lzLOdiPPOc51KVGpSp555551TqnVOqeeedQnUpU888+ydRvo30UUvzqXrSh2OfG12DfE7h+CnOqHm5p1Tz80/N8lTkSEHR8tihwB" +
  "EvKK4uZlZzz3+f+n/261xxepcuXWq0ve+KqKA9yD/wBn0A/xmA99AP8AOhPuCHv76IQPgB33Af+DB33IP/DYT7kD/DYHuQPmzAe+" +
  "gD4zBPvoMJL+HiP4xxBT+PhO/iPJ9j+HiR/j4SwYwBIMQIBEIgAEwqFg2xAJTAcAAAGyQZogFa8VFYrFYrcAZGKM0PgADIxRmh8C" +
  "fv//9fFYrFYAX+FUX8d8wwc8zMfADD/zQ/i/yHyHyBs+GPIf+/ip49/3d393dw2LUf//yO57XPK+qqv+/wS6X7jwI24/70f8VADE" +
  "8Wz3WgAz8ARSaE/Aj0q8q4ytdf9ffsLU8LxIi70eBhasO9OUPcx4HsMHFYIdgHX//2EM/+Q7D5fzXD5bP/PUAaIWtqWfreomUqPl" +
  "Kj5T//89xH54ttv4iBVFOMmPJP++GwTplCdMoTp///4qKAMAHsxayKxP0eg6BciLUDFDsvA5wzfUCwOzao5GcaYOUSOfYC1psTwC" +
  "PWXl/vIMPmwxBglbAOvFb4rFYUeJljckjxI9KWHy+Kqsb4oYoGGJR0DFDlj+Q5W0Byto/m+LimrvKfX7jz/J/fFGK1XNbo5Wz/vZ" +
  "/xXFsHgD+KNsDsIuSgWDDZabwcRaSwIkOtR+bm/sx1/6riTxQxPktelIyWv+K7agBPEPy1F2Wf/wBgAMXVqAYntI8Y/AIb5Ujff6" +
  "4GWDiCHBsZFmWe4h+KMUcSmKAMnPRI78U/n+CTx8KDwArv8BAjKH5n+n9P1z7a7/T//l//xvWt9d39fbnj6/b+f7fUeEZ14oFf+7" +
  "96im/e37ySm9TeUpoU379+++/fffv33sFQzhLfv376AgFw1BYKhYKABEIBcJgCoSACIQAEwmFABQAIAOAPwyhCARQhBu3/jfp3+n" +
  "/+j/+XV8bx93vk4+f1/j64eu+qlQDSsen+1PT/Ylyz/2en0kmEnAwMDAzIGwZAwMDYsFQ2haIoCATCYWCoVCQSCUQiAJgCwUCQAX" +
  "AEwmFgsGeARFLgOAAAAAxEGaQBavfnhIDyA9O3P/P/7WVVVX/XG2Cy748AptH/wl+1///5OWnT//iuKAYgCoxDxRgYoUsYxVt95V" +
  "LeXcUYr8S4W/+KMUeKMUYlwlfeSviV934riX9Qcn38mUuAxW++J8U8UxHhsyjjnOOHc8S/u2lZZtP/xXFAGKA83FMWTlhvHLeqUv" +
  "+Li/FZ3C/nzxcU8UxQxOhJZc7iIMt/FVUnvcHEus64AbRsJL7l5Y8UYketVCOM8F5bJ1l8R66iHk30XU5/AA/jKH5n8/2/fPlnr/" +
  "/D//Pd8eNJ9/nvj4/b/n/p8cV3lznXdAvw2bFVtmzpbYUiNmxs6IN2zZs2R2R2bNmzZYLBnCmzZs2UBELhsCxs2eULACQSBMIhYA" +
  "ZwqEgkCIABMKgCQARAcAAACYQZpgFqE8VxQDBw74oxRgrFLChu/JXxK+/FZ/xcOst/VfFYo8UGKDDoyxzT6UZYnFl/iv6YoA/wPY" +
  "fvimKHimLi4W+5N8qaP3fim/1aMK1/iuKAMHH+KYpjbHLC4/eSFkdz4unu6z0B938UxTxTFMm+JvvRGWRGW/xX9sUA460fAxhS3x" +
  "RijxRisKviUfeSj45p/4o2deIacA/jKH5n7/x+M/bz3+n//L//jd6cevqvGa18/4/jzL7y29KBaG/eopv3037yjfvX3lKXU379++" +
  "++99++6w32uLBigKAiEwuFgsGcKABALhcMgAoFgBIEABcJhULBtiERKYDgECMofmfr9v159bfb//X//PetbzNfj5518fp/n+/3p6" +
  "zgndAtASV1aqw1FYD8/7HVF+P9tWrVq1atWrVq1TCoVCWrUUBALhmCwawoGcEQgEQBcAWCgUAC4AuGMLACgAQAcAAACcQZqAFqE8" +
  "VxQxXijEvArhUHpj8lfP/xX1E+K+MMiWv4oxR4oxLwq+J1l5KPiV9/iuovg8fFAchrLciCjoXI5b8UxTxHi5N8TH3ncO5/ifFP7Y" +
  "Usv4riAWBfFMnNUdE8Tos74v3EP+0kGV8UxTxTEeSWSIy3kx8zP4ruK8HRcUA7PmbClKxe/FGKPEvFZ44SvulZY9z6rl4o/l5K+8" +
  "AP4yicN38/2/x39vPf5//1f/z6vXf1+frM3ft+f9v+P13O+dXz1VABfn9PoED6fT6OhYCZaPoN30AgBDt+mv6a6KKBrooomNn4bN" +
  "hYMsRQEAmEwyB6QkGUEQBAAXAFQkFAQCIAmGMJBlCsAiKXAcAAAAnEGaoBahPFcHNxR4o52J7nJ1l/bF8XFNGuoaMt8UYo8Ubh0Z" +
  "YlH35Osq/4rqnigMUAfhUHw2xy34pinimLogyxJZeiyyz3/i4plpwt8Tff4rg0ehZ4p32KIMt0Rlv6b7ijOkG9xLnimKHimpN8cc" +
  "6Iyyzv8V3bxQMUDcoIBxihSwxQUt+KDFHisVpRlkoy3nuJWW/4oxXkjnNCdZeAD+Mofmfz/T9e/fjv9P/+X//G74vnd/j7ZPP2/0" +
  "/p7TXe5RuAnv371jfvoElN6+8pS6m/fv33372/fv3z377rBUKdt+/fQEQuFwuGkKBQAIhoDAFQBQKABAIACYVCoAkAEQHAD+Mofm" +
  "f4/p+vPiePH/+H/+e9azjx8ZvnX1/H/P+vtbxV1KQFa6tSSurVWFSXLVqV1NXVFy1atWqGrU1atWqYekLBigKAiEw1Bc1avdAZQB" +
  "QEQmEwqAMoVCQIBcAAqAJBaIREsIDgAAAJxBmsAWoTxXFYo8/Vw6Mt1fT9VxPin4djJvvxRijxL4kcSjLeSvr/iuoPH8UAYVAaDT" +
  "QRFHR65HLVUdH4pi+Li5N8s95evub4pi7TvklkiMt/iuXinpvIW+6hf/iHijd81uhKMt+KYp4vRGWRGW9mfxXcHRfFAMLAaHwRtl" +
  "F+0AZalKj8UYrxWKyUfHuc5oW/FxD8UYoxz18KviV98BMDKL5hSqzv/0/+dau7kkkSRJEQAo7qr5ME1lHfVhIfGO7ffJhIMeoXDp" +
  "xNdGyrwk6cTXb7+zCSso9tXhJhjXdvv7MJK8Y7t/hJhjXdHtqwkPjHdvvkwxruj21eEmGMd2+/swTWUe2rwkwxru339mEleMe3f4" +
  "SYY13R7ajyV4x7d9/ZhjXdHtqwkPjGzff2Yd1d0e2rwkwxNdHf2YSVlHdVfJgRro76sJDka6q+TBJi4BQDKL5ilKz16+vaauSWkk" +
  "iSIiAafdmghbacdfSRoczWR2aCFvQFvp9w2oZ30zGhzNZHX4Cb0ONPuzGhbacdfgmbhcafdmghb0OOvpmbhzNZHZoIW9Dmd9Mxoc" +
  "zWR1+Am4XM77s0EObRkdfgmbhczvuzQQt6Mjr8EzcOZp908ELehzO/BM3DmayOngJvQ5nfTM3DmayOvwTNwuZ33ZjQttOOvwTNwu" +
  "NPunNC2047wAAAYhbW9vdgAAAGxtdmhkAAAAAAAAAAAAAAAAAAAD6AAABdwAAQAAAQAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAA" +
  "AAABAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAod0cmFrAAAAXHRraGQAAAADAAAAAAAA" +
  "AAAAAAABAAAAAAAABXgAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAABAAAAAAEAAAAAwAAAA" +
  "AAAkZWR0cwAAABxlbHN0AAAAAAAAAAEAAAV4AAAAAAABAAAAAAH/bWRpYQAAACBtZGhkAAAAAAAAAAAAAAAAAAAoAAAAOABVxAAA" +
  "AAAALWhkbHIAAAAAAAAAAHZpZGUAAAAAAAAAAAAAAABWaWRlb0hhbmRsZXIAAAABqm1pbmYAAAAUdm1oZAAAAAEAAAAAAAAAAAAA" +
  "ACRkaW5mAAAAHGRyZWYAAAAAAAAAAQAAAAx1cmwgAAAAAQAAAWpzdGJsAAAAvnN0c2QAAAAAAAAAAQAAAK5hdmMxAAAAAAAAAAEA" +
  "AAAAAAAAAAAAAAAAAAAAAEAAMABIAAAASAAAAAAAAAABFExhdmM2MC4zLjEwMCBsaWJ4MjY0AAAAAAAAAAAAAAAAGP//AAAANGF2" +
  "Y0MB9AAK/+EAF2f0AAqRloR7ARAAAAMAEAAAAwCg8SJqAQAGaM4BlGSA//j4AAAAABBwYXNwAAAAAQAAAAEAAAAUYnRydAAAAAAA" +
  "ADQwAAA0MAAAABhzdHRzAAAAAAAAAAEAAAAHAAAIAAAAABRzdHNzAAAAAAAAAAEAAAABAAAAHHN0c2MAAAAAAAAAAQAAAAEAAAAB" +
  "AAAAAQAAADBzdHN6AAAAAAAAAAAAAAAHAAAEKAAAAbYAAADIAAAAnAAAAKAAAACgAAAAoAAAACxzdGNvAAAAAAAAAAcAAAEdAAAG" +
  "oQAACSEAAApPAAALrgAADL0AAA4mAAACxXRyYWsAAABcdGtoZAAAAAMAAAAAAAAAAAAAAAIAAAAAAAAF3AAAAAAAAAAAAAAAAQEA" +
  "AAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAACRlZHRzAAAAHGVsc3QAAAAAAAAAAQAABdwA" +
  "AAQAAAEAAAAAAj1tZGlhAAAAIG1kaGQAAAAAAAAAAAAAAAAAAB9AAAAy4FXEAAAAAAAtaGRscgAAAAAAAAAAc291bgAAAAAAAAAA" +
  "AAAAAFNvdW5kSGFuZGxlcgAAAAHobWluZgAAABBzbWhkAAAAAAAAAAAAAAAkZGluZgAAABxkcmVmAAAAAAAAAAEAAAAMdXJsIAAA" +
  "AAEAAAGsc3RibAAAAH5zdHNkAAAAAAAAAAEAAABubXA0YQAAAAAAAAABAAAAAAAAAAAAAQAQAAAAAB9AAAAAAAA2ZXNkcwAAAAAD" +
  "gICAJQACAASAgIAXQBUAAAAAACGIAAAhiAWAgIAFFYhW5QAGgICAAQIAAAAUYnRydAAAAAAAACGIAAAhiAAAACBzdHRzAAAAAAAA" +
  "AAIAAAAMAAAEAAAAAAEAAALgAAAAWHN0c2MAAAAAAAAABgAAAAEAAAABAAAAAQAAAAIAAAACAAAAAQAAAAQAAAABAAAAAQAAAAUA" +
  "AAACAAAAAQAAAAYAAAABAAAAAQAAAAcAAAACAAAAAQAAAEhzdHN6AAAAAAAAAAAAAAANAAAA7QAAAOEAAAB7AAAAZAAAAGYAAABm" +
  "AAAAYgAAAGEAAABvAAAAYwAAAGYAAACxAAAArgAAADBzdGNvAAAAAAAAAAgAAAAwAAAFRQAACFcAAAnpAAAK6wAADE4AAA1dAAAO" +
  "xgAAABpzZ3BkAQAAAHJvbGwAAAACAAAAAf//AAAAHHNiZ3AAAAAAcm9sbAAAAAEAAAANAAAAAQAAAGF1ZHRhAAAAWW1ldGEAAAAA" +
  "AAAAIWhkbHIAAAAAAAAAAG1kaXJhcHBsAAAAAAAAAAAAAAAALGlsc3QAAAAkqXRvbwAAABxkYXRhAAAAAQAAAABMYXZmNjAuMy4x" +
  "MDA=",
);

/**
 * coded 64x48 with a 90-degree-CLOCKWISE display matrix (0,1,-1,0) — what an iPhone writes for a clip held upright; displays 48x64; 1.80 s.
 * ffmpeg (a 64x48 1.8 s H.264 clip) then: -display_rotation -90 -i clip.mp4 -c copy
 * (3581 bytes)
 */
export const PORTRAIT_MP4: Buffer = b64(
  "AAAAIGZ0eXBpc29tAAACAGlzb21pc28yYXZjMW1wNDEAAAAIZnJlZQAAColtZGF0AAACUwYF//9P3EXpvebZSLeWLNgg2SPu73gy" +
  "NjQgLSBjb3JlIDE2NCByMzEwNiBlYWE2OGZhIC0gSC4yNjQvTVBFRy00IEFWQyBjb2RlYyAtIENvcHlsZWZ0IDIwMDMtMjAyMyAt" +
  "IGh0dHA6Ly93d3cudmlkZW9sYW4ub3JnL3gyNjQuaHRtbCAtIG9wdGlvbnM6IGNhYmFjPTAgcmVmPTEgZGVibG9jaz0wOjA6MCBh" +
  "bmFseXNlPTA6MCBtZT1kaWEgc3VibWU9MCBwc3k9MSBwc3lfcmQ9MS4wMDowLjAwIG1peGVkX3JlZj0wIG1lX3JhbmdlPTE2IGNo" +
  "cm9tYV9tZT0xIHRyZWxsaXM9MCA4eDhkY3Q9MCBjcW09MCBkZWFkem9uZT0yMSwxMSBmYXN0X3Bza2lwPTEgY2hyb21hX3FwX29m" +
  "ZnNldD02IHRocmVhZHM9MSBsb29rYWhlYWRfdGhyZWFkcz0xIHNsaWNlZF90aHJlYWRzPTAgbnI9MCBkZWNpbWF0ZT0xIGludGVy" +
  "bGFjZWQ9MCBibHVyYXlfY29tcGF0PTAgY29uc3RyYWluZWRfaW50cmE9MCBiZnJhbWVzPTAgd2VpZ2h0cD0wIGtleWludD0yNTAg" +
  "a2V5aW50X21pbj01IHNjZW5lY3V0PTAgaW50cmFfcmVmcmVzaD0wIHJjPWNyZiBtYnRyZWU9MCBjcmY9NTEuMCBxY29tcD0wLjYw" +
  "IHFwbWluPTAgcXBtYXg9NjkgcXBzdGVwPTQgaXBfcmF0aW89MS40MCBhcT0wAIAAAAHNZYiEOghAGPcw3F3X/wsjJ8AEP1xZ8fG+" +
  "G+/X98ABZkQ2VWcPhXf8Aj55E+AAR88ifAnGqo7eZ2KInwA/hCDkD///jgCANyALZ/C///iAAHAABAA8Y723wAw//4Qg5AAv//4O" +
  "AgACBv/hL/r/4OAAeL/gIvW2//hCAQfQcDL8T/+O6ZIjJhE/lEwABAEEx+8ZIP///w43dGYL5KgFT3ZwaNaD8AWtpjYx6/xi/fHb" +
  "/8dAddJk9fB1v+DrfB1v8O0z//w0pn//rUnXcdAcSmmexiNXP1VzVXP//4epn//joBUka5bSPjFz8xyUk3Hb4AMokemAFBBp/f5d" +
  "CzL9bLKzl60ggAd2CF2kWxqyw62q6qDFS1UvyZllFS8B9NIbGPQ6BgNSl/+bTbgB/SYAAgBegFNcfu4dI5ZWcs0/15WcsrcvwAzE" +
  "KQBLSPV21+VnLDpDltzdtvJmWTMvx0HC9P+3t8AaD4AAgGoAGQm3+HmUsPMUvw8xSw8xS/AEYAL2Aso0279ytyyZl+qllFS/CEAI" +
  "vdptH655zD7cul3AA/mYcnp6ghv1UolLVfKOY/gATo0CZlmIFYd//t/t0AMu5sofgAyaPwk9/oNhUsoqX8AAAAGyQZogFa8VFYrF" +
  "YrcAZGKM0PgADIxRmh8Cfv//9fFYrFYAX+FUX8d8wwc8zMfADD/zQ/i/yHyHyBs+GPIf+/ip49/3d393dw2LUf//yO57XPK+qqv+" +
  "/wS6X7jwI24/70f8VADE8Wz3WgAz8ARSaE/Aj0q8q4ytdf9ffsLU8LxIi70eBhasO9OUPcx4HsMHFYIdgHX//2EM/+Q7D5fzXD5b" +
  "P/PUAaIWtqWfreomUqPlKj5T//89xH54ttv4iBVFOMmPJP++GwTplCdMoTp///4qKAMAHsxayKxP0eg6BciLUDFDsvA5wzfUCwOz" +
  "ao5GcaYOUSOfYC1psTwCPWXl/vIMPmwxBglbAOvFb4rFYUeJljckjxI9KWHy+Kqsb4oYoGGJR0DFDlj+Q5W0Byto/m+LimrvKfX7" +
  "jz/J/fFGK1XNbo5Wz/vZ/xXFsHgD+KNsDsIuSgWDDZabwcRaSwIkOtR+bm/sx1/6riTxQxPktelIyWv+K7agBPEPy1F2Wf/wBgAM" +
  "XVqAYntI8Y/AIb5Ujff64GWDiCHBsZFmWe4h+KMUcSmKAMnPRI78U/n+CTx8KDwArv8AAADEQZpAFq9+eEgPID07c/8//tZVVVf9" +
  "cbYLLvjwCm0f/CX7X///k5adP/+K4oBiAKjEPFGBihSxjFW33lUt5dxRivxLhb/4oxR4oxRiXCV95K+JX3fiuJf1ByffyZS4DFb7" +
  "4nxTxTEeGzKOOc44dzxL+7aVlm0//FcUAYoDzcUxZOWG8ct6pS/4uL8VncL+fPFxTxTFDE6EllzuIgy38VVSe9wcS6zrgBtGwkvu" +
  "XljxRiR61UI4zwXlsnWXxHrqIeTfRdTn8AAAAJhBmmAWoTxXFAMHDvijFGCsUsKG78lfEr78Vn/Fw6y39V8VijxQYoMOjLHNPpRl" +
  "icWX+K/pigD/A9h++KYoeKYuLhb7k3ypo/d+Kb/VowrX+K4oAwcf4pimNscsLj95IWR3Pi6e7rPQH3fxTFPFMUyb4m+9EZZEZb/F" +
  "f2xQDjrR8DGFLfFGKPFGKwq+JR95KPjmn/ijZ14hpwAAAJxBmoAWoTxXFDFeKMS8CuFQemPyV8//FfUT4r4wyJa/ijFHijEvCr4n" +
  "WXko+JX3+K6i+Dx8UByGstyIKOhcjlvxTFPEeLk3xMfedw7n+J8U/thSy/iuIBYF8Uyc1R0TxOizvi/cQ/7SQZXxTFPFMR5JZIjL" +
  "eTHzM/iu4rwdFxQDs+ZsKUrF78UYo8S8VnjhK+6Vlj3PquXij+Xkr7wAAACcQZqgFqE8Vwc3FHijnYnucnWX9sXxcU0a6hoy3xRi" +
  "jxRuHRliUffk6yr/iuqeKAxQB+FQfDbHLfimKeKYuiDLEll6LLLPf+LimWnC3xN9/iuDR6FninfYogy3RGW/pvuKM6Qb3EueKYoe" +
  "Kak3xxzojLLO/xXdvFAxQNyggHGKFLDFBS34oMUeKxWlGWSjLee4lZb/ijFeSOc0J1l4AAAAnEGawBahPFcVijz9XDoy3V9P1XE+" +
  "Kfh2Mm+/FGKPEviRxKMt5K+v+K6g8fxQBhUBoNNBEUdHrkctVR0fimL4uLk3yz3l6+5vimLtO+SWSIy3+K5eKem8hb7qF/+IeKN3" +
  "zW6Eoy34pini9EZZEZb2Z/FdwdF8UAwsBofBG2UX7QBlqUqPxRivFYrJR8e5zmhb8XEPxRijHPXwq+JX3wAAAJdBmuAWoTxXFGKP" +
  "wuLIlff/U3xTFDWcNBliQsvxRij3cOjLEo+//4rl4oA8UAYkWUwWRy3G2HLHsfimL4umSWR0g9Z6P4qxTxTFOFvuTfF/8VxTF/Jv" +
  "juf9xD8UYo/Cr4lH34pink6iDh+mzz+K7YoB4oBiCyblYvcOoXjsfijFHittKMslGW9eyr+LYo8UYo4lzJ1klGW+AAAAwEGbABah" +
  "PFcUZ/qLhV9X1X1F8UxTNRKR+dwm++KDEv8Kj5Oye/nI8JwAdYOyIYtb16xTFPJBwRClsqK4Zt9fpAV9HAHPuY43G7+/2ACE13rs" +
  "D8AFCrIACJ0KmfKmut33cHBMPNAOIR7QAIQ01tNMDsFfR/FcSeT7iskso+4hp7ivFGKNwlujk4skoy34piP9EZZQv/8VxIHigHg2" +
  "KhYwrypDFClvpSoLfxWK8VqW3xvp+KMV4rFGGhGSvvJXxKPvgAAAA0xtb292AAAAbG12aGQAAAAAAAAAAAAAAAAAAAPoAAAHCAAB" +
  "AAABAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAACAAACd3RyYWsAAABcdGtoZAAAAAMAAAAAAAAAAAAAAAEAAAAAAAAHCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAD//wAA" +
  "AAAAAAAAAAAAAAAAAAAAAEAAAAAAQAAAADAAAAAAACRlZHRzAAAAHGVsc3QAAAAAAAAAAQAABwgAAAAAAAEAAAAAAe9tZGlhAAAA" +
  "IG1kaGQAAAAAAAAAAAAAAAAAACgAAABIAFXEAAAAAAAtaGRscgAAAAAAAAAAdmlkZQAAAAAAAAAAAAAAAFZpZGVvSGFuZGxlcgAA" +
  "AAGabWluZgAAABR2bWhkAAAAAQAAAAAAAAAAAAAAJGRpbmYAAAAcZHJlZgAAAAAAAAABAAAADHVybCAAAAABAAABWnN0YmwAAAC+" +
  "c3RzZAAAAAAAAAABAAAArmF2YzEAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAQAAwAEgAAABIAAAAAAAAAAEUTGF2YzYwLjMuMTAw" +
  "IGxpYngyNjQAAAAAAAAAAAAAAAAY//8AAAA0YXZjQwH0AAr/4QAXZ/QACpGWhHsBEAAAAwAQAAADAKDxImoBAAZozgGUZID/+PgA" +
  "AAAAEHBhc3AAAAABAAAAAQAAABRidHJ0AAAAAAAALq8AAC6vAAAAGHN0dHMAAAAAAAAAAQAAAAkAAAgAAAAAFHN0c3MAAAAAAAAA" +
  "AQAAAAEAAAAcc3RzYwAAAAAAAAABAAAAAQAAAAkAAAABAAAAOHN0c3oAAAAAAAAAAAAAAAkAAAQoAAABtgAAAMgAAACcAAAAoAAA" +
  "AKAAAACgAAAAmwAAAMQAAAAUc3RjbwAAAAAAAAABAAAAMAAAAGF1ZHRhAAAAWW1ldGEAAAAAAAAAIWhkbHIAAAAAAAAAAG1kaXJh" +
  "cHBsAAAAAAAAAAAAAAAALGlsc3QAAAAkqXRvbwAAABxkYXRhAAAAAQAAAABMYXZmNjAuMy4xMDA=",
);

/**
 * QuickTime brand, 48x32, 1.20 s; moov BEFORE mdat (+faststart).
 * ffmpeg -f lavfi -i testsrc=size=48x32:rate=5 -t 1.2 -c:v libx264 -preset ultrafast -crf 51 -movflags +faststart -f mov
 * (1996 bytes)
 */
export const FASTSTART_MOV: Buffer = b64(
  "AAAAFGZ0eXBxdCAgAAACAHF0ICAAAAMXbW9vdgAAAGxtdmhkAAAAAAAAAAAAAAAAAAAD6AAABLAAAQAAAQAAAAAAAAAAAAAAAAEA" +
  "AAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAoN0cmFrAAAAXHRr" +
  "aGQAAAADAAAAAAAAAAAAAAABAAAAAAAABLAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAABA" +
  "AAAAADAAAAAgAAAAAAAkZWR0cwAAABxlbHN0AAAAAAAAAAEAAASwAAAAAAABAAAAAAH7bWRpYQAAACBtZGhkAAAAAAAAAAAAAAAA" +
  "AAAoAAAAMAB//wAAAAAALWhkbHIAAAAAbWhscnZpZGUAAAAAAAAAAAAAAAAMVmlkZW9IYW5kbGVyAAABpm1pbmYAAAAUdm1oZAAA" +
  "AAEAAAAAAAAAAAAAACxoZGxyAAAAAGRobHJ1cmwgAAAAAAAAAAAAAAAAC0RhdGFIYW5kbGVyAAAAJGRpbmYAAAAcZHJlZgAAAAAA" +
  "AAABAAAADHVybCAAAAABAAABOnN0YmwAAACqc3RzZAAAAAAAAAABAAAAmmF2YzEAAAAAAAAAAQAAAABGRk1QAAACAAAAAgAAMAAg" +
  "AEgAAABIAAAAAAAAAAEUTGF2YzYwLjMuMTAwIGxpYngyNjQAAAAAAAAAAAAAAAAY//8AAAA0YXZjQwH0AAr/4QAXZ/QACpGWjWwE" +
  "QAAAAwBAAAADAoPEiagBAAZozgGUZID/+PgAAAAAEHBhc3AAAAABAAAAAQAAABhzdHRzAAAAAAAAAAEAAAAGAAAIAAAAABRzdHNz" +
  "AAAAAAAAAAEAAAABAAAAHHN0c2MAAAAAAAAAAQAAAAEAAAAGAAAAAQAAACxzdHN6AAAAAAAAAAAAAAAGAAADvwAAABkAAAAtAAAA" +
  "LQAAADAAAAAvAAAAFHN0Y28AAAAAAAAAAQAAAzsAAAAgdWR0YQAAABipc3dyAAxVxExhdmY2MC4zLjEwMAAAAAh3aWRlAAAEmW1k" +
  "YXQAAAJTBgX//0/cRem95tlIt5Ys2CDZI+7veDI2NCAtIGNvcmUgMTY0IHIzMTA2IGVhYTY4ZmEgLSBILjI2NC9NUEVHLTQgQVZD" +
  "IGNvZGVjIC0gQ29weWxlZnQgMjAwMy0yMDIzIC0gaHR0cDovL3d3dy52aWRlb2xhbi5vcmcveDI2NC5odG1sIC0gb3B0aW9uczog" +
  "Y2FiYWM9MCByZWY9MSBkZWJsb2NrPTA6MDowIGFuYWx5c2U9MDowIG1lPWRpYSBzdWJtZT0wIHBzeT0xIHBzeV9yZD0xLjAwOjAu" +
  "MDAgbWl4ZWRfcmVmPTAgbWVfcmFuZ2U9MTYgY2hyb21hX21lPTEgdHJlbGxpcz0wIDh4OGRjdD0wIGNxbT0wIGRlYWR6b25lPTIx" +
  "LDExIGZhc3RfcHNraXA9MSBjaHJvbWFfcXBfb2Zmc2V0PTYgdGhyZWFkcz0xIGxvb2thaGVhZF90aHJlYWRzPTEgc2xpY2VkX3Ro" +
  "cmVhZHM9MCBucj0wIGRlY2ltYXRlPTEgaW50ZXJsYWNlZD0wIGJsdXJheV9jb21wYXQ9MCBjb25zdHJhaW5lZF9pbnRyYT0wIGJm" +
  "cmFtZXM9MCB3ZWlnaHRwPTAga2V5aW50PTI1MCBrZXlpbnRfbWluPTUgc2NlbmVjdXQ9MCBpbnRyYV9yZWZyZXNoPTAgcmM9Y3Jm" +
  "IG1idHJlZT0wIGNyZj01MS4wIHFjb21wPTAuNjAgcXBtaW49MCBxcG1heD02OSBxcHN0ZXA9NCBpcF9yYXRpbz0xLjQwIGFxPTAA" +
  "gAAAAWRliIQ6CEBUca/L3+NjJX3PwAgMjLYGJf1Y5fHyCbv9fu/gAPGj1gwU6KVcdEAsQBtTa+eAeptiYx6b3/bTjVUdg74WIkLH" +
  "8IQYADEC11qtdakCAAIDQAVB3fe733uQABQADoBYWMSFjEhYiQsCQsRIWMSFiJCwEIAo4rlkep73+WdYAzJnQGDLnQZzHmSv3vAH" +
  "rIxA4uFbzGNWAGP5+Gnv9fFAsYAzPHnPaf74WIkLEdAH/6sf+R6aCt8cAEMh/zKQEw23+oufU5owqvgAdM5YAFow0qhFPTC0Kt/q" +
  "IFgGVLCmB2oVQFr1piMYQmcsdBUSPN/3yb2wAiAAEYNIiM2YG7X/cqnLKrlvDyKWHkKWAAnIvHKszDW//EAsSOJ+wnZbiAFgquWn" +
  "YEDoCyRy2K/9u8/PoAJWQlmK4VBDX3/h5ClhSvAXU78AC57CwsKhNzlv93KVLAj5tE+AIBYiMoiA7TFS4AAAABVBmiKJy/9xX+J/" +
  "6i+Lr+q18v3Ff8AAAAApQZpBonE/8Vn7B1Kb4rFbM9u78q8T+f4utVTS+ov+J/8vfFbtHwU1S/AAAAApQZpgqJxMXT/e1rRu7Tis" +
  "/Z/if+qpI/c3xdSUUe8T/3Fdp3dmLk7Kcv4AAAAsQZqA6JxP/ezqLpDDIVitzkX1fE/Fc9xdWUiWSmsmKLxfE/+9xW571kIpXvAA" +
  "AAArQZqg6JxP/bXN13FY+1fR74fE739VSpvtri4ugZCPif+IeK2j275yPpvPcA==",
);

/**
 * Matroska/WebM, VP8, 32x24, 2.20 s.
 * ffmpeg -f lavfi -i testsrc=size=32x24:rate=5 -t 2.2 -c:v libvpx -b:v 5k
 * (2240 bytes)
 */
export const VP8_WEBM: Buffer = b64(
  "GkXfo59ChoEBQveBAULygQRC84EIQoKEd2VibUKHgQJChYECGFOAZwEAAAAAAAiQEU2bdLpNu4tTq4QVSalmU6yBoU27i1OrhBZU" +
  "rmtTrIHWTbuMU6uEElTDZ1OsggEjTbuMU6uEHFO7a1Osggh67AEAAAAAAABZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVSalmsCrXsYMPQkBNgIxM" +
  "YXZmNjAuMy4xMDBXQYxMYXZmNjAuMy4xMDBEiYhAoTAAAAAAABZUrmvIrgEAAAAAAAA/14EBc8WIkVSnK9D9hxecgQAitZyDdW5k" +
  "iIEAhoVWX1ZQOIOBASPjg4QL68IA4JCwgSC6gRiagQJVsIRVuYEBElTDZ/tzc59jwIBnyJlFo4dFTkNPREVSRIeMTGF2ZjYwLjMu" +
  "MTAwc3PWY8CLY8WIkVSnK9D9hxdnyKBFo4dFTkNPREVSRIeTTGF2YzYwLjMuMTAwIGxpYnZweGfIokWjiERVUkFUSU9ORIeUMDA6" +
  "MDA6MDIuMjAwMDAwMDAwAAAfQ7Z1RtHngQCjQpuBAACAEBMAnQEqIAAYAABHCIWFiIWEiAICAnW6JMG+A/gr+o3NhaX9sP07ygnw" +
  "H8R/iX4Kb0j+mf4Qe4D/AecB/pvtTfwH/JfwHqAfUB/inWA/wH+A+g3/eP5B8AP6Z+gndxPwH8Ev2e6Y/0ByQn1H8dtED/Mfwe/Y" +
  "meXceY/XfxV9QvxF7AP6T/2H8ov6zyAP6A+1k0HT9Z9paCSrVlxs9Fe32IgA/v//FviAh1UMQ/ZifCrvqjuNDrG4v3sqUatDwAfB" +
  "n/iylL1IoYNHz3NmG+XB7In614zndEqWsVVXIrp/98MnTPAR+oH2MTtTLToWI3DDQt65+zgBhnDKSn7HZv7LO5pNgS12AB/a8Qt3" +
  "rS8f3bIZwe5rDzT4jj2j5iiy/ZDd05wohSChM3/9n1pQCm6y6uMCle98T+xrz75MkS3Pt7xCSgm9J7YBnbENUsXS3frV6JYQyjzk" +
  "Mfx2yi8GVlk9NH8UMu36yjo+/7JfIL82TJ/uyfqHxSSOpzYLuwf6u241+UB//TZknVK2LQx5J5IlGAnTYbTxm5zD+jLidGNixSgp" +
  "jA7YOUGuga80Pxhu7WD2xD+T7XUrv6BOu7YGmwZd/70H5fnhoQMoJNoEF1EAfnLvWW/hdnd4BRdn/KxeWkXe/juZU9sIKVLDTCx/" +
  "M6GK7QKfx/kpx94Xvs7e3qRPz4NR4FGgtcPUj2jLHlYvRaLxsrDefPuWoVRU6lwSxqkf//qPRFKL/07lf0wvjaPyD66Dl2UwwcNX" +
  "f5Yly78HQyfzzKNIfe5l6e9dfzTwWUEQKmb9Cd30ginoO0hZRrUnh2y5xOXcswCfNfUJerULOOeV/2smkdxPXoRxBbPq6wwjeqe4" +
  "H/nRX5L0nRnakf/6CQ0N/EfabvAAo+iBAMgAUQMAEBCIABzD5nQzAuYj/9uPZ/k24VYBx44OAFTkDGcjJlP7UM3ITEX6KeQAAAAA" +
  "AAAAdrUReYAAP766BwUwAAdDUztM7Mf8YyGzJpCcCuwAAAAAAAAAAu8MAAEYYISQYAAAAKPpgQGQAJECABAQmAAYAmf/d/yP/xcB" +
  "c6MK4eJA/I8KpFIXAk7OFNaUrRFjN/lvwwGeWC0xBsxQcAAH2yQS+MAAD7e1d9KRiq+IXPPDTQDUoUIAAAAAAAACgwynDg7ZgywA" +
  "AOLlgT2KgAAAo9mBAlgAcQIAERCoABgEP/M372AEfuAi4HlIAPiWSGKgCyilml2sLIFClaoAAJNK3pQAPP4OAF/Qhawlxf6FGnXy" +
  "MYWL7IyP0fEwnQDgAvNbayBYWKD+XCDwAKPcgQMgAHECAA0QsAAYA3f8ogo+AvdCFkQFHADf8cqkFEvUT4KD8pphX7C8Iz/pex9S" +
  "IAG39UQAA/XwbgApQHixiZIACf0T05xasYdQPx31ATaBoAB/BwAFlvMAAACj2IED6ADxAQARELgAGAAkQC/0AWxAUcDMFi+UnIKJ" +
  "kepboG9Bb5YkLgITdy0wdkQIAA/g+3MpAACOoOJNI/oi7Bi2sRKD2Fn8AaXUW4cQWoAAK1DgOKIAAACj0oEEsAAxAgAREMAAGAE7" +
  "/HkAn9gEvA8pAPBA8MWFD8AZgSG+RoX8QJCjK1AABQ7QH0gABMjzLJyVWJvSR+qtK3FxCIvgG1rIAACDxCOA4ogAAACjQS2BBXgA" +
  "kQcADRAQFHrS3vtXmtKu6kT+3//M/oBsAO5m6gDzt1Ir/P/k/8kIwgff/Igq+b/q3VHFv9RDfKA/mVLCk/YAxfQZY2TDa3t2RgDC" +
  "4BA0Lv2L8sPaV45FsuwOTHjjgodmknovXKp80R3psTFa762M9xwWk5W0ImvYtuspl6q2vPFA1Cl70mDZazTfJGKmK0gIdVj80Oox" +
  "sgiA9J7/MohGq/UWgUGC6cs5df8GxlDpfsDveQau/IDt6NYUHwjgz1gVZH+ptBqhP6HRq4HOYXzyvLPToPpPWj5BcjgX+RGZIoFt" +
  "7DtEkY3n7XXHV8TtekuHfQoaGkyH4yVbAqIt2LzVLtK1K/9EfEL8ez+ouhP4ZOXgOcldaTq//7Wdb/jfx+hXkNDYqk/mD4AAo72B" +
  "BkAA8QEAExEEABu4kAWgB34gOiFQ+YN+SM6dp5wBIwAAIVwwTAAF/HMKY0UdMMI3gAmXQAAASKdgAAAAo8GBBwgAMQIAKREMABgA" +
  "WX8egNHLhkYCtwCa3DGGkNIAKpDiSAHCUAYJgACJjIQx3RKzz6AiEFN+QAABQX4p2AAAAKPAgQfQAPEBACIRGAAYACRAL/QBa15w" +
  "AMv9FT6lbcDQwAACB9cAAJtMRAAAIgbpri0+J1fpIyetaQAAAI/abgAAABxTu2uRu4+zgQC3iveBAfGCAaPwgQM=",
);

/**
 * fragmented MP4 with an EMPTY moov (mvhd duration 0, no mehd): 3.00 s exists only in moof/traf/trun.
 * ffmpeg -f lavfi -i testsrc=size=32x24:rate=5 -t 3 -c:v libx264 -preset ultrafast -crf 51 -g 5 -movflags frag_keyframe+empty_moov
 * (3059 bytes)
 */
export const FRAGMENTED_MP4: Buffer = b64(
  "AAAAJGZ0eXBpc29tAAACAGlzb21pc282aXNvMmF2YzFtcDQxAAAC7W1vb3YAAABsbXZoZAAAAAAAAAAAAAAAAAAAA+gAAAAAAAEA" +
  "AAEAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAIAAAHwdHJhawAAAFx0a2hkAAAAAwAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAA" +
  "AQAAAAAAAAAAAAAAAAAAQAAAAAAgAAAAGAAAAAABjG1kaWEAAAAgbWRoZAAAAAAAAAAAAAAAAAAAKAAAAAAAVcQAAAAAAC1oZGxy" +
  "AAAAAAAAAAB2aWRlAAAAAAAAAAAAAAAAVmlkZW9IYW5kbGVyAAAAATdtaW5mAAAAFHZtaGQAAAABAAAAAAAAAAAAAAAkZGluZgAA" +
  "ABxkcmVmAAAAAAAAAAEAAAAMdXJsIAAAAAEAAAD3c3RibAAAAKtzdHNkAAAAAAAAAAEAAACbYXZjMQAAAAAAAAABAAAAAAAAAAAA" +
  "AAAAAAAAAAAgABgASAAAAEgAAAAAAAAAARRMYXZjNjAuMy4xMDAgbGlieDI2NAAAAAAAAAAAAAAAABj//wAAADVhdmNDAfQACv/h" +
  "ABhn9AAKkZaJficBEAAAAwAQAAADAKDxImoBAAZozgGUZID/+PgAAAAAEHBhc3AAAAABAAAAAQAAABBzdHRzAAAAAAAAAAAAAAAQ" +
  "c3RzYwAAAAAAAAAAAAAAFHN0c3oAAAAAAAAAAAAAAAAAAAAQc3RjbwAAAAAAAAAAAAAAKG12ZXgAAAAgdHJleAAAAAAAAAABAAAA" +
  "AQAAAAAAAAAAAAAAAAAAAGF1ZHRhAAAAWW1ldGEAAAAAAAAAIWhkbHIAAAAAAAAAAG1kaXJhcHBsAAAAAAAAAAAAAAAALGlsc3QA" +
  "AAAkqXRvbwAAABxkYXRhAAAAAQAAAABMYXZmNjAuMy4xMDAAAACEbW9vZgAAABBtZmhkAAAAAAAAAAEAAABsdHJhZgAAACR0Zmhk" +
  "AAAAOQAAAAEAAAAAAAADEQAACAAAAANhAQEAAAAAABR0ZmR0AQAAAAAAAAAAAAAAAAAALHRydW4AAAIFAAAABQAAAIwCAAAAAAAD" +
  "YQAAABEAAAAhAAAAJQAAACYAAAPmbWRhdAAAAlEGBf//TdxF6b3m2Ui3lizYINkj7u94MjY0IC0gY29yZSAxNjQgcjMxMDYgZWFh" +
  "NjhmYSAtIEguMjY0L01QRUctNCBBVkMgY29kZWMgLSBDb3B5bGVmdCAyMDAzLTIwMjMgLSBodHRwOi8vd3d3LnZpZGVvbGFuLm9y" +
  "Zy94MjY0Lmh0bWwgLSBvcHRpb25zOiBjYWJhYz0wIHJlZj0xIGRlYmxvY2s9MDowOjAgYW5hbHlzZT0wOjAgbWU9ZGlhIHN1Ym1l" +
  "PTAgcHN5PTEgcHN5X3JkPTEuMDA6MC4wMCBtaXhlZF9yZWY9MCBtZV9yYW5nZT0xNiBjaHJvbWFfbWU9MSB0cmVsbGlzPTAgOHg4" +
  "ZGN0PTAgY3FtPTAgZGVhZHpvbmU9MjEsMTEgZmFzdF9wc2tpcD0xIGNocm9tYV9xcF9vZmZzZXQ9NiB0aHJlYWRzPTEgbG9va2Fo" +
  "ZWFkX3RocmVhZHM9MSBzbGljZWRfdGhyZWFkcz0wIG5yPTAgZGVjaW1hdGU9MSBpbnRlcmxhY2VkPTAgYmx1cmF5X2NvbXBhdD0w" +
  "IGNvbnN0cmFpbmVkX2ludHJhPTAgYmZyYW1lcz0wIHdlaWdodHA9MCBrZXlpbnQ9NSBrZXlpbnRfbWluPTEgc2NlbmVjdXQ9MCBp" +
  "bnRyYV9yZWZyZXNoPTAgcmM9Y3JmIG1idHJlZT0wIGNyZj01MS4wIHFjb21wPTAuNjAgcXBtaW49MCBxcG1heD02OSBxcHN0ZXA9" +
  "NCBpcF9yYXRpbz0xLjQwIGFxPTAAgAAAAQhliIQ6CEA0G2OHf4WbmTNz8ACBv4ctoKKjfc3f6//4ACMzGqIig29mFxAI+eRPgRg1" +
  "VHZ/v+2DD//CEAMzF0gBF7+EXlvnLEQsAAQv3jtkBQAT4yQf/4ACabSaQAFt+C94AtbTGxj1//8dChelw1WR26bncyXc/AHQkQ/B" +
  "VcLYkCZFWcmQdCMgsG0h4ZkVBtL/gAJJC3/EPJq2hXgYNIKgykVNIMXuNO+YHcKUjyZH4OUjhM//x0CKZpXJpttzUhfT3PsOfYA4" +
  "XIJBgcPBmQeDMjoIyOgjIgEyagt6TKeTtzJ25gAQn7DB1LhCFg08goPSKDyLz0lPHCZGQ8eSa0+TP5ERLmHiJc4AAAANQZoin1+t" +
  "/83/93vWvwAAAB1BmkKfN/x1lq2XNkmFwuPx+Javm/65pJWlaVJZNwAAACFBmmCp81qk/+bFJkpJNHwbxr8fmvf7VK7nyzYbCYzD" +
  "R+AAAAAiQZqA6fN/5sxplUsZRHILtIN2qXm/9K0XC5U/DYQgsxxB+AAAAIRtb29mAAAAEG1maGQAAAAAAAAAAgAAAGx0cmFmAAAA" +
  "JHRmaGQAAAA5AAAAAQAAAAAAAAd7AAAIAAAAAQMBAQAAAAAAFHRmZHQBAAAAAAAAAAAAKAAAAAAsdHJ1bgAAAgUAAAAFAAAAjAIA" +
  "AAAAAAEDAAAADQAAACIAAAAgAAAAKAAAAYJtZGF0AAAA/2WIgg6CEA0G2OHf4WbmTNz8ACBv4ctoKKjfc3f6//4ACMzGqIig29mF" +
  "xAI+eRPgRg1VHZ/v+2DD//CEAMzF0gBF7+EXlvnLEQsAAQv3jtkBQAT4yQf/4ACabSaQAFt+C94AtbTGxj1//8dIAXhy7s1KzI7d" +
  "NzuZLufgC3QlOKlgkmRJMnCZVyAt6Ua16Vf/wAEkiTbAQFbdljMGo2ygBi3XA538DoEZLy4GZf//x0A1jNfBbir2cL6e59hz7AA0" +
  "AqE7mR4HgZkQCZHQIyeEyPcfMle0nJnyduZO3MADE9gYKi4IIvi0B4My+g6CMwY0gAyePCRrTOk8iIlzDxEucAAAAAlBmiKfX4vv" +
  "eoAAAAAeQZpCnzf+1SNlmQf5HfHrXzf+9xDhcqfhsszLjvyAAAAAHEGaYKnzf+scZf82GwmMzzf+XJ882WZSHWRtVsoAAAAkQZqA" +
  "6fN97zYbGZI0y1jLHWWrZbTSSXm+1VS4XD4/C5fn3d3gAAAAhG1vb2YAAAAQbWZoZAAAAAAAAAADAAAAbHRyYWYAAAAkdGZoZAAA" +
  "ADkAAAABAAAAAAAACYEAAAgAAAABAQEBAAAAAAAUdGZkdAEAAAAAAAAAAABQAAAAACx0cnVuAAACBQAAAAUAAACMAgAAAAAAAQEA" +
  "AAAPAAAAJAAAACYAAAAjAAABhW1kYXQAAAD9ZYiEEoIQDQG2OHf4WbmTNz8ACBv4ctoKKjfc3f6//4ACMzGqIig29mFxAI+eRPgR" +
  "g1VHZ/v+2DD//CEAMzCsmBi95fwQ7Wt84WIgWAAIX7x2yAoAJ8ZIP/8ABNNpNIAC2/Be8AWtpjYx6//+OgUpbDyOi1tLI/c7mS7n" +
  "4AhMlQ1jwz2v4f9tONv/gAJJSbYCAV67JKUJJmcJkAIW74HO+BobIUfiQNkK/v/8dAuj3xO3bP0cnNPc8sOeWABQhUScyPAPw5Sr" +
  "B2ClKMWxJMhwGaThM/J25k7cwARH7BhVVDBVzhMg8GZPJkdBGQbpFnAMnnoTWsXeRES5h4iXOAAAAAtBmiKfN/4v/6qqqAAAACBB" +
  "mkKfN/zY0zIvmzaKRScR83/LhcPj8e/fi0Osj4rZQAAAACJBmmCp82lPnqqmIy5Pk2SYqyvm/46y1bLmyTJcnx0mkGqAAAAAH0Ga" +
  "gOnzf9ppJb3kINTYPZsxRn5ta/e9a77lwbw/F+IAAABpbWZyYQAAAFF0ZnJhAQAAAAAAAAEAAAAAAAAAAwAAAAAAAAAAAAAAAAAA" +
  "AxEBAQEAAAAAAAAoAAAAAAAAAAd7AQEBAAAAAAAAUAAAAAAAAAAJgQEBAQAAABBtZnJvAAAAAAAAAGk=",
);

/**
 * AAC in MP4, NO video track, 1.00 s.
 * ffmpeg -f lavfi -i sine=frequency=440:sample_rate=8000 -t 1 -c:a aac -b:a 8k
 * (2175 bytes)
 */
export const AUDIO_ONLY_M4A: Buffer = b64(
  "AAAAHGZ0eXBNNEEgAAACAE00QSBpc29taXNvMgAAAAhmcmVlAAAFPW1kYXTcAExhdmM2MC4zLjEwMAACOKVS00bus/aPt8SVdy0S" +
  "JEiRJINq2natp2radq4ztXGdq2menbFO2Kw7VtO1cZ2rjOVZTlW05VtNixOOxOVZSECECECESUZKMqjKpTJWlNdcrq7tzA3YpQJQ" +
  "MDAwMDGzcsssssspuWWWWWWU3LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL" +
  "LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLwBAJzZPRVEuhlEuxdkvn2+f/4v" +
  "/P9euONauR/0/T/8P/P8eePN6l1n/T8/+n/z9dccX1WpP/T8/+n/3+utccaXSZdGKPAy6MSccujFHhpmbDFc00y5lzPNNMlmjZZf" +
  "kP14LsEDhKMJ1nOiqoxjUGjoojoN0DqFBug3VPRRWFK2bIt7Zs2Ed9IuEbRLi+yewjs2bIr8iRwVlzLOdiPPOc51KVGpSp555551" +
  "TqnVOqeeedQnUpU888+ydRvo30UUvzqXrSh2OfG12DfE7h+CnOqHm5p1Tz80/N8lTkSEHR8tihwBEvKK4uZlZzz3+f+n/261xxep" +
  "cuXWq0ve+KqKA9yD/wBn0A/xmA99AP8AOhPuCHv76IQPgB33Af+DB33IP/DYT7kD/DYHuQPmzAe+gD4zBPvoMJL+HiP4xxBT+PhO" +
  "/iPJ9j+HiR/j4SwYwBIMQIBEIgAEwqFg2xAJTAcBAjKH5n+n9P1z7a7/T//l//xvWt9d39fbnj6/b+f7fUeEZ14oFf+796im/e37" +
  "ySm9TeUpoU379+++/fffv33sFQzhLfv376AgFw1BYKhYKABEIBcJgCoSACIQAEwmFABQAIAOAPwyhCARQhBu3/jfp3+n/+j/+XV8" +
  "bx93vk4+f1/j64eu+qlQDSsen+1PT/Ylyz/2en0kmEnAwMDAzIGwZAwMDYsFQ2haIoCATCYWCoVCQSCUQiAJgCwUCQAXAEwmFgsG" +
  "eARFLgOAAP4yh+Z/P9v3z5Z6//w//z3fHjSff574+P2/5/6fHFd5c513QL8NmxVbZs6W2FIjZsbOiDds2bNkdkdmzZs2WCwZwps2" +
  "bNlARC4bAsbNnlCwAkEgTCIWAGcKhIJAiAATCoAkAEQHAP4yh+Z+/8fjP289/p//y//43enHr6rxmtfP+P48y+8tvSgWhv3qKb99" +
  "N+8o37195Sl1N+/fvvvvffvusN9riwYoCgIhMLhYLBnCgAQC4XDIAKBYASBAAXCYVCwbYhESmA4BJjKL5RCKVWd//2f/z6mrlySR" +
  "aJIgmxitWPShlfctWPShlfderHpqZWL+oGFVwqZX3LVp6UMr7r1Y9NTK+69WPTUyvuvjxwqur7r48emrTXJfHiurTXJf1Y4Vaa0X" +
  "9WK6tNaL+rFdWmtF/ViurT0ov6u6+rT0oX1dy1aelDOrG9WnpqZ1d18+npqZH3Xqx6amV9y1Y4IZPItWIQytC1Y4VMrkvUS6mVgQ" +
  "AcABQDKL5lFUz19v54u7uSSSJIkSCBXPlWybchUGVbJtyFQZWm5tzgTldhGVpnNuRDAhpky3FQIabmdchgfabmW5DAhpuZbkMD7X" +
  "PM65DA+1zzLchgQ1zzLchgQ1zzLc5tyGueZbOaBCufKtnNuQ1z5Vs5tyFc+VbObchXPlaZzbnFQZWmc25xXPlaZNucVBlaZNucVA" +
  "+0yZ1xUD7TJnXFQIaZMtyGB9puZ1yGBDTc3AAAADHm1vb3YAAABsbXZoZAAAAAAAAAAAAAAAAAAAA+gAAAPoAAEAAAEAAAAAAAAA" +
  "AAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAJJdHJh" +
  "awAAAFx0a2hkAAAAAwAAAAAAAAAAAAAAAQAAAAAAAAPoAAAAAAAAAAAAAAABAQAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAA" +
  "AAAAAAAAQAAAAAAAAAAAAAAAAAAAJGVkdHMAAAAcZWxzdAAAAAAAAAABAAAD6AAABAAAAQAAAAABwW1kaWEAAAAgbWRoZAAAAAAA" +
  "AAAAAAAAAAAAH0AAACNAVcQAAAAAAC1oZGxyAAAAAAAAAABzb3VuAAAAAAAAAAAAAAAAU291bmRIYW5kbGVyAAAAAWxtaW5mAAAA" +
  "EHNtaGQAAAAAAAAAAAAAACRkaW5mAAAAHGRyZWYAAAAAAAAAAQAAAAx1cmwgAAAAAQAAATBzdGJsAAAAanN0c2QAAAAAAAAAAQAA" +
  "AFptcDRhAAAAAAAAAAEAAAAAAAAAAAABABAAAAAAH0AAAAAAADZlc2RzAAAAAAOAgIAlAAEABICAgBdAFQAAAAAAJO0AACTtBYCA" +
  "gAUViFblAAaAgIABAgAAACBzdHRzAAAAAAAAAAIAAAAIAAAEAAAAAAEAAANAAAAAHHN0c2MAAAAAAAAAAQAAAAEAAAAJAAAAAQAA" +
  "ADhzdHN6AAAAAAAAAAAAAAAJAAAA7QAAAOEAAAB7AAAAZAAAAGYAAABmAAAAYgAAAKsAAACvAAAAFHN0Y28AAAAAAAAAAQAAACwA" +
  "AAAac2dwZAEAAAByb2xsAAAAAgAAAAH//wAAABxzYmdwAAAAAHJvbGwAAAABAAAACQAAAAEAAABhdWR0YQAAAFltZXRhAAAAAAAA" +
  "ACFoZGxyAAAAAAAAAABtZGlyYXBwbAAAAAAAAAAAAAAAACxpbHN0AAAAJKl0b28AAAAcZGF0YQAAAAEAAAAATGF2ZjYwLjMuMTAw",
);
